<div class="user-ad-container" id="<?php echo($tsx['tsx_ad_id']); ?>">
	<video id="video--<?php echo $tsx['media']['storyId'];?>" class="video-js vjs-default-skin <?php echo($tsx['rvad_con']); ?>"  controls preload="auto" poster="<?php  echo $tsx['media']['video_thumb'];?>" data-setup="{}" data-post-video="<?php echo $tsx['media']['storyId'];?>" style="width:100%;height:500px;">
	  <source
	     src="<?php echo $tsx['media']['filename'];?>"
	     type="application/x-mpegURL">
	</video>
</div>  
<script>
fluidPlayer('video--<?php echo $tsx['media']['storyId'];?>', {
    layoutControls: {
        primaryColor:           "<?php echo $tsx['config']['btn_background_color'];?>",
        fillToContainer: true,
    }
});
</script>