<div class="col-sm-3 ch_main_items">
	<div class="prod_img">
		<a href="<?php echo $tsx['order']->product['url'] ?>" data-ajax="?link1=post&id=<?php echo $tsx['order']->product['seo_id']?>">
			<img src="<?php echo $tsx['order']->product['images'][0]['image']?>">
		</a>
		<div><?php echo (!empty($tsx['currencies'][$tsx['order']->product['currency']]['symbol'])) ? $tsx['currencies'][$tsx['order']->product['currency']]['symbol'] : $tsx['config']['classified_currency_s'];?><?php echo $tsx['order']->product['price_format']?></div>
		<?php if ($tsx['can_review'] > 0 && $tsx['is_reviewed'] < 1) { ?>
			<a class="btn" href="javascript:void(0)" onclick="OpenWriteReview('<?php echo $tsx['order']->product['id']?>')"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></svg> <?php echo $tsx['lang']['write_review']; ?></a>
		<?php } ?>
	</div>
    <div class="prod_info">
        <h4><a href="<?php echo $tsx['order']->product['url'] ?>" data-ajax="?link1=post&id=<?php echo $tsx['order']->product['seo_id']?>"><?php echo $tsx['order']->product['name'];?></a></h4>
        <div class="price-wrap">
			<div class="quantity">
				Qty <?php echo $tsx['order']->units ?>
			</div>
		</div>
    </div>
</div>