<div class="leftcol-sidebar left-col-sidebar-hidden"><?php echo tsx_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="joinda_main_float_head contactus">
		<div class="container">
			<h1><?php echo $tsx['lang']['privacy_policy']; ?></h1>
		</div>
	</div>
	
	<div class="joinda_main_blogs_bg"></div>
	
	<div class="joinda_content tsx_terms_page">
		<div class="setting-well">
			<?php echo $tsx['lang']['privacy_policy_page'];?>
		</div>
	</div>
</div>

<?php echo tsx_Loadpage('footer/content'); ?>

<script>
$('.joinda_main_blogs_bg').css('height', ($('.joinda_main_float_head').height()) + 'px');
</script>