<div class="leftcol-sidebar"><?php echo tsx_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 middlecol">
			<?php $up = tsx_GetUserProType($tsx['user']['pro_type']); ?>
			<div class="alert alert-warning">
				<?php if (!empty(in_array($tsx['user']['pro_type'], array_keys($tsx['pro_packages'])) && !empty($tsx['pro_packages'][$tsx['user']['pro_type']]['image'])) && $_COOKIE['mode'] == 'day') { ?>
					<img src="<?php echo($tsx['pro_packages'][$tsx['user']['pro_type']]['image']) ?>" class="pro_packages_icon_inline">
				<?php }
				elseif (!empty(in_array($tsx['user']['pro_type'], array_keys($tsx['pro_packages'])) && !empty($tsx['pro_packages'][$tsx['user']['pro_type']]['night_image'])) && $_COOKIE['mode'] == 'night') { ?>
					<img src="<?php echo($tsx['pro_packages'][$tsx['user']['pro_type']]['night_image']) ?>" class="pro_packages_icon_inline">
				<?php } else{ ?>
					<i class="fa fa-<?php echo $up['icon'];?> fa-fw"></i> 
				<?php } ?>
				<?php 
					$string = str_replace('{type_name}', $up['type_name'], $tsx['lang']['boost_posts_in_same_time']);
					$string = str_replace('{can_boost}', $up['can_boost'], $string);
					echo $string;
				?>
			</div>
			<div class="alert alert-info">
				<i class="fa fa-check fa-fw"></i> <?php echo $tsx['lang']['boosted_pages_viewable'];?>
			</div>
			<div class="saved-posts">
				<?php
					$stories = tsx_GetBoostedPosts($tsx['user']['user_id']);
					if (count($stories) <= 0) {
						echo tsx_LoadPage('boosted-posts/no-posts');
					} else {
						foreach ($stories as $tsx['story']) {
							echo tsx_LoadPage('story/content');
						}
					}
				?>
			</div>
		</div>
		<?php echo tsx_LoadPage('sidebar/content');?>
	</div>
</div>