<div class="joinda_content joinda_sett_content">
	<div class="tsx_page_hdng pag_neg_padd">
		<div class="tsx_page_hdng_innr">
			<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M22.7,19L13.6,9.9C14.5,7.6 14,4.9 12.1,3C10.1,1 7.1,0.6 4.7,1.7L9,6L6,9L1.6,4.7C0.4,7.1 0.9,10.1 2.9,12.1C4.8,14 7.5,14.5 9.8,13.6L18.9,22.7C19.3,23.1 19.9,23.1 20.3,22.7L22.6,20.4C23.1,20 23.1,19.3 22.7,19Z"></path></svg></span> <?php echo $tsx['lang']['delete_group'];?>
		</div>
	</div>
	<form action="#" method="post" class="form-horizontal setting-delete-page-form">
		<div class="setting-delete-page-alert setting-update-alert"></div>
		<div class="joinda_form_fields">
			<label for="passtsxrd"><?php echo $tsx['lang']['passtsxrd']; ?></label>
			<input id="passtsxrd" name="passtsxrd" type="passtsxrd" required>
		</div>
		<input type="hidden" name="group_id" value="<?php echo $tsx['setting']['id'];?>">
		<div class="text-center">
			<button class="btn btn-main btn-mat btn-mat-raised add_joinda_loader" type="submit"><?php echo $tsx['lang']['delete']; ?></button>
		</div>
		<input type="hidden" name="hash_id" value="<?php echo tsx_CreateSession();?>">
	</form>
</div>
<script type="text/javascript">
$(function() {
  $('form.setting-delete-page-form').ajaxForm({
    url: tsx_Ajax_Requests_File() + '?f=groups&s=delete_group',
    beforeSend: function() {
      $('.setting-delete-page-form').find('.add_joinda_loader').addClass('btn-loading');
    },
    success: function(data) {
      if (data.status == 200) {
        $('.setting-delete-page-alert').html('<br><div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          window.setTimeout(function() {
            window.location.href = data.location;
          },2000);
        });
      } else {
        var errors = data.errors.join("<br>");
        $('.setting-delete-page-alert').html('<br><div class="alert alert-danger">' + errors + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      $('.setting-delete-page-form').find('.add_joinda_loader').removeClass('btn-loading');
    }
  });
});
</script>