<div class="profile-style" id="request-<?php echo $tsx['request']['user_id'] ?>">
   <a href="<?php echo $tsx['request']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $tsx['request']['username']?>">
      <div class="avatar <?php echo tsx_RightToLeft('pull-left');?>">
         <img src="<?php echo $tsx['request']['avatar'];?>" alt="<?php echo $tsx['request']['name']; ?> Profile Picture" />
      </div>
      <?php echo $tsx['request']['name']; ?>
      <?php if($tsx['request']['verified'] == 1) { ?>
         <span class="verified-color">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $tsx['lang']['verified_user'];?>" data-toggle="tooltip"><path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" /></svg>
         </span>
      <?php } ?>
   </a>
   <div class="page-website">
      <?php echo tsx_UserStatus($tsx['request']['user_id'],$tsx['request']['lastseen']); ?>
   </div>
   <div>
   <span onclick="tsx_AcceptJoinGroup(<?php echo $tsx['request']['user_id']?>, <?php echo $tsx['setting']['id']?>);" class="btn btn-default btn-sm"><i class="fa fa-check"></i> <?php echo $tsx['lang']['accept']; ?></span>
   <span onclick="tsx_DeleteJoinGroup(<?php echo $tsx['request']['user_id']?>, <?php echo $tsx['setting']['id']?>);" class="btn btn-default btn-sm"><i class="fa fa-remove"></i> <?php echo $tsx['lang']['delete']; ?></span>
   </div>
</div>