<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 middlecol">
		<div class="page-margin mt-0 mab-0">
					<div class="wo_page_hdng pag_neg_padd pag_alone">
						<div class="wo_page_hdng_innr big_size">
						<svg width="583" height="639" viewBox="0 0 583 639" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M431.95 213.63L387.99 182.8L450.5 59.6802L526.43 112.94L431.95 213.63Z" fill="url(#paint0_linear_1118_285)"/>
							<path d="M576.36 126.43C559 152.12 508.71 148.48 464.04 118.29C419.36 88.1001 397.21 42.8101 414.57 17.1201C431.93 -8.56991 482.22 -4.9299 526.89 25.2601C571.57 55.4401 593.72 100.74 576.36 126.43Z" fill="url(#paint1_linear_1118_285)"/>
							<path d="M455.59 294.71C433.7 327.1 280 223.26 301.88 190.86C323.76 158.47 375.91 155.46 418.36 184.13C460.8 212.81 477.47 262.32 455.59 294.71Z" fill="url(#paint2_linear_1118_285)"/>
							<path d="M301.04 366.27L293.05 360.67L371.53 248.77L379.53 254.37L301.04 366.27Z" fill="url(#paint3_linear_1118_285)"/>
							<path d="M470.13 305.89L469.83 569.03C469.83 581.83 459.09 592.21 445.84 592.21H67.42C54.17 592.21 43.43 581.83 43.43 569.03V214.77C43.43 201.97 54.17 191.59 67.42 191.59H268.48V141.99H28.68C12.84 141.99 0 154.4 0 169.71V610.29C0 625.6 12.84 638.01 28.68 638.01H484.58C500.42 638.01 513.26 625.6 513.26 610.29V305.89H470.13Z" fill="url(#paint4_linear_1118_285)"/>
							<path d="M267.41 305.89H10.2299L8.62988 327.45H267.41V305.89Z" fill="url(#paint5_linear_1118_285)"/>
							<defs>
							<linearGradient id="paint0_linear_1118_285" x1="401.441" y1="113.526" x2="521.119" y2="183.107" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint1_linear_1118_285" x1="408.654" y1="71.7724" x2="582.274" y2="71.7724" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint2_linear_1118_285" x1="299.755" y1="232.674" x2="465.219" y2="232.674" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint3_linear_1118_285" x1="293.047" y1="307.519" x2="379.528" y2="307.519" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint4_linear_1118_285" x1="10.9908" y1="351.403" x2="504.626" y2="491.989" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint5_linear_1118_285" x1="22.4089" y1="316.671" x2="281.197" y2="316.671" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="1" stop-color="#121011"/>
							</linearGradient>
							</defs>
						</svg>

							
							<?php echo $wo['lang']['create_events'];?>
						</div>
					</div>
				</div>

			<div class="page-margin wow_content wow_sett_content">
				<form class="form form-horizontal" method="post" id="insert-event">
					<div class="wow_form_fields">
						<label for="event-name"><?php echo $wo['lang']['name']; ?></label>
						<input id="event-name" name="event-name" type="text">
					</div>
					<div class="wow_form_fields">
						<label for="event-locat"><?php echo $wo['lang']['location']; ?></label>
						<input id="event-locat" name="event-locat" type="text">
					</div>
					<?php if ($wo['config']['google_map'] == 1 || $wo['config']['yandex_map'] == 1) { ?>
						<div id="review-location">
							<div id="place" <?php echo($wo['config']['yandex_map'] == 1 ? 'class="yandex_ads_map"' : '') ?>></div>
						</div>
					<?php } ?>
					<div class="wow_form_fields">
						<label for="event-start"><?php echo $wo['lang']['event_start']; ?></label>
						<div class="row">
							<div class="col-md-6">
								<input type="text" class="date" id="event-start" name="event-start-date">
							</div>
							<div class="col-md-6">
								<input type="text" id="event-start-time" class="time1" name="event-start-time">
							</div>
						</div>
					</div>
					<div class="wow_form_fields">
						<label for="event-end-date"><?php echo $wo['lang']['event_end']; ?></label>
						<div class="row">
							<div class="col-md-6">
								<input type="text" class="date1" name="event-end-date" id="event-end-date">
							</div>
							<div class="col-md-6">
								<input type="text" id="event-end-time" class="time1" name="event-end-time">
							</div>
						</div>
					</div>
					<div class="wow_form_fields">
						<label for="event-description"><?php echo $wo['lang']['description']; ?></label>
						<textarea name="event-description" id="event-description" rows="5"></textarea>
					</div>
					<div class="wow_form_fields">
						<label><?php echo $wo['lang']['image']; ?></label>
						<div class="wow_fcov_image">
							<div id="wow_fcov_img_holder">
								<img src="<?php echo $wo['config']['theme_url'];?>/img/ad_pattern.png">
							</div>
							<div class="upload_ad_image" onclick="document.getElementById('event-cover').click(); return false">
								<div class="upload_ad_image_content">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z"></path></svg> <?php echo $wo['lang']['choose_image'] ?>
								</div>
							</div>
						</div>
					</div>
					
					<div class="setting-update-alert" id="event-alert"></div>
					
					<div class="text-center">
						<a class="btn btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-events'); ?>" data-ajax="?link1=my-events">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> <?php echo $wo['lang']['go_back'];?>
						</a>
						<button class="btn btn-main btn-mat btn-mat-raised add_wow_loader" type="submit"><?php echo $wo['lang']['publish']; ?></button>
					</div>
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
					<input type="file" name="event-cover" class="hidden" id="event-cover" accept="image/*">
				</form>
			</div>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>

<script>
	<?php if ($wo['config']['google_map'] == 1) { ?>
      	$(document).on('change', '#event-locat', function(event) {
	        if ($(this).val().length >= 3) {
	          $("#review-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + $("#event-locat").val() + '&language=en"></iframe>')
	        }else{
	          $("#review-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=us&language=en"></iframe>')
	        }
      	});
     <?php } ?>
     <?php if ($wo['config']['yandex_map'] == 1) { ?>
		 	$(document).on('change', '#event-locat', function(event) {
		   	var myMap;
		    ymaps.geocode($(this).val()).then(function (res) {
		    	$("#review-location #place").html('');
		        myMap = new ymaps.Map('place', {
		            center: res.geoObjects.get(0).geometry.getCoordinates(),
		            zoom : 10
		        });
		        myMap.geoObjects.add(new ymaps.Placemark(res.geoObjects.get(0).geometry.getCoordinates(), {
		            balloonContent: ''
		        }));
		    });
		 	});

		 <?php } ?>
  jQuery(document).ready(function($) {
		$(".date").flatpickr({
			dateFormat: "Y-m-d",
			altInput: true,
			altFormat: "F j, Y",
			minDate: "today",
		});
		
		$(".time1").flatpickr({
			enableTime: true,
			noCalendar: true,
			dateFormat: "H:i",
		});
		
		$(".date1").flatpickr({
			dateFormat: "Y-m-d",
			altInput: true,
			altFormat: "F j, Y",
			minDate: new Date().fp_incr(1),
		});


      $("#event-cover").change(function(event) {
        $("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
      });

      $('#insert-event').ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=insert-event',
            beforeSend: function() {
              $('.wo_settings_page').find('.add_wow_loader').addClass('btn-loading');
            },
            success: function(data) {
              if (data['status'] == 200) {
                $("#event-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
                window.location = data['url'];
              }
              else if (data['message']) {
                $("#event-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
              } 
              $('.wo_settings_page').find('.add_wow_loader').removeClass('btn-loading');
            }
      });
  });
</script>