<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 singlecol profile-lists ">
			<div class="page-margin mt-0">
					<div class="wo_page_hdng pag_neg_padd pag_alone">
						<div class="wo_page_hdng_innr big_size">
							
						<svg width="384" height="451" viewBox="0 0 384 451" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M366.99 302.27H0V25.3C0 11.32 11.33 0 25.3 0H366.98C382.03 0 389.56 18.21 378.91 28.84L256.34 151.13L378.91 273.42C389.57 284.06 382.04 302.27 366.99 302.27Z" fill="black"/>
							<path d="M38.38 451H4.03C1.8 451 0 449.19 0 446.97V316.66H38.38V451Z" fill="black"/>
						</svg>

							<?php echo $wo['lang']['pages']; ?>
						</div>
						<a class="btn btn-main btn-mat btn-mat-raised create-btn-bottom" href="<?php echo Wo_SeoLink('index.php?link1=create-page');?>" data-ajax="?link1=create-page"><svg height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg"><g id="_03_Login" data-name="03 Login"><path d="m256 512a25 25 0 0 1 -25-25v-462a25 25 0 0 1 50 0v462a25 25 0 0 1 -25 25z"/><path d="m487 281h-462a25 25 0 0 1 0-50h462a25 25 0 0 1 0 50z"/></g></svg></a>
					</div>
				</div>
			<div class="page-margin wow_content">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_my_pages">
				<div>
					<?php
						$pages = Wo_GetMyPages();
						if (count($pages) > 0) {
							foreach ($pages as $wo['page']) {
								echo Wo_LoadPage('page/pages-list');
							}
						} else {
							echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z"></path></svg>' . $wo['lang']['no_pages_found'] . '</div>';
						}
					?>
				</div>
			</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php echo Wo_LoadPage('sidebar/content');?>