<div class="page_list flex_pages boosted_pages">
	<div class="info">
		<div class="page-cover" style="background-image: url('<?php echo $wo['page']['cover']?>')"></div>
		<a href="<?php echo $wo['page']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['page']['page_name'];?>">
			<div class="avatar">
				<img src="<?php echo $wo['page']['avatar'];?>" alt="<?php echo $wo['page']['page_name']; ?> Profile Picture" />
				<div>
					<span class="page_title"><?php echo $wo['page']['page_title']; ?></span>
					<span><?php echo Wo_CountPageLikes($wo['page']['page_id']);?> <?php echo $wo['lang']['people_likes_this']; ?></span>
				</div>
			</div>
		</a>
	</div>
	<div class="btns">
		<div class="page_list_endDiv">
			<span><?php echo $wo['page']['category']?></span>
			<?php if( isset( $wo['page']['Wo_PageSug'] ) ){ ?>
				<?php echo Wo_GetLikeButton($wo['page']['page_id']);?>
			<?php }else{ ?>
		    	<a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' .  $wo['page']['page_name']); ?>" data-ajax="?link1=page-setting&page=<?php echo $wo['page']['page_name'];?>" class="btn btn-info btn-sm btn-mat btn-mat-raised" title="<?php echo $wo['lang']['edit']; ?>">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8,12H16V14H8V12M10,20H6V4H13V9H18V12.1L20,10.1V8L14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H10V20M8,18H12.1L13,17.1V16H8V18M20.2,13C20.3,13 20.5,13.1 20.6,13.2L21.9,14.5C22.1,14.7 22.1,15.1 21.9,15.3L20.9,16.3L18.8,14.2L19.8,13.2C19.9,13.1 20,13 20.2,13M20.2,16.9L14.1,23H12V20.9L18.1,14.8L20.2,16.9Z" /></svg>
				</a>
			<?php } ?>
		</div>
	</div>
</div>