<span id="join-<?php echo $tsx['join']['id']?>">
    <button type="button" onclick="tsx_RegisterGroupJoin(<?php echo $tsx['join']['id'];?>, <?php echo ($tsx['join']['join_privacy'] == 2) ? 1 : 0;?>)" class="btn btn-default btn-sm tsx_follow_btn" id="tsx_useract_btn">
       <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
       <span class="button-text"> <?php echo $tsx['lang']['join'];?></span>
    </button>
</span>