<span id="join-<?php echo $tsx['join']['id']?>">
    <button type="button" onclick="tsx_RegisterGroupJoin(<?php echo $tsx['join']['id'];?>, <?php echo ($tsx['join']['join_privacy'] == 2) ? 1 : 0;?>)" class="btn-requested btn btn-default btn-sm tsx_request_btn" id="tsx_useract_btn">
       <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
       <span class="button-text"> <?php echo $tsx['lang']['requested'];?></span>
    </button>
</span>