<span id="join-<?php echo $tsx['join']['id']?>">
    <button type="button" onclick="tsx_RegisterGroupJoin(<?php echo $tsx['join']['id'];?>)" class="btn btn-active btn-default btn-sm tsx_following_btn" id="tsx_useract_btn">
       <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>
       <span class="button-text"> <?php echo $tsx['lang']['joined'];?></span>
    </button>
</span>