<div class="verification btn-sm btn btn-danger" onclick="tsx_RemoveVerification(<?php echo $tsx['verification']['id']?>,'<?php echo $tsx['verification']['type']?>');" id="tsx_useract_btn">
	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
	<?php echo $tsx['lang']['pending'];?>
</div>