<span id="Follow-<?php echo $tsx['follow']['user_id']?>" title="<?php echo $tsx['lang']['unfriend'];?>">
    <button type="button" onclick="tsx_RegisterFollow(<?php echo $tsx['follow']['user_id'];?>,0,true)" class="btn btn-active btn-default btn-sm tsx_following_btn" id="tsx_useract_btn">
       <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><polyline points="17 11 19 13 23 9"></polyline></svg>
       <span class="button-text"> <?php echo $tsx['lang']['friends_btn'];?></span>
    </button>
</span>