<style>
	.page-margin{margin-top:0;}
body, .tsx_about_wrapper_parent {
    padding-left: 0;
}
.tsx_job_head_filter {
    overflow: inherit!important;
    justify-content: space-between;
    padding: 5px 20px;
}
.joinda_main_float_head {
    background: #cce8f7;
}
</style>
<?php if($tsx['language_type'] == 'rtl') { ?>
    <style>
      body {
            padding-left: 30rem!important;
            padding-right: 0!important;
        }
    </style>
<?php } ?>
<div class="leftcol-sidebar left-col-sidebar-hidden"><?php echo tsx_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin products tsx_market">
	<div class="joinda_main_float_head new_market blogs">
			<div class="container" style="padding:0;">
				<img src="<?php echo $tsx['config']['theme_url'];?>/img/productMain.webp" class="products-mainImage" alt="content writing">
			</div>
			<div class="joinda_content tsx_job_head_filter tsx_market_head_filter">
			<h1><?php echo $tsx['lang']['market']; ?></h1>
				<div class="market__inps">
				<div class="search-blog">
					<form action="">
						<?php
							$placeholder = $tsx['lang']['search_for_products_main']; 
							if (!empty($category_name)) {
								$placeholder = str_replace('{category_name}', $category_name, $tsx['lang']['search_for_products']);
				    	    }
						?>
						<input type="text" onkeyup="tsx_SearchProducts(this.value)" placeholder="<?php echo $placeholder; ?>" id="product-text">
					</form>
				</div>
				<div class="dropdown market_widget">
					<div class="m_widget_head dropdown-toggle" data-toggle="dropdown" role="button">
						<?php echo $tsx['lang']['sort_by'];?> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M7,10L12,15L17,10H7Z" /></svg>
					</div>
					<div class="dropdown-menu">
						<div class="market_categories">
							<ul class="product-sort-slider">
								<li class="active" onclick="changePriceSortValue('latest');$(this).addClass('active');"><a href="javascript:void(0)"><?php echo $tsx['lang']['latest'] ?></a></li>
								<li onclick="changePriceSortValue('price_low');$(this).addClass('active');"><a href="javascript:void(0)"><?php echo $tsx['lang']['price_low'] ?></a></li>
								<li onclick="changePriceSortValue('price_high');$(this).addClass('active');"><a href="javascript:void(0)"><?php echo $tsx['lang']['price_high'] ?></a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="dropdown market_widget">
					<div class="m_widget_head dropdown-toggle" data-toggle="dropdown" role="button">
						<?php echo $tsx['lang']['categories'];?> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M7,10L12,15L17,10H7Z" /></svg>
					</div>
					<div class="dropdown-menu">
						<div class="market_categories">
							<ul class="product-category-slider">
								<?php 
									$category_id = (!empty($_GET['c_id'])) ? (int) $_GET['c_id'] : 0;
									foreach ($tsx['products_categories'] as $key => $category) {
										$active = ($category_id == $key) ? 'active' : '';
								?>
									<li class="<?php echo $active?>" data_prodect_cat_id="<?php echo($key) ?>"><a href="<?php echo tsx_SeoLink('index.php?link1=products&c_id=' . $key);?>"><?php echo $category;?></a></li>
								<?php } ?>
							</ul>
						</div>
					</div>
				</div>
				<?php if ( !empty($_GET['c_id']) && !empty($tsx['products_sub_categories'][$_GET['c_id']])) { ?>
					<div class="dropdown market_widget">
						<div class="m_widget_head dropdown-toggle" data-toggle="dropdown" role="button">
							<?php echo $tsx['lang']['sub_category'];?> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M7,10L12,15L17,10H7Z" /></svg>
						</div>
						<div class="dropdown-menu">
							<div class="market_categories">
								<ul class="product-category-slider-sub">
									<?php 
										$category_id = (!empty($_GET['sub_id'])) ? (int) $_GET['sub_id'] : 0;
										foreach ($tsx['products_sub_categories'][$_GET['c_id']] as $key => $category) {
											$active = ($category_id == $category['id']) ? 'active' : '';
									?>
										<li class="<?php echo $active?>" data_prodect_cat_id="<?php echo($category['id']) ?>"><a href="<?php echo tsx_SeoLink('index.php?link1=products&c_id=' . $_GET['c_id'].'&sub_id='.$category['id']);?>"><?php echo $category['lang'];?></a></li>
									<?php } ?>
								</ul>
							</div>
						</div>
					</div>
				<?php } ?>
				<div class="dropdown market_widget">
					<div class="m_widget_head dropdown-toggle" data-toggle="dropdown" role="button">
						<?php echo $tsx['lang']['location_dist'];?> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M7,10L12,15L17,10H7Z" /></svg>
					</div>
					<div class="dropdown-menu">
						<div class="select-nearby-users-distance">
							<form>
								<input type="range" class="cusrange" id="nearby-users-distance" name="amountRange" onchange="tsx_SearchProductsNearBy();" value="0" min="0" max="300" oninput="this.form.amountInput.value=this.value">
								<input type="number" name="amountInput" min="0" max="4000" value="0" oninput="this.form.amountRange.value=this.value" readonly id="cusrange-reader"/> km
							</form>
						</div>
					</div>
				</div>
				<?php if ($tsx['loggedin'] == true) { ?>
				<?php if ($tsx['config']['nearby_shop_system'] == 1) { ?>
					<a href="<?php echo($tsx['config']['site_url'].'/nearby_shops') ?>" data-ajax="?link1=nearby_shops" class="btn btn-danger btn-mat side_mkt_btn"><?php echo $tsx['lang']['nearby_shops'] ?></a>
				<?php } ?>
				<?php } ?>
				</div>
			</div>
	</div>
	
	<div class="pageSubHeadlineDiv">
		<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28"><g id="Marketplace" transform="translate(-1159 -21)"><path id="Path_4887" data-name="Path 4887" d="M3387.6,1446.51v13.09a1.386,1.386,0,0,1-1.4,1.4h-22.4a1.386,1.386,0,0,1-1.4-1.4v-13.09a5.585,5.585,0,0,1-1.4-3.71v-8.4a1.387,1.387,0,0,1,1.4-1.4h25.2a1.386,1.386,0,0,1,1.4,1.4v8.4A5.637,5.637,0,0,1,3387.6,1446.51Zm-9.8-3.71a1.4,1.4,0,1,1,2.8,0,2.8,2.8,0,0,0,5.6,0v-7h-22.4v7a2.8,2.8,0,0,0,5.6,0,1.4,1.4,0,1,1,2.8,0,2.8,2.8,0,0,0,5.6,0Z" transform="translate(-2202 -1412)"></path></g></svg>
		<p><?php echo $tsx['lang']['market']; ?></p>
	</div>
	<div class="joinda_main_blogs_bg"></div>
	
	<div class="row">
		<div class="col-md-12 products-mainDiv">
			<div class="latest-products">
				<?php
					$category_name = '';
					$data = array();
					if (!empty($_GET['c_id'])) {
						if (is_numeric($_GET['c_id'])) {
							if (array_key_exists($_GET['c_id'], $tsx['products_categories'])) {
								?>
								<input type="hidden" value="<?php echo tsx_Secure($_GET['c_id']); ?>" id="c_id" />
								<?php
								$category_name = $tsx['products_categories'][$_GET['c_id']];
								$data['c_id'] = tsx_Secure($_GET['c_id']);
							}
						}
						if (!empty($tsx['products_sub_categories'][$_GET['c_id']]) && !empty($_GET['sub_id'])) {
							foreach ($tsx['products_sub_categories'][$_GET['c_id']] as $key => $value) {
								if ($_GET['sub_id'] == $value['id']) { ?>
									<input type="hidden" value="<?php echo tsx_Secure($_GET['sub_id']); ?>" id="sub_id" />
									<?php
									$data['sub_id'] = tsx_Secure($value['id']);
									break;
								}
							}
						}
					} else {
						echo '<input type="hidden" value="0" id="c_id" />';
						echo '<input type="hidden" value="" id="sub_id" />';
					}
				?>
				<div class="market_bottom">
					<?php
						$data['limit'] = 10;
						$products = tsx_GetProducts($data);
						if (count($products) > 0) {
					?>
					<div id="products" class="row">
						<?php
						foreach ($products as $key => $tsx['product']) {
							echo tsx_LoadPage('products/products-list'); 
						}
						} else {
							echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,13A5,5 0 0,1 7,8H9A3,3 0 0,0 12,11A3,3 0 0,0 15,8H17A5,5 0 0,1 12,13M12,3A3,3 0 0,1 15,6H9A3,3 0 0,1 12,3M19,6H17A5,5 0 0,0 12,1A5,5 0 0,0 7,6H5C3.89,6 3,6.89 3,8V20A2,2 0 0,0 5,22H19A2,2 0 0,0 21,20V8C21,6.89 20.1,6 19,6Z"></path></svg>' . $tsx['lang']['no_available_products'] . '</div>';
						}
						?>
					</div>
				</div>
			</div> 	

		<div class="clear"></div>
	</div>
</div>

<div class="posts_load load-produts">
			<?php if (count($products) > 0): ?>
				<div class="load-more">
                    <button class="btn btn-default text-center pointer" onclick="tsx_LoadProducts();"><?php echo $tsx['lang']['load_more_products'] ?></button></div>
                <?php endif ?>
			</div>
</div>
<div class="sidebar-conatnier">
    <div class="col-md-3 sidebar rightcol">
        <?php echo tsx_LoadPage('chat/content'); ?>
    </div>
</div>

<?php echo tsx_LoadPage('footer/content'); ?>

<script>

function changePriceSortValue(price_sort) {
	cat_id = $('.product-category-slider').find('.active').attr('data_prodect_cat_id');
	sub_id = $('.product-category-slider-sub').find('.active').attr('data_prodect_cat_id');
	distance = $('#distance_val').text();
	$('.product-sort-slider li').removeClass('active');
	$(this).addClass('active');
	
	$.post(tsx_Ajax_Requests_File() + '?f=get_prodects_by_filter', {price_sort: price_sort, cat_id:cat_id, sub_id:sub_id, distance: distance}, function (data) {
		if (data.status == 200) {
			if (data.html.length > 0) {
				$('#products').html(data.html);
			} else {
				$('#products').html('<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,13A5,5 0 0,1 7,8H9A3,3 0 0,0 12,11A3,3 0 0,0 15,8H17A5,5 0 0,1 12,13M12,3A3,3 0 0,1 15,6H9A3,3 0 0,1 12,3M19,6H17A5,5 0 0,0 12,1A5,5 0 0,0 7,6H5C3.89,6 3,6.89 3,8V20A2,2 0 0,0 5,22H19A2,2 0 0,0 21,20V8C21,6.89 20.1,6 19,6Z"></path></svg><?php echo $tsx['lang']['no_available_products'] ?></div>');
			}
		}
	});
}

function tsx_SearchProductsNearBy() {
	length = $('#cusrange-reader').val();
	text_value = $('#product-text').val();
	var c_id = 0;
	if ($('#c_id').length > 0) {
		c_id = $('#c_id').val();
	}
	var sub_id = $('#sub_id').val();
	$.post(tsx_Ajax_Requests_File() + '?f=search_products', {value: text_value, c_id:c_id, sub_id:sub_id, length: length}, function (data) {
		if (data.status == 200) {
			if (data.html.length > 0) {
				$('#products').html(data.html);
			} else {
				$('#products').html('<?php echo $tsx['lang']['no_available_products'] ?>');
			}
		}
	});
}
function tsx_LoadProducts() {
	$('.load-produts').html('<div class="white-loading list-group"><div class="cs-loader"><div class="cs-loader-inner"><label> ●</label><label> ●</label><label> ●</label><label> ●</label><label> ●</label><label> ●</label></div></div></div>');
	var $c_id = $('#c_id').val();
	var sub_id = $('#sub_id').val();
	var $last_id = $('.product:last').attr('data-id');
	var length = $('#cusrange-reader').val();
	$.post(tsx_Ajax_Requests_File() + '?f=load_more_products', {last_id: $last_id, c_id:$c_id, sub_id:sub_id, length: length}, function (data) {
		if (data.status == 200) {
			if (data.html.length > 0) {
				$('.load-produts').html('<div class="load-more"><button class="btn btn-default text-center pointer" onclick="tsx_LoadProducts();"><i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $tsx['lang']['load_more_products'] ?></button></div>');
				$('#products').append(data.html);
			} else {
				$('.load-produts').html('<div class="load-more"><button class="btn btn-default text-center pointer" onclick="tsx_LoadProducts();"><?php echo $tsx['lang']['no_available_products'] ?></button></div>');
			}
		}
	});
}
function tsx_SearchProducts(value) {
	length = $('#cusrange-reader').val();
	var c_id = 0;
	if ($('#c_id').length > 0) {
		c_id = $('#c_id').val();
	}
	var sub_id = $('#sub_id').val();
	$.post(tsx_Ajax_Requests_File() + '?f=search_products', {value: value, c_id:c_id, sub_id:sub_id, length: length}, function (data) {
		if (data.status == 200) {
			if (data.html.length > 0) {
				$('#products').html(data.html);
			} else {
				$('#products').html('<?php echo $tsx['lang']['no_available_products'] ?>');
			}
		}
	});
}
</script>