<div class="movies-film-wrapper" data-film-id="<?php echo $tsx['film']['id']; ?>">
	<figure>
		<a href="<?php echo $tsx['film']['url']; ?>">
			<img src="<?php echo $tsx['film']['cover']; ?>" alt="" class="responsive-img">
			<span class="movie_rating_sml"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></svg> <?php echo round($tsx['film']['rating'],1); ?></span>
		</a>
		<h3 title="<?php echo $tsx['film']['name']; ?>"><a href="<?php echo $tsx['film']['url']; ?>"><?php echo $tsx['film']['name']; ?></a></h3>
		<svg id="glyph" height="512" viewBox="0 0 64 64" width="512" xmlns="http://www.w3.org/2000/svg"><path d="m29 11v14a4 4 0 0 1 -4 4h-14a4 4 0 0 1 -4-4v-14a4 4 0 0 1 4-4h14a4 4 0 0 1 4 4zm24-4h-14a4 4 0 0 0 -4 4v14a4 4 0 0 0 4 4h14a4 4 0 0 0 4-4v-14a4 4 0 0 0 -4-4zm-28 28h-14a4 4 0 0 0 -4 4v14a4 4 0 0 0 4 4h14a4 4 0 0 0 4-4v-14a4 4 0 0 0 -4-4zm21 0a11 11 0 1 0 11 11 11 11 0 0 0 -11-11z"/></svg><p><?php echo $tsx['film']['genre']; ?></p>
		<span><strong><?php echo $tsx['lang']['producer']; ?></strong> <?php echo $tsx['film']['producer']; ?></span>
	</figure>
</div>