<div class="reply reply-container" id="comment_reply_<?php echo $tsx['reply']['id'];?>" data-reply-id="<?php echo $tsx['reply']['id'];?>">
   <a class="<?php echo tsx_RightToLeft('pull-left'); ?>" href="<?php echo $tsx['reply']['publisher']['url']?>">
   <img class="avatar <?php echo tsx_RightToLeft('pull-left'); ?>" src="<?php echo $tsx['reply']['publisher']['avatar']?>" alt="avatar">
   </a>
   <div class="comment-body">
      <div class="comment-heading reply-heading">
         <span class="user-popover" data-id="<?php echo $tsx['reply']['publisher']['id'];?>" data-type="<?php echo $tsx['reply']['publisher']['type'];?>">
         <a href="<?php echo $tsx['reply']['publisher']['url']?>" data-ajax="?link1=timeline&u=<?php echo $tsx['reply']['publisher']['username'];?>">
            <h4 class="user">
               <?php echo $tsx['reply']['publisher']['name']?>
            </h4>
         </a>
         </span>
         <?php  if($tsx['reply']['publisher']['verified'] == 1) {   ?>
         <span class="verified-color" data-toggle="tooltip" title="<?php echo $tsx['lang']['verified_user'];?>"><i class="fa fa-check-circle"></i></span>
         <?php } ?>
         <div class="<?php echo tsx_RightToLeft('pull-right');?> comment-options">
            <?php if ($tsx['reply']['post_onwer'] === true|| $tsx['reply']['onwer'] === true) {?>
            <span class="pointer" id="deleteComment" onclick="tsx_DeleteReplyComment(<?php echo $tsx['reply']['id']?>);">
            <i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i>
            </span>
            <?php } ?>
         </div>
         <span class="time ajax-time" title="<?php echo date('c',$tsx['reply']['time']);?>"><?php echo $tsx['reply']['time']?></span>
         <div class="reply-text"><?php echo $tsx['reply']['text']?></div>
         
         <div class="clear"></div>   
      </div>

      <?php if ($tsx['config']['second_post_button'] == 'reaction') { ?>
            <!-- reaction -->

            <div class="like-stat  stat-item post-like-status" style="float: left;margin: -2px 10px 0px 0px;">
              <span class="like-emo reply-reactions-icons-<?php echo $tsx['reply']['id']; ?>">
              <?php echo tsx_GetPostReactions($tsx['reply']['id'],"replay");?>
              </span>
              <!-- <span class="like-details">Arkaprava Majumder and 1k others</span> -->
            </div>

            <div class="tsx-reaction stat-item" style="max-width: 100%;padding: inherit;float: left;font-size: 13px;margin-top: 3px;position: relative;">
                <span class="like-btn" >
                    <?php
                    if (tsx_IsReacted($tsx['reply']['id'], $tsx['reply']['user_id'],"replay") === true) {    
                    echo '<span class="rstatus-reaction-'.$tsx['reply']['id'].' active-like"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg> <span class="r_likes-'.$tsx['reply']['id'].'">' . $tsx['lang']['liked'] . '</span></span>';   
                    } else {   
                    echo '<span class="rstatus-reaction-'.$tsx['reply']['id'].'"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg> <span class="r_likes-'.$tsx['reply']['id'].'">' . $tsx['lang']['like'] . '</span></span>';   
                    }    
                    ?>
                    <ul class="reactions-box">
                        <li class="reaction reaction-like" data-reaction="Like" onclick="tsx_RegisterReplyReaction(<?php echo $tsx['reply']['user_id']; ?>,<?php echo $tsx['reply']['id']; ?>,'Like');"></li>
                        <li class="reaction reaction-love" data-reaction="Love" onclick="tsx_RegisterReplyReaction(<?php echo $tsx['reply']['user_id']; ?>,<?php echo $tsx['reply']['id']; ?>,'Love');"></li>
                        <li class="reaction reaction-haha" data-reaction="HaHa" onclick="tsx_RegisterReplyReaction(<?php echo $tsx['reply']['user_id']; ?>,<?php echo $tsx['reply']['id']; ?>,'HaHa');"></li>
                        <li class="reaction reaction-joinda" data-reaction="joinda" onclick="tsx_RegisterReplyReaction(<?php echo $tsx['reply']['user_id']; ?>,<?php echo $tsx['reply']['id']; ?>,'joinda');"></li>
                        <li class="reaction reaction-sad" data-reaction="Sad" onclick="tsx_RegisterReplyReaction(<?php echo $tsx['reply']['user_id']; ?>,<?php echo $tsx['reply']['id']; ?>,'Sad');"></li>
                        <li class="reaction reaction-angry" data-reaction="Angry" onclick="tsx_RegisterReplyReaction(<?php echo $tsx['reply']['user_id']; ?>,<?php echo $tsx['reply']['id']; ?>,'Angry');"></li>
                    </ul>
                </span>
            </div>
        <?php } else { ?>

      <span class="comment-options">
            <span class="comment-icons">
            <span class="pointer" id="LikeReplyComment" onclick="tsx_RegisterCommentReplyLike(<?php echo $tsx['reply']['id']; ?>);">
            <?php if($tsx['reply']['is_comment_liked'] !== true) { ?>
            <i class="fa fa-thumbs-up progress-icon" data-icon="thumbs-up"></i>
            <?php } else { ?>
            <i class="fa fa-thumbs-up progress-icon active-like" data-icon="thumbs-up"></i>
            <?php } ?>
            </span> 
            <span id="comment-reply-likes">
            <?php echo $tsx['reply']['comment_likes'];?>
            </span> · 
            </span>
            <span class="pointer" id="tsxnderReplyComment" onclick="tsx_RegisterCommentReplytsxnder(<?php echo $tsx['reply']['id']; ?>);">
            <?php if($tsx['reply']['is_comment_tsxndered'] !== true) { ?>
            <i class="fa fa-<?php echo $tsx['second_post_button_icon'];?> progress-icon" data-icon="<?php echo $tsx['second_post_button_icon'];?>"></i>
            <?php } else {  ?>
            <i class="fa fa-<?php echo $tsx['second_post_button_icon'];?> progress-icon active-tsxnder" data-icon="<?php echo $tsx['second_post_button_icon'];?>"></i>
            <?php } ?>
            </span>
            <span id="comment-reply-tsxnders">
            <?php echo $tsx['reply']['comment_tsxnders'];?>
            </span> · 
      </span>

       <?php } ?>
       
   </div>
   <?php echo tsx_LoadPage('modals/delete-comment-reply');?>
</div>