<div class="story-container user-story-container" id="<?php echo $tsx['story']['id']; ?>" data-status-id="<?php echo $tsx['story']['id']; ?>">
    <div class="panel panel-white panel-shadow">
      <div class="ads-heading">
        
        <div class="<?php echo tsx_RightToLeft('pull-left');?> ads-image">
          <a data-ajax="?link1=timeline&u=<?php echo $tsx['story']['user_data']['username']?>">
          <img src="<?php echo $tsx['story']['user_data']['avatar']; ?>"  class="responsive-img" style="border-radius: 50%;">
          </a>
        </div>
        <div class="ads-meta">
          <div class="title h5">
            <p>
              <b><?php echo $tsx['story']['user_data']['name']; ?></b>
              
              <?php if ($tsx['story']['is_owner']):?>
	            <span class="pull-right pointer" onclick="tsx_DeleteStatus(<?php echo $tsx['story']['id']; ?>)">
	              	<i class="fa fa-trash-o"></i>
	            </span>
	          <?php endif;?>
              <span class="clear"></span>
            </p>
            <h6>
              <span class="time">
		        <span class="ajax-time" title="<?php echo date('c',$tsx['story']['posted']); ?>">
		          <?php echo tsx_Time_Elapsed_String($tsx['story']['posted']); ?>
		        </span>
		      </span>  
            </h6>
          </div>
        </div>
        <div class="ads-headline">
            <?php echo $tsx['story']['title'];?>
            <span>
              <?php echo $tsx['story']['description']; ?>
            </span>
        </div>
        <?php if (isset($tsx['story']['thumb'])): ?>
	        <div class="story-media-cont" id="<?php echo $tsx['story']['id']; ?>">
	          	<div class="story-image-wrapper user-story-gallery-<?php echo $tsx['story']['id']; ?>" id="fullsizeimg">
	          		<a href="<?php echo $tsx['story']['thumb']['filename']; ?>">
	          			<img src="<?php echo $tsx['story']['thumb']['filename']; ?>" alt="" style="max-width: 100%;">
	          		</a>
		          	<?php foreach ($tsx['story']['images'] as $image): ?>
		            	<?php if ($image['type'] == 'image'): ?>           		
							<a href="<?php echo $image['filename']; ?>"></a>	
		            	<?php endif; ?>
		            <?php endforeach; ?>
	            </div>
	        </div>
        <?php endif; ?>

        <?php if (count($tsx['story']['videos']) > 0): ?>
        	<hr>
        	<div class="story-media-cont">
	        	<?php foreach ($tsx['story']['videos'] as $tsx['media']): ?>
	    			<?php echo tsx_LoadPage('status/video'); ?>
	    		<?php endforeach; ?>
    		</div>
        <?php endif; ?>	
    	
      
      <div class="clear"></div>
    </div>
</div>
</div>

<script>
	// jQuery(document).ready(function($) {
	// 	var interval;
	// 	$('.user-story-gallery-<?php echo $tsx['story']['id']; ?>').magnificPopup({
	// 		delegate: 'a',
	// 		type: 'image',
	// 		tLoading: '',
	// 		gallery:{
	// 			enabled:true,
	// 		},
	// 		removalDelay: 300,

	// 		callbacks: {
	// 			open: function() {
	// 				tsx_StoryProgress();																			
	// 				if ($('.user-story-gallery-<?php echo $tsx['story']['id']; ?> a').length > 1) {
	// 					interval = setInterval(function() {
	// 				        $.magnificPopup.instance.next(true);
	// 				    }, 10000);
	// 				}
	// 				else if($('.user-story-gallery-<?php echo $tsx['story']['id']; ?> a').length == 1){
	// 					tsx_Delay(function(){
	// 						$('.user-story-gallery-<?php echo $tsx['story']['id']; ?>').magnificPopup('close');
	// 						tsx_ResetStory();
	// 					}, 10000)
	// 				}
	// 			},
	// 			close:function() {
	// 				clearInterval(interval);
	// 				tsx_ResetStory();
	// 			}
	// 		}
	// 	});	
	// });
</script>