<style>
@font-face {
    font-family: OpenSansLight;
    src: url("<?php echo $tsx['config']['theme_url'];?>/fonts/OpenSansLight/OpenSansLight.tsxff") format("tsxff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansRegular;
    src: url("<?php echo $tsx['config']['theme_url'];?>/fonts/OpenSansRegular/OpenSansRegular.tsxff") format("tsxff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansSemiBold;
    src: url("<?php echo $tsx['config']['theme_url'];?>/fonts/OpenSansSemiBold/OpenSansSemiBold.tsxff") format("tsxff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansBold;
    src: url("<?php echo $tsx['config']['theme_url'];?>/fonts/OpenSansBold/OpenSansBold.tsxff") format("tsxff");
    font-weight: normal;
}
:root {
	--plyr-color-main: <?php echo $tsx['config']['btn_background_color'];?> ;
}

.tsx_follow_btn {
    background: <?php echo $tsx['config']['btn_hover_background_color'];?> !important;
}
.joinda_htag .htag_top {
    color: #666A76 !important;
}
.tsx_follow_btn:hover {
    background: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
.publisher-box .publisher-hidden-option #progress .progress, .publisher-box .publisher-hidden-option #percent, .tsx_new_wallet .joinda_mini_wallets h5 {
	color: <?php echo $tsx['config']['btn_background_color'];?>;
}



.navbar-default {
    background: <?php echo $tsx['config']['header_background'];?>; border: none;
    height: 56px;
    box-shadow: 0 2px 4px rgb(0 0 0 / 15%);
}
.mobile-bottomHeader{
    background: <?php echo $tsx['config']['header_background'];?>;
}
.round-check input[type="checkbox"]:checked + label:before, .round-check input[type="radio"]:checked + label:before {
    background: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
.group-messages-wrapper a{
    color: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
ul.profile-completion-bar li.completion-bar div.completion-bar-status {
    background: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
/*.joinda_srch_innr_filtr .round_check input:checked+label {
  background: <?php echo $tsx['config']['btn_background_color'];?> !important;
  color: <?php echo $tsx['config']['btn_color'];?> !important;
}*/
.result-bar {
    background: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
.featured-users .sidebar-title-back, .featured-users .pro-me-here a {
    color: #444 !important;
}

.lang_select_modal .language_info {
    background: <?php echo $tsx['config']['btn_background_color'];?>
}
.lang_select_modal .language_info h3 {
	color: <?php echo $tsx['config']['btn_color'];?>;
}



.avtive {
    border-color: <?php echo $tsx['config']['btn_background_color'];?> !important;
}

.new-update-alert {
    background: <?php echo $tsx['config']['btn_hover_background_color'];?>;
	color: <?php echo $tsx['config']['btn_color'];?>;
}

#tsx_nw_msg_page .msg_under_hood .mobilerightpane .messages-search-users-form .inner-addon .btn_contr {
	background: <?php echo $tsx['config']['btn_background_color'];?>;
	color: <?php echo $tsx['config']['btn_color'];?>;
}
#tsx_nw_msg_page .msg_under_hood .mobilerightpane .messages-search-users-form .inner-addon button.btn {
	color: <?php echo $tsx['config']['btn_color'];?>;
}
#tsx_nw_msg_page .msg_under_hood .mobilerightpane .messages-search-users-form .inner-addon button.btn:hover {
	background: <?php echo $tsx['config']['btn_hover_background_color'];?>;
}

.green-audio-player svg path {
	fill: <?php echo $tsx['config']['btn_background_color'];?>;
}
.green-audio-player .slider .gap-progress, .green-audio-player .slider .gap-progress .pin {
	background-color: <?php echo $tsx['config']['btn_background_color'];?> !important;
}

.add_as_cont_list label input:checked+div {
    background-color: <?php echo $tsx['config']['btn_background_color'];?>;
    color: <?php echo $tsx['config']['btn_color'];?>;
}

.barloading {
  background-color: transparent !important;
}
.barloading:before {
    background-color: #8dd9ff;
}
.left-sidebar ul li a i {
    color: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
.cs-loader-inner, .main  {
    color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.login input:focus, ul.profile-completion-bar li.completion-bar div.completion-bar-wrapper, .edit_grp_info_modal input.form-control:not(textarea):focus, .verfy_sett_email_phone input.form-control:not(textarea):focus {
    border-color: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
.login:not(.loading) button:hover {
    background: <?php echo $tsx['config']['btn_hover_background_color'];?> !important;
    color: <?php echo $tsx['config']['btn_color'];?>;
}
.tsx_setting_sidebar ul .list-group-item{
    background: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
.tsx_setting_sidebar ul .list-group-item a{
    color: <?php echo $tsx['config']['btn_color'];?>;
}
.tsx_settings_page .setting-panel input[type=text]:focus, .tsx_settings_page .setting-panel input[type=email]:focus, .tsx_settings_page .setting-panel input[type=passtsxrd]:focus, .tsx_settings_page .setting-panel select:focus, .tsx_settings_page .setting-panel textarea:focus {
    border-color: #03A9F4;
}

#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle{
    border-color: <?php echo $tsx['config']['btn_background_color'];?>;
}
#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle:after{
    background: <?php echo $tsx['config']['btn_background_color'];?>;
}
.tsx_page_hdng_menu > ul li.active a {
    box-shadow: inset 0px -2.5px #DF2A39;
}
.login button, .postCategory h5, .tsx_search_page .nav-tabs li.active a {
    background: <?php echo $tsx['config']['btn_background_color'];?> !important;
    color: <?php echo $tsx['config']['btn_color'];?> !important;
}
.mejs-controls .mejs-time-rail .mejs-time-current, .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current, .mejs-controls .mejs-volume-button .mejs-volume-slider .mejs-volume-current {
    background-color: <?php echo $tsx['config']['btn_background_color'];?> !important;
    background: <?php echo $tsx['config']['btn_background_color'];?> !important;
    background-image: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
.navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
    color: <?php echo $tsx['config']['header_color'];?> !important;
    background-color: <?php echo $tsx['config']['header_hover_border'];?> !important;
}
.navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:focus, .navbar-default .navbar-nav>.active>a:hover, .nav-names li:hover {
    color: <?php echo $tsx['config']['header_color'];?> !important;
    background-color: <?php echo $tsx['config']['header_hover_border'];?> !important;
}
body {
    background-color: <?php echo $tsx['config']['body_background'];?>;
}
.navbar-default .navbar-nav>li>a {
    color: <?php echo $tsx['config']['header_color'];?>;
    font-size: 13px;
}
a.unread-update {
    color: <?php echo $tsx['config']['header_color'];?> !important;
}
.btn-main {
    color: <?php echo $tsx['config']['btn_color'];?>;
    background-color: <?php echo $tsx['config']['btn_background_color'];?>;
    border-color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.btn-main:hover {
    color: <?php echo $tsx['config']['btn_hover_color'];?>;
    background-color: <?php echo $tsx['config']['btn_hover_background_color'];?>;
    border-color: <?php echo $tsx['config']['btn_hover_background_color'];?>;
}
.joinda_pops_head {
    background: <?php echo $tsx['config']['btn_hover_background_color'];?>;
}
.btn-main:focus {
	color: <?php echo $tsx['config']['btn_hover_color'];?>;
}
.active-tsxnder {
    color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.admin-panel .col-md-9 .list-group-item:first-child, .setting-panel .col-md-8 .list-group-item:first-child, .profile-lists .list-group-item:first-child, .col-md-8 .list-group-item:first-child, .col-md-3.custom .list-group-item:first-child, .col-sm-4 .list-group-item:first-child, .col-md-7 .list-group-item:first-child, .col-md-9 .list-group-item:first-child, .red-list .list-group-item:first-child, .active.list-group-item:first-child {
     color: #444;
     background-color: #fcfcfc;
     border-bottom: 1px solid #f1f1f1;
     padding: 18px;
}
.admin-panel .col-md-9 .list-group-item:first-child a, .setting-panel .col-md-8 .list-group-item:first-child a, .profile-lists .list-group-item:first-child a, .col-md-8 .list-group-item:first-child a, .col-md-7 .list-group-item:first-child a, .active.list-group-item:first-child a {
    color: #444 !important;
}
.list-group-item.black-list.active-list, .red-list.active-list {
    color: <?php echo $tsx['config']['btn_color'];?>;
    background-color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.list-group-item.black-list {
    background: <?php echo $tsx['config']['btn_background_color'];?>;
}
.profile-top-line {
    background-color: <?php echo $tsx['config']['btn_background_color'];?>;
}
#bar {
    background-color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.list-group-item.black-list a{
    color: <?php echo $tsx['config']['btn_color'];?>;
}
.list-group-item.black-list.active-list a{
    color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.main-color, .small-text a {
    color: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
.nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {
    color: <?php echo $tsx['config']['btn_color'];?>;
    cursor: default;
    color: <?php echo $tsx['config']['btn_background_color'];?>;
    border-bottom: 1px solid <?php echo $tsx['config']['btn_background_color'];?>;
    background-color: transparent
}
.btn-active {
    color: <?php echo $tsx['config']['btn_color'];?>;
    background: <?php echo $tsx['config']['btn_background_color'];?>;
    outline: none;
    border: 1px solid <?php echo $tsx['config']['btn_background_color'];?>
}
.btn-active:hover, .btn-active:focus {
    border: 1px solid <?php echo $tsx['config']['btn_hover_background_color'];?>;
    color: <?php echo $tsx['config']['btn_hover_color'];?>;
    background: <?php echo $tsx['config']['btn_hover_background_color'];?>;
}
.btn-active-color:hover {
    background: <?php echo $tsx['config']['btn_hover_background_color'];?>;
}

.chat-tab .chat-textarea .chat-btns-w .chat_optns {
    color: <?php echo $tsx['config']['btn_background_color'];?>;
    fill: <?php echo $tsx['config']['btn_background_color'];?>;
}

.profile-style .user-follow-button button.btn-active, .btn-login, .btn-register {
    background: <?php echo $tsx['config']['btn_background_color'];?>;
    color: <?php echo $tsx['config']['btn_color'];?>;
}
.profile-style .user-follow-button button.btn-active:hover, .btn-login:hover, .btn-login:focus, .btn-register:hover, .btn-register:focus {
    color: <?php echo $tsx['config']['btn_hover_color'];?>;
    background: <?php echo $tsx['config']['btn_hover_background_color'];?>;
}
.panel-login>.panel-heading a.active {
    color: <?php echo $tsx['config']['btn_background_color'];?>;
    font-size: 18px;
}
.hash {
    color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.message-text .hash {
    color: #fff !important;
}
.search-container .search-input {
    color: <?php echo $tsx['config']['header_color'];?> !important;
    background: <?php echo $tsx['config']['header_search_color'];?> !important;
}
.chat-messages-wrapper .outgoing .message-text {
    background: <?php echo $tsx['config']['btn_background_color'];?>;
    color: <?php echo $tsx['config']['btn_color'];?>;
}
.normal-container {
    width: 100%;
    height: 100%;
    margin-top: 15px;
}
.active.fa-thumbs-up {
    color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.api-ex-urls {
    background-color: <?php echo $tsx['config']['btn_background_color'];?>; color: <?php echo $tsx['config']['btn_color'];?>;
}
.user-username {
    color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.upload-image {
    border: 3px dashed <?php echo $tsx['config']['btn_background_color'];?>;
}
.events-tab-list li { background-color: <?php echo $tsx['config']['btn_background_color'];?>; }
.events-tab-list li:hover { background-color: <?php echo $tsx['config']['btn_background_color'];?>; }
.active-e-tab { background-color: <?php echo $tsx['config']['btn_background_color'];?> !important; }
.main { color: <?php echo $tsx['config']['btn_background_color'];?> !important; }
.events-list-dropup-menu ul li a:hover { background: <?php echo $tsx['config']['btn_background_color'];?>; }
.usr-offline { color: <?php echo $tsx['config']['btn_background_color'];?>; }
.blog-dd-ul li span:hover, .blog-dd-ul li a:hover { background: <?php echo $tsx['config']['btn_background_color'];?> !important; }
.blog_publ {background: <?php echo $tsx['config']['btn_background_color'];?> ; border: 1px solid <?php echo $tsx['config']['btn_background_color'];?> ; }
.slide-film-desc:hover, .movies-top-breadcrumb li:hover, .movies-top-breadcrumb li a:hover{
    color: <?php echo $tsx['config']['btn_background_color'];?> !important;
}
.movies h3.latest-movies, h3.recommended-movies {
    border-left: 3px solid  <?php echo $tsx['config']['btn_background_color'];?>;
}

.tsx_user_profile .user-bottom-nav li .menuactive {
    border-bottom: 2px solid <?php echo $tsx['config']['btn_background_color'];?>;
    color:<?php echo $tsx['config']['btn_background_color'];?>;
}
.ads-navbar-wrapper ul li a.active {
	border-color: <?php echo $tsx['config']['btn_background_color'];?>;
}
/* .ads_mini_wallet, .tsx_page_hdng_innr span {
	background-color: <?php echo $tsx['config']['btn_background_color'];?>;
	color: <?php echo $tsx['config']['btn_color'];?>;
} */
.btn-loading:after {
	background-color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.joinda_pub_privacy_menu li label input[type="radio"]:checked+span {
	background-color: <?php echo $tsx['config']['btn_background_color'];?>;color: <?php echo $tsx['config']['btn_color'];?>;
}
.order_by ul li.active a {background: <?php echo $tsx['config']['btn_background_color'];?> !important;color: <?php echo $tsx['config']['btn_color'];?> !important;}


<?php
if ($tsx['config']['chatSystem'] == 1 && $tsx['page'] != 'get_news_feed' && $tsx['page'] != 'welcome' && $tsx['loggedin'] == true && $tsx['page'] != 'messages') { ?>
body, .tsx_about_wrapper_parent{padding: 0 30rem;}
.joinda_main_float_head {right: 250px;}
@media (max-width:1140px){
	.tsx_about_wrapper_parent{padding-right: 0px;}
	.joinda_main_float_head {right: 0;}
}
<?php } ?>

<?php if($tsx['language_type'] == 'rtl' && $tsx['config']['chatSystem'] == 1 && $tsx['page'] != 'get_news_feed' && $tsx['page'] != 'welcome' && $tsx['page'] != 'messages' && $tsx['loggedin'] == true) { ?>
/* body, .navbar-default, .tsx_about_wrapper_parent{padding-left: 250px;padding-right: 0px;} */
.joinda_main_float_head {right: 0;left: 250px;}
@media (max-width:1140px){
	.tsx_about_wrapper_parent{padding-left: 0px;}
	.joinda_main_float_head {right: 0;left: 0;}
}
<?php } ?>

#welcomeheader .mdbtn:hover{background-color: <?php echo $tsx['config']['header_color'];?>;color: <?php echo $tsx['config']['header_background'];?>;border-color: <?php echo $tsx['config']['header_color'];?>;}

.post .panel.active_shadow {
    box-shadow: 0 0 0 1.5px <?php echo $tsx['config']['btn_background_color'];?> !important;
}

.ui-widget-header .ui-state-default, .tsx_adv_search_filter_side .ui-slider .ui-slider-range, .tsx_adv_search_filter_side .ui-slider .ui-slider-handle {
    background-color: <?php echo $tsx['config']['btn_background_color'];?>;
}
<?php
if (!empty($tsx['reactions_types'])) {
    foreach ($tsx['reactions_types'] as $key => $value) {
?>
.reaction-<?php echo $value['id'];?>::before {
    content: "<?php echo $value['name'];?>";
}
<?php } } ?>
/*.reaction-like::before {
    content: "<?php echo $tsx['lang']['like'];?>";
}
.reaction-love::before {
    content: "<?php echo $tsx['lang']['love'];?>";
}
.reaction-haha::before {
    content: "<?php echo $tsx['lang']['haha'];?>";
}
.reaction-joinda::before {
    content: "<?php echo $tsx['lang']['joinda'];?>";
}
.reaction-sad::before {
    content: "<?php echo $tsx['lang']['sad'];?>";
}
.reaction-angry::before {
    content: "<?php echo $tsx['lang']['angry'];?>";
}*/

.navbar-default .dropdown-menu.ani-acc-menu >li>a:hover {
    color: #262626;background-color: <?php echo $tsx['config']['btn_background_color'];?>;
}

#tsx_nw_msg_page .msg_under_hood .mobilerightpane .messages-search-users-form .tsx_msg_tabs li.active a, .text-sender-container .msg_usr_info_top_list .msg_usr_cht_opts_btns > span:hover, .text-sender-container .msg_usr_info_top_list .msg_usr_cht_usr_data a:hover, .tsx_chat_tabs li.active a {
    color: <?php echo $tsx['config']['btn_background_color'];?>;
}
.text-sender-container .outgoing .message-model .message {background-color: <?php echo $tsx['config']['btn_background_color'];?>;color: <?php echo $tsx['config']['btn_color'];?>;}
.text-sender-container .outgoing .message-model .message p, .text-sender-container .outgoing .message-model .message a {color: <?php echo $tsx['config']['btn_color'];?>;}

<?php if ($tsx['config']['google_map'] == 0 && $tsx['config']['yandex_map'] == 0) { ?>
/*#filterby-post li {
    width: 16.5%;
}*/
<?php }?>
#notification-popup {
     position: fixed;
     left: 20px;
     width: 300px;
     bottom: 20px;
     z-index: 10000;
}
#notification-popup .notifications-popup-list:empty {
      padding: 0;
}
#notification-popup .notifications-popup-list {
    position: relative;
    background:  <?php echo $tsx['config']['header_hover_border'];?> !important;
    border-radius: 10px;
    padding: 6px;
    width: 100%;
    margin-bottom: 10px;
    z-index: 10000;
    box-shadow: 0 2px 4px rgb(0 0 0 / 10%);
}
#notification-popup .notifications-popup-list, #notification-popup .notifications-popup-list a, #notification-popup .notifications-popup-list .main-color, #notification-popup .notifications-popup-list svg, #notification-popup .notifications-popup-list .notification-text, #notification-popup .notifications-popup-list .notification-time {
    color: <?php echo $tsx['config']['header_color'];?> !important;
}
#notification-popup .notifications-popup-list .notification-list {
    border-radius: 10px;
}
#notification-popup .notifications-popup-list .notification-list:hover {
    background: rgba(255, 255, 255, 0.1);
}
</style>
