<div class="recommended-articles col-md-4">
	<div class="article-thumbnail">
		<a href="<?php echo $tsx['blog-style']['url'] ?>">
			<img src="<?php echo $tsx['blog-style']['thumbnail'];?>" alt="Article Picture">
		</a>
	</div>
	<div class="article-title">
		<a href="<?php echo $tsx['blog-style']['url'] ?>">
			<h4><?php echo $tsx['blog-style']['title'] ?></h4>
		</a>
	</div>
	<div class="article-info">
		<span><?php echo date("d M Y",$tsx['blog-style']['posted']); ?></span>
	</div>
</div>