<div class="leftcol-sidebar"><?php echo tsx_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 profile-lists singlecol">
		<div class="page-margin mt-0">
					<div class="tsx_page_hdng pag_neg_padd pag_alone">
						<div class="tsx_page_hdng_innr big_size">
						<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24.351" height="27.056" viewBox="0 0 24.351 27.056">
						<defs>
							<linearGradient id="linear-gradient1131" x1="0.251" y1="0.741" x2="0.251" gradientUnits="objectBoundingBox">
								<stop offset="0" stop-color="#8c5afd"></stop>
								<stop offset="1" stop-color="#13e2da"></stop>
							</linearGradient>
						</defs>
						<path id="Union_52" data-name="Union 52" d="M-130,4992.165h-21.645a1.4,1.4,0,0,1-.96-.392,1.4,1.4,0,0,1-.392-.96v-17.587h24.351v17.587a1.4,1.4,0,0,1-.393.96A1.4,1.4,0,0,1-130,4992.165Zm1.353-21.645H-153v-4.058a1.4,1.4,0,0,1,.392-.96,1.4,1.4,0,0,1,.96-.393H-130a1.4,1.4,0,0,1,.96.393,1.4,1.4,0,0,1,.393.96Zm-18.939,6.764v5.411h5.411v-5.411Zm0,8.117v2.706h13.528V4985.4Zm8.117-6.764v2.706h5.411v-2.706Z" transform="translate(153 -4965.108)" fill="url(#linear-gradient1131)"></path>
						</svg><?php echo $tsx['lang']['blog']; ?>
						</div>
						<a class="btn btn-main btn-mat btn-mat-raised" href="<?php echo tsx_SeoLink('index.php?link1=create-blog');?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path></svg> <span><?php echo $tsx['lang']['create'] ?></span></a>
					</div>
				</div>
			<div class="tsx_my_pages my_tsx_pages_blog">
				<div class="row" id="blog-list">
					<?php  
						$pages          = tsx_GetMyBlogs($tsx["user"]['id']); 
						$no_blogs_found = $tsx['lang']['no_blogs_created'];
					?>

					<?php if ($pages && count($pages) > 0): ?>
						<?php foreach ($pages as $tsx['blog']): ?>
							<?php echo tsx_LoadPage('blog/includes/card-lg-list'); ?>
						<?php endforeach ?>
					<?php else: ?> 
						<?php echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11H4V8H20M20,15H13V13H20M20,19H13V17H20M11,19H4V13H11M20.33,4.67L18.67,3L17,4.67L15.33,3L13.67,4.67L12,3L10.33,4.67L8.67,3L7,4.67L5.33,3L3.67,4.67L2,3V19A2,2 0 0,0 4,21H20A2,2 0 0,0 22,19V3L20.33,4.67Z" /></svg>' . $no_blogs_found . '</div>'; ?>
					<?php endif; ?> 
				</div>
				
				<div class="loading-alert"></div>
            
				<div class="posts_load">
					<?php if (count($pages) >= 10): ?>
					<div class="load-more">
                        <button class="btn btn-default text-center pointer load-more-my-blogs">
                          <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> 
                          <?php echo $tsx['lang']['load_more'] ?>
                        </button>
					</div>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php echo tsx_LoadPage('blog/delete-blog');?>
<?php echo tsx_LoadPage('sidebar/content'); ?>
<script>
$(document).ready(function() {
  $(".delete-blog").on("click", function() {
    $("#delete-blog").attr('data-blog-id', $(this).attr("id")).modal();      
  });

  $(".load-more-my-blogs").click(function () {
      let offset = (($(".view-blog").length > 0) ? $(".view-blog:last").attr('id') : 0);

      $.ajax({
         url: tsx_Ajax_Requests_File(),
         type: 'GET',
         dataType: 'json',
         data: {f:"load-my-blogs",offset:offset},
         success:function(data){
            if (data['status'] == 200) {
              $("#blog-list").append(data['html']);
            }

            else{
              $(".posts_load").remove();
            }
         }
      });
   });
});
</script>