<?php if (tsx_FriendPrivacy($tsx['user_profile']['id'],$tsx['user_profile']['friend_privacy'])): ?>
<ul class="page-margin joinda_content negg_padd list-unstyled event-options-list" id="sidebar-following-list-container">
	<div class="tsx_page_hdng" style="margin-bottom: 5px;">
		<div class="tsx_page_hdng_innr">
			<a href="<?php echo tsx_SeoLink('index.php?link1=timeline&u=' . $tsx['user_profile']['username'] . '&type=following');?>" data-ajax="?link1=timeline&u=<?php echo $tsx['user_profile']['username']?>&type=following" class="pointer"><?php echo $tsx['lang']['following'];?></a>&nbsp;<div style="font-weight: normal">(<?php echo number_format($tsx['user_profile']['details']['following_count']);?>)</div>
		</div>
	</div>
	<li>
		<div class="sidebar-following-users-container list-sidebar-element"><?php
            foreach (tsx_GetFollowing($tsx['user_profile']['user_id'], 'profile', 9 , 0, array('in' => 'profile_sidebar', 'following_data' => $tsx['user_profile']['following_data'])) as $tsx['UsersList']) {
               $tsx['UsersList']['user_name'] = $tsx['UsersList']['name'];
               echo tsx_LoadPage('sidebar/profile-sidebar-user-list');
            } 
            ?></div>
	</li>
	<li><div class="clear"></div></li>
</ul>
<ul class="page-margin joinda_content negg_padd list-unstyled event-options-list" id="sidebar-followers-list-container">
	<div class="tsx_page_hdng" style="margin-bottom: 5px;">
		<div class="tsx_page_hdng_innr">
			<a href="<?php echo tsx_SeoLink('index.php?link1=timeline&u=' . $tsx['user_profile']['username'] . '&type=followers');?>" data-ajax="?link1=timeline&u=<?php echo $tsx['user_profile']['username']?>&type=followers"><?php echo $tsx['lang']['followers'];?></a>&nbsp;<div style="font-weight: normal">(<?php echo number_format($tsx['user_profile']['details']['followers_count']);?>)</div>
		</div>
	</div>
	<li>
		<div class="sidebar-followers-users-container list-sidebar-element"><?php 
            foreach (tsx_GetFollowers($tsx['user_profile']['user_id'],'profile',9 , 0, array('in' => 'profile_sidebar', 'followers_data' => $tsx['user_profile']['followers_data'])) as $tsx['UsersList']) {
               $tsx['UsersList']['user_name'] = $tsx['UsersList']['name'];
               echo tsx_LoadPage('sidebar/profile-sidebar-user-list');
             } 
             ?></div>
	</li>
	<li><div class="clear"></div></li>
</ul>
<?php endif; ?>


