<ul class="page-margin joinda_content negg_padd list-unstyled event-options-list" id="sidebar-pages-list-container">
	<div class="tsx_page_hdng" style="margin-bottom: 5px;">
		<div class="tsx_page_hdng_innr">
			<a href="<?php echo tsx_SeoLink('index.php?link1=timeline&u=' . $tsx['user_profile']['username'] . '&type=groups');?>" data-ajax="?link1=timeline&u=<?php echo $tsx['user_profile']['username']?>&type=groups"><?php echo $tsx['lang']['groups'];?></a>&nbsp;<div style="font-weight: normal">(<?php echo number_format($tsx['user_profile']['details']['groups_count']);?>)</div>
		</div>
	</div>
	<li>
		<div class="sidebar-groups-container list-sidebar-element"><?php 
			foreach (tsx_GetUsersGroups($tsx['user_profile']['user_id'], 9, array('in' => 'profile_sidebar', 'groups_data' => $tsx['user_profile']['groups_data'])) as $tsx['GroupList']) {
				$tsx['GroupList']['name'] = $tsx['GroupList']['name'];
				echo tsx_LoadPage('sidebar/sidebar-groups-list');
			}
			?></div>
	</li>
	<li><div class="clear"></div></li>
</ul>