<div class="col-xs-6 col-sm-4 nearby_user_wrapper text-center user-data" data-page-id="<?php echo $tsx['PageList']['page_id'];?>">
  <a href="<?php echo $tsx['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $tsx['PageList']['username']?>">
    <div class="avatar">
      <img src="<?php echo $tsx['PageList']['avatar'];?>" alt="<?php echo $tsx['PageList']['name']; ?> Profile Picture" />
    </div>
    <span class="user_wrapper_link"><?php echo $tsx['PageList']['name']; ?></span>
  </a>
  <div class="user-lastseen">
    <?php echo $tsx['lang']['category'];?>: <?php echo $tsx['PageList']['category']; ?>
  </div>
  <div class="user-follow-button">
    <?php echo tsx_GetLikeButton($tsx['PageList']['page_id']);?>
  </div>
</div>