<ul class="page-margin joinda_content negg_padd list-unstyled event-options-list" id="sidebar-pages-list-container">
	<div class="tsx_page_hdng" style="margin-bottom: 5px;">
		<div class="tsx_page_hdng_innr">
			<a href="<?php echo tsx_SeoLink('index.php?link1=timeline&u=' . $tsx['user_profile']['username'] . '&type=likes');?>" data-ajax="?link1=timeline&u=<?php echo $tsx['user_profile']['username']?>&type=likes"><?php echo $tsx['lang']['likes'];?></a>&nbsp;<div style="font-weight: normal">(<?php echo number_format($tsx['user_profile']['details']['likes_count']);?>)</div>
		</div>
	</div>
	<li>
		<div class="sidebar-likes-container list-sidebar-element"><?php 
			foreach (tsx_GetLikes($tsx['user_profile']['user_id'], 'profile', 9 , 0, array('in' => 'profile_sidebar', 'likes_data' => $tsx['user_profile']['likes_data'])) as $tsx['PageList']) {
				$tsx['PageList']['user_name'] = $tsx['PageList']['name'];
				echo tsx_LoadPage('sidebar/sidebar-page-list');
			}
			?></div>
	</li>
	<li><div class="clear"></div></li>
</ul>