<div id="posts" data-story-user="<?php echo $tsx['user_profile']['user_id'];?>">
            <div class="pinned-post-container">
                <?php
                    $pinedstory = tsx_GetPinnedPost($tsx['user_profile']['user_id']);
                    if (count($pinedstory) == 1) {
                        foreach ($pinedstory  as $tsx['story']) {
                          echo tsx_LoadPage('story/content');
                        }
                    }
                    ?>
        </div>
            <?php
                $stories = tsx_GetPosts(array('filter_by' => 'all','publisher_id' => $tsx['user_profile']['user_id'],'placement' => 'multi_image_post')); 
                if (count($stories) == 0 && count($pinedstory) == 0) {
                   echo tsx_LoadPage('story/profile-no-stories');
                } else {
                   foreach ($stories as $tsx['story']) {
                     echo tsx_LoadPage('story/content');
                   }
                }
                ?>
        </div>
        <?php if ($tsx['loggedin'] == true && count($stories) > 0) {  ?>
        <div class="load-more pointer" id="load-more-posts" onclick="tsx_GetMorePosts();">
            <span class="btn btn-default"><i class="fa fa-chevron-circle-down progress-icon" data-icon="chevron-circle-down"></i> &nbsp;<?php echo $tsx['lang']['load_more_posts']; ?><span>
        </div>
        <?php } ?>

