<div class="joinda_side_prods_prnt">
	<div class="joinda_side_prods">
		<a href="<?php echo $tsx['product']['url'];?>" data-ajax="?link1=post&id=<?php echo $tsx['product']['seo_id'];?>">
			<div class="avatar">
				<img src="<?php echo $tsx['product']['images'][0]['image_org'];?>" alt="<?php echo $tsx['product']['name']; ?> Profile Picture" />
			</div>
			<div class="produc_info">
				<span title="<?php echo $tsx['product']['name']; ?>"><?php echo $tsx['product']['name']; ?></span>
				<h4><?php echo (!empty($tsx['currencies'][$tsx['product']['currency']]['symbol'])) ? $tsx['currencies'][$tsx['product']['currency']]['symbol'] : $tsx['config']['classified_currency_s'];?><?php echo $tsx['product']['price']; ?></h4>
			</div>
		</a>
	</div>
</div>