<?php 
$data = $db->where('name','activate')->getOne(T_HTML_EMAILS);
$html = $data->value;
$replaces = array('USERNAME' => $tsx['user']['username'],
                 'SITE_URL' => $tsx['config']['site_url'],
                 'EMAIL' => $tsx['user']['email'],
                 'CODE' => $tsx['code'],
                 'SITE_NAME' => $tsx['config']['siteName']);
$html = tsx_ReplaceText($html,$replaces);
echo $html;
 ?>