<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
    <div class="row">
        <div class="col-md-7 singlecol">
            <div class="page-margin mt-0">
                <div class="wo_page_hdng pag_neg_padd pag_alone">
                    <div class="wo_page_hdng_innr big_size">
                    <svg width="648" height="600" viewBox="0 0 648 600" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M114.45 391.27L111.81 490.87C111.81 490.87 111.81 519.33 145.01 519.33H401.38" stroke="url(#paint0_linear_1118_136)" stroke-width="18" stroke-miterlimit="10"/>
                            <path d="M401.38 590.46C421.025 590.46 436.95 574.535 436.95 554.89C436.95 535.245 421.025 519.32 401.38 519.32C381.735 519.32 365.81 535.245 365.81 554.89C365.81 574.535 381.735 590.46 401.38 590.46Z" stroke="black" stroke-width="18" stroke-miterlimit="10"/>
                            <path d="M187.96 590.46C207.605 590.46 223.53 574.535 223.53 554.89C223.53 535.245 207.605 519.32 187.96 519.32C168.315 519.32 152.39 535.245 152.39 554.89C152.39 574.535 168.315 590.46 187.96 590.46Z" stroke="#805BE2" stroke-width="18" stroke-miterlimit="10"/>
                            <path d="M257.92 19.51C323.36 19.51 376.47 72.25 377.1 137.54H396.61C395.97 61.47 334.13 0 257.92 0C181.71 0 119.87 61.47 119.23 137.54H138.74C139.37 72.24 192.47 19.51 257.92 19.51Z" fill="url(#paint1_linear_1118_136)"/>
                            <path d="M396.64 138.72C396.64 166.6 388.39 192.54 374.23 214.28C388.09 228.3 407.84 237.13 429.84 237.13C471.75 237.13 505.72 205.28 505.72 165.99C505.72 155.87 503.43 146.25 499.36 137.53H396.61C396.61 137.93 396.64 138.32 396.64 138.72Z" fill="url(#paint2_linear_1118_136)"/>
                            <path d="M613.02 137.54H515.29C518.27 146.49 519.95 156.04 519.95 166C519.95 215.77 479.61 256.11 429.84 256.11C403.99 256.11 380.74 245.16 364.31 227.72C338.86 258.11 300.66 277.45 257.92 277.45C181.31 277.45 119.2 215.34 119.2 138.73C119.2 138.33 119.23 137.94 119.23 137.54H78.8901L107.35 474.27H534.19L648 164.53C648 149.62 632.34 137.54 613.02 137.54Z" fill="url(#paint3_linear_1118_136)"/>
                            <path d="M344.39 137.54H138.73C138.73 137.94 138.7 138.33 138.7 138.73C138.7 204.57 192.07 257.94 257.91 257.94C296.32 257.94 330.46 239.76 352.26 211.56C344.36 198.19 339.72 182.66 339.72 166C339.73 156.04 341.41 146.49 344.39 137.54Z" fill="url(#paint4_linear_1118_136)"/>
                            <path d="M361.77 197.25C371.54 179.96 377.14 160 377.14 138.72C377.14 138.32 377.11 137.93 377.11 137.53H360.32C356.25 146.25 353.96 155.86 353.96 165.99C353.96 177.23 356.8 187.82 361.77 197.25Z" fill="url(#paint5_linear_1118_136)"/>
                            <path d="M429.84 75.88C390.03 75.88 356.31 101.73 344.39 137.53H360.32C372.03 112.41 398.74 94.85 429.85 94.85C460.96 94.85 487.66 112.42 499.38 137.53H515.31C503.37 101.73 469.65 75.88 429.84 75.88Z" fill="url(#paint6_linear_1118_136)"/>
                            <path d="M93.11 151.76C93.11 151.76 88.37 66.39 3 90.11" stroke="#805BE2" stroke-width="20" stroke-miterlimit="10"/>
                            <defs>
                            <linearGradient id="paint0_linear_1118_136" x1="102.815" y1="459.675" x2="401.382" y2="459.675" gradientUnits="userSpaceOnUse">
                            <stop offset="0.3573" stop-color="#805BE2"/>
                            <stop offset="0.5191" stop-color="#6247AA"/>
                            <stop offset="0.846" stop-color="#29203D"/>
                            <stop offset="0.9916" stop-color="#121011"/>
                            </linearGradient>
                            <linearGradient id="paint1_linear_1118_136" x1="148.092" y1="68.7684" x2="425.477" y2="68.7684" gradientUnits="userSpaceOnUse">
                            <stop offset="0.1555" stop-color="#8200FF"/>
                            <stop offset="0.2495" stop-color="#8313FB"/>
                            <stop offset="0.4403" stop-color="#8444F0"/>
                            <stop offset="0.7077" stop-color="#8793E0"/>
                            <stop offset="0.9659" stop-color="#8AE5CE"/>
                            </linearGradient>
                            <linearGradient id="paint2_linear_1118_136" x1="440.471" y1="157.57" x2="435.92" y2="459.128" gradientUnits="userSpaceOnUse">
                            <stop offset="0.3573" stop-color="#805BE2"/>
                            <stop offset="0.5191" stop-color="#6247AA"/>
                            <stop offset="0.846" stop-color="#29203D"/>
                            <stop offset="0.9916" stop-color="#121011"/>
                            </linearGradient>
                            <linearGradient id="paint3_linear_1118_136" x1="364.188" y1="58.089" x2="358.493" y2="767.212" gradientUnits="userSpaceOnUse">
                            <stop offset="0.0689" stop-color="#805BE2"/>
                            <stop offset="0.3671" stop-color="#805BE2"/>
                            <stop offset="0.5086" stop-color="#6247AA"/>
                            <stop offset="0.7945" stop-color="#29203D"/>
                            <stop offset="0.9218" stop-color="#121011"/>
                            </linearGradient>
                            <linearGradient id="paint4_linear_1118_136" x1="245.372" y1="133.626" x2="246.235" y2="453.197" gradientUnits="userSpaceOnUse">
                            <stop offset="0.3573" stop-color="#805BE2"/>
                            <stop offset="0.5191" stop-color="#6247AA"/>
                            <stop offset="0.846" stop-color="#29203D"/>
                            <stop offset="0.9916" stop-color="#121011"/>
                            </linearGradient>
                            <linearGradient id="paint5_linear_1118_136" x1="364.414" y1="168.19" x2="360.601" y2="218.183" gradientUnits="userSpaceOnUse">
                            <stop stop-color="#805BE2"/>
                            <stop offset="0.2529" stop-color="#6247AA"/>
                            <stop offset="0.764" stop-color="#29203D"/>
                            <stop offset="0.9916" stop-color="#121011"/>
                            </linearGradient>
                            <linearGradient id="paint6_linear_1118_136" x1="344.387" y1="106.71" x2="515.29" y2="106.71" gradientUnits="userSpaceOnUse">
                            <stop offset="0.1555" stop-color="#8200FF"/>
                            <stop offset="0.2467" stop-color="#8312FB"/>
                            <stop offset="0.4296" stop-color="#8441F1"/>
                            <stop offset="0.6876" stop-color="#878CE1"/>
                            <stop offset="0.9659" stop-color="#8AE5CE"/>
                            </linearGradient>
                            </defs>
                        </svg>

                            <?php echo $wo['lang']['market']; ?>
                    </div>
                    <?php if ($wo['config']['can_use_market']) { ?>
                            <a class="btn btn-main btn-mat btn-mat-raised create-btn-bottom" href="#" data-toggle="modal" data-target="#create-product-modal" data-backdrop="static" data-keyboard="false"><svg height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg"><g id="_03_Login" data-name="03 Login"><path d="m256 512a25 25 0 0 1 -25-25v-462a25 25 0 0 1 50 0v462a25 25 0 0 1 -25 25z"/><path d="m487 281h-462a25 25 0 0 1 0-50h462a25 25 0 0 1 0 50z"/></g></svg></a>
                        <?php } ?>
                </div>
            </div>
            
            <div class="wo_my_pages">
                <div class="row my_products">
                    <?php
                    $products = Wo_GetProducts(array('user_id' => $wo['user']['user_id']));
                    if (count($products) > 0) {
                        foreach ($products as $wo['product']) {
                            echo Wo_LoadPage('products/product-style');
                        }
                    } else {
                        echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg> ' . $wo['lang']['no_available_products'] . '</h5>';
                    }
                    ?>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <!-- .row -->
</div>
<?php echo Wo_LoadPage('products/create'); ?>
<div class="modal fade" id="delete-product-post" role="dialog">
    <div class="modal-dialog modal-md wow_mat_mdl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
                <h4 class="modal-title"><?php echo $wo['lang']['delete_product_post']; ?></h4>
            </div>
            <div class="modal-body">
                <p><?php echo $wo['lang']['confirm_delete_product_post']; ?></p>
            </div>
            <div class="modal-footer">
                <div class="ball-pulse"><div></div><div></div><div></div></div>
                <button id="delete-my-product-post" type="button" class="btn main btn-mat"><?php echo $wo['lang']['delete']; ?></button>
            </div>
        </div>
    </div>
</div>
<div class="sidebar-conatnier">
    <div class="col-md-3 sidebar rightcol">
        <?php echo Wo_LoadPage('sidebar/content'); ?>
    </div>
</div>
<script type="text/javascript">
    function RemoveUserProduct(id,type = 'show') {
        if (type == 'hide') {
            $('#delete-product-post').find('#delete-my-product-post').attr('onclick', "RemoveUserProduct('"+id+"')");
            $('#delete-product-post').modal({
                show: true
            });
            return false;
        }
        $('#delete-product-post').modal('hide');
        $('#product_'+id).slideUp(300).remove();
        $.post(Wo_Ajax_Requests_File() + "?f=products&s=delete",{id: id},function () {});
    }
</script>