<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 singlecol">
			<div class="page-margin mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
					<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="25.924" height="28.804" viewBox="0 0 25.924 28.804">
							<defs>
								<linearGradient id="linear-gradient101" x1="0.5" x2="0.5" y2="1" gradientUnits="objectBoundingBox">
								<stop offset="0" stop-color="#e335f1"></stop>
								<stop offset="1" stop-color="#fc6519"></stop>
								</linearGradient>
							</defs>
							<path id="Path_5886" data-name="Path 5886" d="M3478.041,4914h15.843a1.475,1.475,0,0,1,1.152.575l3.889,5.185v21.6a1.427,1.427,0,0,1-1.44,1.44H3474.44a1.425,1.425,0,0,1-1.44-1.44v-21.6l3.888-5.185a1.476,1.476,0,0,1,1.152-.575Zm17.282,5.76-2.16-2.88h-14.4l-2.16,2.88Zm-13.682,5.762h-2.881v2.88a7.2,7.2,0,1,0,14.4,0v-2.88h-2.88v2.88a4.321,4.321,0,0,1-8.641,0Z" transform="translate(-3473 -4914)" fill="url(#linear-gradient101)"></path>
							</svg> <?php echo $wo['lang']['market']; ?>
					</div>
					<?php if ($wo['config']['can_use_market']) { ?>
						<a class="btn btn-main btn-mat btn-mat-raised create-btn-bottom" href="#" data-toggle="modal" data-target="#create-product-modal" data-backdrop="static" data-keyboard="false"><svg height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg"><g id="_03_Login" data-name="03 Login"><path d="m256 512a25 25 0 0 1 -25-25v-462a25 25 0 0 1 50 0v462a25 25 0 0 1 -25 25z"/><path d="m487 281h-462a25 25 0 0 1 0-50h462a25 25 0 0 1 0 50z"/></g></svg></a>
						<?php } ?>
				</div>
			</div>
			
			<div class="wo_my_pages">
				<div class="row my_products">
					<?php
						$products = Wo_GetProducts(array('user_id' => $wo['user']['user_id']));
						if (count($products) > 0) {
							foreach ($products as $wo['product']) {
								echo Wo_LoadPage('products/product-style');
							}
						} else {
							echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg> ' . $wo['lang']['no_available_products'] . '</h5>';
						}
					?>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!-- .row -->
</div>
<?php echo Wo_LoadPage('products/create'); ?>
<div class="modal fade" id="delete-product-post" role="dialog">
	<div class="modal-dialog modal-md wow_mat_mdl">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['delete_product_post']; ?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $wo['lang']['confirm_delete_product_post']; ?></p>
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button id="delete-my-product-post" type="button" class="btn main btn-mat"><?php echo $wo['lang']['delete']; ?></button>
			</div>
		</div>
	</div>
</div>
<div class="sidebar-conatnier">
    <div class="col-md-3 sidebar rightcol">
        <?php echo Wo_LoadPage('sidebar/content'); ?>
    </div>
</div>
<script type="text/javascript">
	function RemoveUserProduct(id,type = 'show') {
		if (type == 'hide') {
			$('#delete-product-post').find('#delete-my-product-post').attr('onclick', "RemoveUserProduct('"+id+"')");
			$('#delete-product-post').modal({
			    show: true
			});
			return false;
		}
		$('#delete-product-post').modal('hide');
		$('#product_'+id).slideUp(300).remove();
		$.post(Wo_Ajax_Requests_File() + "?f=products&s=delete",{id: id},function () {});
	}
</script>