<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bbcode/jquery.bbcode.js"></script>
<link rel="stylesheet" href="<?php echo $wo['config']['theme_url'];?>/javascript/bbcode/jquery.bbcode.css" media="all">
<style>
.f_category,.member_list,.adv-mbr-search,.g_search, .bg-main, .blocksubhead {background-color: <?php echo $wo['config']['header_background'];?>;color: #fff;}
.section-list {padding: 10px;}
.forum-tabs{width: 100%;overflow: hidden;margin-bottom: 20px;}
.forum-tabs li{width: 25%;background-color: #a84849;float: left;text-align: center;font-size: 14px;}
.forum-tabs li a{width: 100%;padding: 10px 0px;background-color: #a84849;color: #fff;vertical-align: middle;}
.forum-tabs li a:hover{background: rgba(245, 245, 245, 0.04);}
.navbar-collapse {padding-left: 0 !important;}
.flink {color: <?php echo $wo['config']['btn_background_color'];?> !important;}
blockquote {border-left: 2px solid <?php echo $wo['config']['btn_background_color'];?> !important;}
.bbcode-editor .bbcode-toolbar {color: #fff;background: <?php echo $wo['config']['header_background'];?> !important;padding: 8px;padding-bottom: 5px;}
</style>
<?php 
$forum_class = 'search-forums';
if (!empty($_GET['fid'])) {
	$forum_class = 'search-forum-threads';
}
if ($_GET['link1'] == 'showthread') {
	$forum_class = 'forum-messages-search';
}
 ?>
<div class="page-margin" id="forum-cont">
	<!-- <?php if ($wo['config']['user_ads'] == 1): ?>
			<div id="sidebar-sticky-forum">
				<?php 
				  $wo['sidebar-ad'] = Wo_GetAdsByType('forum');
				  if (!empty($wo['sidebar-ad'])) {
				  	echo Wo_LoadPage('ads/includes/forum-ad');
				  }
				?>
				<div class="clear"></div>
			</div>
	    <?php endif; ?>  -->
	
			<div class="page-margin mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
					<svg width="511" height="595" viewBox="0 0 511 595" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path d="M209.01 453.71V439.68H186.07V512.36C186.07 541.67 165.67 565.97 140.2 565.97H193.06C203 552.34 209.01 534.78 209.01 515.59V453.71Z" fill="#03131D"/>
						<path d="M488.06 439.68V453.71V512.36C488.06 541.67 467.66 565.97 442.19 565.97V594.03H442.84C480.49 594.03 511 558.91 511 515.58V439.67H488.06V439.68Z" fill="#03131D"/>
						<path d="M438.37 565.97H430.72V594.03H438.37V565.97Z" fill="#03131D"/>
						<path d="M442.19 565.97H438.37V594.03H442.19V565.97Z" fill="#03131D"/>
						<path d="M430.72 343.03H405.55V453.71H430.72V343.03Z" fill="#03131D"/>
						<path d="M430.72 453.71H405.55V458.39H430.72V453.71Z" fill="#999999"/>
						<path d="M405.55 565.97H400.14H193.06C180.56 583.12 161.82 594.03 140.84 594.03H419.25V565.97H405.55Z" fill="#03131D"/>
						<path d="M193.06 565.97H140.2H136.38V594.03H140.85C161.82 594.03 180.56 583.11 193.06 565.97Z" fill="#03131D"/>
						<path d="M430.73 565.97H419.26V594.03H430.73V565.97Z" fill="#03131D"/>
						<path d="M67.5698 0V104.58H90.9398V32.74H405.55V217.53H430.72V0H67.5698Z" fill="#03131D"/>
						<path d="M67.5698 510.63C67.5698 556.69 96.2698 594.03 131.68 594.03H136.38V565.97H134.32C110.36 565.97 90.9398 540.71 90.9398 509.54V225.9H67.5698V510.63Z" fill="#03131D"/>
						<path d="M511 449.71H188.88H186.07" stroke="#03131D" stroke-width="20" stroke-miterlimit="10"/>
						<path d="M293.47 221.72H489.25V342.85H331.21L293.47 384.87V221.72Z" stroke="url(#paint0_linear_1118_307)" stroke-width="18" stroke-miterlimit="10"/>
						<path d="M372.71 263.67H335.42V296.3H372.71V263.67Z" fill="#5E44A1"/>
						<path d="M451.95 263.67H414.66V296.3H451.95V263.67Z" fill="#03131D"/>
						<path d="M209.8 104.58H9V228.82H171.09L209.8 271.92V104.58Z" stroke="url(#paint1_linear_1118_307)" stroke-width="18" stroke-miterlimit="10"/>
						<path d="M128.525 181.081L166.775 181.081L166.775 147.611L128.525 147.611L128.525 181.081Z" fill="#03131D"/>
						<path d="M47.2432 181.081L85.4932 181.081L85.4932 147.611L47.2432 147.611L47.2432 181.081Z" fill="#03131D"/>
						<defs>
						<linearGradient id="paint0_linear_1118_307" x1="284.466" y1="310.535" x2="498.246" y2="310.535" gradientUnits="userSpaceOnUse">
						<stop stop-color="#805BE2"/>
						<stop offset="0.1382" stop-color="#6F4FC1"/>
						<stop offset="0.5582" stop-color="#3D2E63"/>
						<stop offset="0.8519" stop-color="#1E1828"/>
						<stop offset="0.9916" stop-color="#121011"/>
						</linearGradient>
						<linearGradient id="paint1_linear_1118_307" x1="0.000100469" y1="195.493" x2="218.8" y2="195.493" gradientUnits="userSpaceOnUse">
						<stop stop-color="#805BE2"/>
						<stop offset="0.1382" stop-color="#6F4FC1"/>
						<stop offset="0.5582" stop-color="#3D2E63"/>
						<stop offset="0.8519" stop-color="#1E1828"/>
						<stop offset="0.9916" stop-color="#121011"/>
						</linearGradient>
						</defs>
					</svg>

							<?php echo $wo['lang']['forum']; ?>
					</div>
				</div>
			</div>
	<!-- <div class="page-margin wow_content">
		<div class="wo_page_hdng pag_neg_padd pag_alone">
			<div class="wo_page_hdng_menu">
				<ul class="list-unstyled">
					<li class="<?php if ($wo['active'] == 'forums') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=forum');?>" data-ajax="?link1=forum"><?php echo $wo['lang']['browse_forum']; ?></a></li>
					<li class="<?php if ($wo['active'] == 'members') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=forum-members');?>" data-ajax="?link1=forum-members"><?php echo $wo['lang']['members']; ?></a></li>
					<li class="<?php if ($wo['active'] == 'search') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=forum-search');?>" data-ajax="?link1=forum-search"><?php echo $wo['lang']['search']; ?></a></li>
					<li class="<?php if ($_GET['link1'] == 'mythreads') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=mythreads');?>" data-ajax="?link1=mythreads"><?php echo $wo['lang']['my_threads']; ?></a></li>
					<li class="<?php if ($_GET['link1'] == 'mymessages') echo 'active'; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=mymessages');?>" data-ajax="?link1=mymessages"><?php echo $wo['lang']['my_messages']; ?></a></li>
				</ul>
				<?php if (empty($wo['forums'])) {
					$wo['forums']        = Wo_GetForums();
				} ?>
				<?php if ($wo['forums'] && count($wo['forums']) > 0): ?>
					<div class="btn-group dropdown wow_forum_jump_btn">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><?php echo $wo['lang']['jump_to']; ?>&nbsp;&nbsp;<span class="caret"></span></button>
						<ul class="dropdown-menu dropdown-menu-right" role="menu">
							<?php foreach ($wo['forums'] as $jump): ?>
								<li>
									<a href="<?php echo Wo_SeoLink('index.php?link1=forums&fid='.$jump['id']);?>" class=""><?php echo $jump['name_lang']; ?></a>
								</li>
							<?php endforeach ?>
						</ul>
					</div>
				<?php endif ?>
			</div>
		</div>
	</div> -->


	<!-- Tab panes -->
	<div class="tab-content" id="tab-content">