<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<style>
    .container {
        width: 800px;
    }

    @media (max-width: 1870px) {
        .container {
            width: 800px !important;
        }
    }

    @media (max-width: 1500px) {
        .container {
            width: 100% !important;
        }
    }
</style>
<div class="page-margin">
    <div class="row">
        <div class="middlecol">
            <?php if ($wo['config']['user_status'] == 1) { ?>
                <div class="user-status-home wow_home_stories">
                    <ul class="status-list">
                        <?php if ($wo['config']['can_use_story']) { ?>
                            <li class="create_new" style="padding-left: 0;">
                                <a href="<?php echo Wo_SeoLink('index.php?link1=create-status'); ?>"
                                    data-ajax="?link1=create-status">
                                    <img src="<?php echo $wo['user']['avatar']; ?>" alt="<?php echo $wo['user']['name']; ?>">
                                </a>
                                <div class="story-owner story-realOwner">
                                    <svg xmlns="http://www.w3.org/2000/svg" style="cursor: pointer;"
                                        onclick="window.location.replace('<?php echo Wo_SeoLink('index.php?link1=create-status'); ?>')"
                                        title="<?php echo $wo['lang']['create_story'] ?>" width="24" height="24"
                                        viewBox="0 0 24 24">
                                        <path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" />
                                    </svg>
                                    <p style="font-weight: 600;color: #121214;"><?php echo $wo['lang']['createstory']; ?></p>
                                </div>
                            </li>
                        <?php } ?>
                        <?php
                        if ($wo['config']['user_status'] == 1) {
                            $get_user_status = Wo_GetFriendsStatus(array('limit' => 5));
                            if (!empty($get_user_status)) {
                                ?>
                                <?php
                                foreach ($get_user_status as $key => $wo['user_status']) {
                                    echo Wo_LoadPage('home/user-status');
                                }
                            }
                            ?>
                        <?php } ?>
                        <?php if (!empty($get_user_status) && count($get_user_status) > 4) { ?>
                            <a href="<?php echo Wo_SeoLink('index.php?link1=more-status'); ?>" class="status-loadMore">
                                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
                                    xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 240.823 240.823"
                                    style="enable-background:new 0 0 240.823 240.823;" xml:space="preserve">
                                    <g>
                                        <path id="Chevron_Right_1_" d="M183.189,111.816L74.892,3.555c-4.752-4.74-12.451-4.74-17.215,0c-4.752,4.74-4.752,12.439,0,17.179
        l99.707,99.671l-99.695,99.671c-4.752,4.74-4.752,12.439,0,17.191c4.752,4.74,12.463,4.74,17.215,0l108.297-108.261
        C187.881,124.315,187.881,116.495,183.189,111.816z" />
                                        <g>
                                        </g>
                                        <g>
                                        </g>
                                        <g>
                                        </g>
                                        <g>
                                        </g>
                                        <g>
                                        </g>
                                        <g>
                                        </g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                    <g>
                                    </g>
                                </svg>

                            </a>
                        <?php } ?>
                    </ul>
                </div>
                <?php
            }
            if (Wo_IsThereAnnouncement() === true) {
                $announcement = Wo_GetHomeAnnouncements();
                ?>
                <div class="home-announcement">
                    <div class="alert alert-success" style="background-color: white;">
                        <span class="close announcements-option" data-toggle="tooltip"
                            onclick="Wo_ViewAnnouncement(<?php echo $announcement['id']; ?>);"
                            title="<?php echo $wo['lang']['hide']; ?>">
                            <i class="fa fa-remove"></i>
                        </span>
                        <?php echo $announcement['text']; ?>
                    </div>
                </div>
                <!-- .home-announcement -->
                <?php
            }
            if ($wo['loggedin'] == true) {
                echo Wo_LoadPage('story/publisher-box');
            }
            ?>

            <?php if (Wo_IsMobile() == true) { ?>
                <?php if ($wo['config']['order_posts_by'] == 0) { ?>
                    <div class="wow_content order-by">
                        <div class="dropdown">
                            <?php echo $wo['lang']['store_posts_by'] ?>: <a class="btn-default dropdown-toggle" type="button"
                                data-toggle="dropdown">
                                <span
                                    class="order-text"><?php echo ($wo['user']['order_posts_by'] == 0) ? $wo['lang']['all'] : $wo['lang']['people_i_follow']; ?></span>
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu post_order_feed">
                                <li>
                                    <a href="javascript:void(0);" onclick="Wo_StorePosts(0);">
                                        <div>
                                            <b><?php echo $wo['lang']['all'] ?></b>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);" onclick="Wo_StorePosts(1);">
                                        <div>
                                            <b><?php echo $wo['lang']['people_i_follow'] ?></b>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                <?php } ?>
            <?php } ?>

            <?php if ($wo['config']['afternoon_system'] == 1) { ?>
                <div class="alert alert-dismissible greetalert hidden" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"
                        onclick="setCookie('day_status', '1', 3);"><span aria-hidden="true">&times;</span></button>
                    <div id="daynightmsg"></div>
                </div>
            <?php } ?>

            <?php if ($wo['page'] == 'home' && in_array($wo['config']['website_mode'], array('facebook', 'linkedin'))) { ?>
                <div id="scroll_filter_click"></div>
                <ul class="list-group filterby" id="filterby-post">
                    <li class="list-group-item hidden" contenteditable="false">Filter by</li>
                    <li class="list-group-item avtive filter-by-li filter_negative_clr" onclick="Wo_FilterPostBy('all');"
                        style="color: #F50E16;" dir="auto">

                        <img style="width:35px" src="<?php echo $wo['config']['theme_url']; ?>/img/home.png">


                    </li>
                    <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('text');" dir="auto"
                        style="color: #FFAB1E;">
                        <!-- <svg width="364" height="431" viewBox="0 0 364 431" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M363.2 58.11H295.4V431H363.2V58.11Z" fill="#182530" />
                            <path d="M363.2 0H295.4V43.58H363.2V0Z" fill="#182530" />
                            <path
                                d="M273.13 0H7.75C3.47 0 0 3.47 0 7.75V387.21C0 411.39 19.61 431 43.79 431H273.13C277.41 431 280.88 427.53 280.88 423.25V7.75C280.88 3.47 277.41 0 273.13 0ZM155.98 275.48C155.98 282.64 153.31 288.44 150.02 288.44H35.34C32.05 288.44 29.38 282.64 29.38 275.48V260.91C29.38 253.75 32.05 247.95 35.34 247.95H150.02C153.31 247.95 155.98 253.75 155.98 260.91V275.48ZM209.34 186.39C209.34 193.55 205.55 199.35 200.87 199.35H37.85C33.17 199.35 29.38 193.55 29.38 186.39V171.82C29.38 164.66 33.17 158.86 37.85 158.86H200.87C205.55 158.86 209.34 164.66 209.34 171.82V186.39ZM250.39 97.31C250.39 104.47 245.73 110.27 239.99 110.27H39.79C34.04 110.27 29.39 104.47 29.39 97.31V82.74C29.39 75.58 34.05 69.78 39.79 69.78H239.99C245.74 69.78 250.39 75.58 250.39 82.74V97.31Z"
                                fill="#182530" />
                        </svg> -->
                        <img style="width:35px" src="<?php echo $wo['config']['theme_url']; ?>/img/notes.png">


                    </li>
                    <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('photos');" dir="auto"
                        style="color: #00C500;">
                        <!-- <svg width="461" height="398" viewBox="0 0 461 398" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M294.94 353.22C294.94 353.22 306.7 345.77 302.67 332.97C301.41 328.96 248.47 240.44 248.47 240.44L289.53 162.39C295.8 150.48 313.68 150.48 319.94 162.39L377.26 271.34V1.91003H35.32C15.81 1.91003 0 17.72 0 37.23V362.67C0 382.18 15.81 397.99 35.32 397.99H377.27V353.21C350.4 353.22 297.85 353.22 294.94 353.22ZM84.19 36.36C100.36 36.36 113.47 49.47 113.47 65.64C113.47 81.81 100.36 94.92 84.19 94.92C68.02 94.92 54.91 81.81 54.91 65.64C54.92 49.46 68.02 36.36 84.19 36.36ZM267.52 353.22H53.09C40.03 353.22 31.16 342.88 36.15 333.48L148.59 121.44C153.57 112.04 167.04 112.04 172.03 121.44L284.47 333.48C289.45 342.89 280.58 353.22 267.52 353.22Z"
                                fill="url(#paint0_linear_1118_210)" />
                            <path d="M460.19 53.9H389.71V398H460.19V53.9Z" fill="url(#paint1_linear_1118_210)" />
                            <path d="M460.19 0H389.71V41.46H460.19V0Z" fill="url(#paint2_linear_1118_210)" />
                            <defs>
                                <linearGradient id="paint0_linear_1118_210" x1="0" y1="199.957" x2="377.271" y2="199.957"
                                    gradientUnits="userSpaceOnUse">
                                    <stop stop-color="#161616" />
                                    <stop offset="0.2196" stop-color="#4A4A4A" />
                                    <stop offset="0.4662" stop-color="#7D7D7D" />
                                    <stop offset="0.6813" stop-color="#A3A3A3" />
                                    <stop offset="0.8542" stop-color="#BABABA" />
                                    <stop offset="0.9631" stop-color="#C2C2C2" />
                                </linearGradient>
                                <linearGradient id="paint1_linear_1118_210" x1="389.708" y1="225.948" x2="460.187"
                                    y2="225.948" gradientUnits="userSpaceOnUse">
                                    <stop stop-color="#C2C2C2" />
                                    <stop offset="0.067" stop-color="#C2C2C2" />
                                    <stop offset="0.1937" stop-color="#C2C2C2" />
                                    <stop offset="0.9631" stop-color="#C2C2C2" />
                                </linearGradient>
                                <linearGradient id="paint2_linear_1118_210" x1="389.708" y1="20.7292" x2="460.187"
                                    y2="20.7292" gradientUnits="userSpaceOnUse">
                                    <stop stop-color="#C2C2C2" />
                                    <stop offset="0.067" stop-color="#C2C2C2" />
                                    <stop offset="0.1937" stop-color="#C2C2C2" />
                                    <stop offset="0.9631" stop-color="#C2C2C2" />
                                </linearGradient>
                            </defs>
                        </svg> -->
                        <img style="width:35px" src="<?php echo $wo['config']['theme_url']; ?>/img/pics.png">

                    </li>
                    <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('video');" dir="auto"
                        style="color: #FF268D;">
                        <svg width="533" height="429" viewBox="0 0 533 429" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M411.59 299.25V429H78.0901V0H411.59V125.86L532.86 40.86V385.56L411.59 299.25Z"
                                fill="url(#paint0_linear_1118_216)" />
                            <path
                                d="M64.31 429H7.17001C3.21001 429 0 425.79 0 421.83V7.17001C0 3.21001 3.21001 0 7.17001 0H64.31V429Z"
                                fill="#805BE2" />
                            <defs>
                                <linearGradient id="paint0_linear_1118_216" x1="97.884" y1="278.691" x2="529.418"
                                    y2="100.103" gradientUnits="userSpaceOnUse">
                                    <stop offset="0.1555" stop-color="#8200FF" />
                                    <stop offset="0.231" stop-color="#820BFD" />
                                    <stop offset="0.3623" stop-color="#8327F7" />
                                    <stop offset="0.5336" stop-color="#8555ED" />
                                    <stop offset="0.7384" stop-color="#8795DF" />
                                    <stop offset="0.9659" stop-color="#8AE5CE" />
                                </linearGradient>
                            </defs>
                        </svg>

                    </li>
                    <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('music');" dir="auto"
                        style="color: #B54EAF;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22.895" height="22.895" viewBox="0 0 22.895 22.895">
                            <path id="Path_9205" data-name="Path 9205"
                                d="M3483.882,13635.975v8.473a3.559,3.559,0,0,1-.664,2.06,3.657,3.657,0,0,1-1.729,1.261,3.427,3.427,0,0,1-2.14-.115,3.545,3.545,0,0,1-1.706-1.259,3.351,3.351,0,0,1,.069-4.007,3.665,3.665,0,0,1,1.751-1.259,3.4,3.4,0,0,1,2.129.114V13633a11.448,11.448,0,1,1-2.289,0v2.4a8.7,8.7,0,0,0-5.907,3.206,9.348,9.348,0,0,0-2.083,6.41,9.235,9.235,0,0,0,9.135,8.586,8.993,8.993,0,0,0,5.827-2.062,9.2,9.2,0,0,0,2.232-11.446A9.4,9.4,0,0,0,3483.882,13635.975Z"
                                transform="translate(-3469 -13633)" fill="currentColor" fill="#b54eaf" />
                        </svg>
                    </li>
                    <?php if ($wo['config']['fileSharing'] == 1) { ?>
                        <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('files');" dir="auto"
                            style="color: #74D5F5;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22.656" height="21.577" viewBox="0 0 22.656 21.577">
                                <path id="Path_9947" data-name="Path 9947"
                                    d="M3533.315,3136v21.577H3529V3136Zm12.946,0a2.154,2.154,0,0,1,2.158,2.147v17.283a2.148,2.148,0,0,1-2.158,2.147h-10.789V3136Zm-4.315,6.473-4.315,4.316h3.237v4.315h2.157v-4.315h3.237Zm9.709,4.316v4.315H3549.5v-4.315Zm0-6.473v4.315H3549.5v-4.315Z"
                                    transform="translate(-3529 -3136)" fill="currentColor" fill="#74d5f5" />
                            </svg>
                        </li>
                    <?php } ?>
                    <?php if ($wo['config']['google_map'] == 1 || $wo['config']['yandex_map'] == 1) { ?>
                        <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('maps');" dir="auto"
                            style="color: #F50E16;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18.854" height="22.761" viewBox="0 0 18.854 22.761">
                                <path id="Path_9940" data-name="Path 9940"
                                    d="M3655.748,5866.465a7.337,7.337,0,0,0,1.414-7.939,7.43,7.43,0,0,0-2.7-3.227,7.356,7.356,0,0,0-8.066,0,7.433,7.433,0,0,0-2.7,3.227,7.339,7.339,0,0,0,1.414,7.939,6.277,6.277,0,0,1,10.642,0Zm-5.321,8.3-6.662-6.672a9.435,9.435,0,1,1,13.324,0Zm0-12.287a3.146,3.146,0,1,1,2.221-.921A3.139,3.139,0,0,1,3650.427,5862.475Z"
                                    transform="translate(-3641 -5852)" fill="currentColor" fill="#f50e16" />
                            </svg>
                        </li>
                    <?php } ?>
                </ul>
            <?php } ?>
            <div class="btn btn-main btn-active posts-count" onclick="Wo_GetNewPosts();"></div>
            <div class="posts_load">
                <div id="posts-laoded">
                    <div class="wo_loading_post">
                        <div class="lightui1-shimmer">
                            <div class="_2iwr"></div>
                            <div class="_2iws"></div>
                            <div class="_2iwt"></div>
                            <div class="_2iwu"></div>
                            <div class="_2iwv"></div>
                            <div class="_2iww"></div>
                            <div class="_2iwx"></div>
                            <div class="_2iwy"></div>
                            <div class="_2iwz"></div>
                            <div class="_2iw-"></div>
                            <div class="_2iw_"></div>
                            <div class="_2ix0"></div>
                        </div>
                    </div>
                    <div class="wo_loading_post">
                        <div class="lightui1-shimmer">
                            <div class="_2iwr"></div>
                            <div class="_2iws"></div>
                            <div class="_2iwt"></div>
                            <div class="_2iwu"></div>
                            <div class="_2iwv"></div>
                            <div class="_2iww"></div>
                            <div class="_2iwx"></div>
                            <div class="_2iwy"></div>
                            <div class="_2iwz"></div>
                            <div class="_2iw-"></div>
                            <div class="_2iw_"></div>
                            <div class="_2ix0"></div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #posts -->
        </div>
    </div>
</div>
<!-- .col-md-8 -->
<?php echo Wo_LoadPage('sidebar/content'); ?>
<!-- .page-margin -->

<?php
if ($wo['user']['social_login'] == 1) {
    echo Wo_LoadPage('modals/create-password');
}
?>

<script type="text/javascript">

    $(function () {
        loadposts();
    });


    // $(document).on('click', '.story-image-wrapper', function(event) {
    //   event.preventDefault();
    //   $value = $(this).parents(".story-container").attr('data-status-id');
    //   $.post(Wo_Ajax_Requests_File() + '?f=story_view', {id: $value}, function(data, textStatus, xhr) {

    //   });
    // });



    /* Standard syntax */
    document.addEventListener("fullscreenchange", function () {
        $('video').toggleClass('active-player');
    });

    /* Firefox */
    document.addEventListener("mozfullscreenchange", function () {
        $('video').toggleClass('active-player');
    });

    /* Chrome, Safari and Opera */
    document.addEventListener("webkitfullscreenchange", function () {
        $('video').toggleClass('active-player');
    });

    /* IE / Edge */
    document.addEventListener("msfullscreenchange", function () {
        $('video').toggleClass('active-player');
    });


    function loadposts() {
        $("#posts-laoded").load(Wo_Ajax_Requests_File() + '?f=load_posts', function enter() {
            Wo_FinishBar();
            window.fbAsyncInit = function () {
                FB.init({
                    appId: '374255706379985',
                    xfbml: true,
                    version: 'v3.2'
                });
            };
            $(".post-description p, .product-description").each(function (index, el) {
                ReadMoreText(this);
            });
            $(".post-commet-textarea .textarea").triggeredAutocomplete({
                hidden: '#hidden_inputbox_comment',
                source: Wo_Ajax_Requests_File() + "?f=mention",
                trigger: "@"
            });
            $(".comment-reply textarea").triggeredAutocomplete({
                hidden: '#hidden_inputbox_comment_reply',
                source: Wo_Ajax_Requests_File() + "?f=mention",
                trigger: "@"
            });
            $('#load-more-posts').show();

        });
    }
    <?php if ($wo['user']['social_login'] == 1) { ?>
        $(window).on("load", function (e) {
            $('#create-password').modal('show');
        });
        $(function () {
            var create_password_container = $('#create-password');
            $('form.create-password').ajaxForm({
                url: Wo_Ajax_Requests_File() + '?f=update_new_logged_user_details',
                beforeSend: function () {
                    Wo_progressIconLoader($('form.create-password').find('button'));
                },
                success: function (data) {
                    if (data.status == 200) {
                        create_password_container.find('.error-container').html("<div class='alert alert-success'>" + data.message + "</div>");
                        $('#update-username').attr('href', data.url);
                        setTimeout(function () {
                            $('#create-password').modal('hide');
                        }, 1500);
                    } else {
                        var errors = data.errors.join("<br>");
                        create_password_container.find('.error-container').html("<div class='alert alert-danger'>" + errors + "</div>");
                    }
                    Wo_progressIconLoader($('form.create-password').find('button'));
                }
            });
        });
    <?php } ?>

    <?php if (Wo_IsMobile() == true) { ?>
        function Wo_StorePosts(type) {
            if (type > 1) {
                return false;
            }
            if (type == 0) {
                $('.order-text').text('<?php echo $wo['lang']['all'] ?>');
            } else {
                $('.order-text').text('<?php echo $wo['lang']['people_i_follow'] ?>');
            }
            $('#posts-laoded').html('<div class="wo_loading_post"><div class="wo_loading_post_child"></div></div>');
            $.get(Wo_Ajax_Requests_File() + '?f=update_order_by', { type: type }, function (data) {
                if (data.status == 200) {
                    loadposts();
                }
            });
        }
    <?php } ?>

    function Wo_ViewAnnouncement(id) {
        var announcement_container = $('.home-announcement');
        $.get(Wo_Ajax_Requests_File() + '?f=update_announcement_views', { id: id }, function (data) {
            if (data.status == 200) {
                announcement_container.slideUp(200, function () {
                    $(this).remove();
                });
            }
        });
    }

    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 60 * 60 * 1000));
        var expires = "expires=" + d;
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    function getCookieValue(a) {
        var b = document.cookie.match('(^|;)\\s*' + a + '\\s*=\\s*([^;]+)');
        return b ? b.pop() : '';
    }

    $(function () {
        var is_day_enabled = getCookieValue('day_status');
        var myDate = new Date();
        var hrs = myDate.getHours();
        var greet;
        var color;
        var quote;
        if (hrs < 12) {
            greet = '<?php echo $wo['lang']['good_morning'] ?>, <?php echo $wo['user']['name'] ?> <img src="<?php echo $wo['config']['theme_url']; ?>/img/park.png"/>';
            color = '#7FC583';
            quote = '<?php echo $wo['lang']['good_morning_quote'] ?>';
        } else if (hrs >= 12 && hrs <= 18) {
            greet = '<?php echo $wo['lang']['good_afternoon'] ?>, <?php echo $wo['user']['name'] ?> <img src="<?php echo $wo['config']['theme_url']; ?>/img/desert.png"/>';
            color = '#ffc107';
            quote = '<?php echo $wo['lang']['good_afternoon_quote'] ?>';
        } else if (hrs >= 18 && hrs <= 24) {
            greet = '<?php echo $wo['lang']['good_evening'] ?>, <?php echo $wo['user']['name'] ?> <img src="<?php echo $wo['config']['theme_url']; ?>/img/sea.png"/>';
            color = '#FF4F70';
            quote = '<?php echo $wo['lang']['good_evening_quote'] ?>';
        }
        if (is_day_enabled != 1) {
            setTimeout(function () {
                $('.greetalert').css('border-color', color);
                $('#daynightmsg').html('<div class="small-texts">' + greet + '</div><p>' + quote + '</p>');
                $('.greetalert').removeClass('hidden');
            }, 100);
        }
    });
</script>