<li class="<?php echo($wo['user_status']['have_not_seen'] ? "not_seen_story" : ""); ?>">
	<a class="see_all_stories" data_story_user_id="<?php echo $wo['user_status']['user_data']['user_id']?>" data_story_type="friends">
		<img src="<?php echo $wo['user_status']['thumb']['filename'];?>" >
	</a>
	<div class="story-owner story-owner-otherusers">
		<img src="<?php echo $wo['user_status']['user_data']['avatar']?>" alt="<?php echo $wo['user_status']['user_data']['name']?> Profile Picture">
		<!-- <p><?php echo $wo['user_status']['user_data']['name']?></p> -->
	</div>
</li>