<?php echo tsx_LoadPage('forum/headers/header'); ?>
<div role="tabpanel" class="tab-pane active" id="showthread">
	<div class="w-100">
		<?php if (count($tsx['threads']) > 0): ?>
			  <table class="table threads-table table-striped">
			    <thead class="joinda_forum_dis_thead">
			      <tr>
			        <th>
				        <?php echo $tsx['lang']['topic']; ?>
			        </th>
			        <th><?php echo $tsx['lang']['views']; ?></th>
			        <th><?php echo $tsx['lang']['last_post']; ?></th>
			        <th width="20%"><?php echo $tsx['lang']['action']; ?></th>
			      </tr>
			    </thead>
			    <tbody>
			    <?php foreach ($tsx['threads'] as $tsx['thread']): ?>
			    	<?php echo tsx_LoadPage("forum/includes/mythread-list"); ?>
			    <?php endforeach; ?>

			    </tbody>
			  </table>
	    <?php else: ?>
			<?php echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M18,22A2,2 0 0,0 20,20V4C20,2.89 19.1,2 18,2H12V9L9.5,7.5L7,9V2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18Z" /></svg>' . $tsx['lang']['no_threads_found'] .  '</div>'; ?>
		<?php endif; ?>	
	</div>
    <div class="posts_load">
        <?php if (count($tsx['threads']) > 5): ?>
        <div class="load-more">
            <button class="btn btn-default text-center pointer forum-posts-load">
            <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $tsx['lang']['load_more_posts'] ?></button>
        </div>
        <?php endif ?>
    </div>
</div>
<div class="clear"></div>
<?php echo tsx_LoadPage('forum/includes/delete-thread'); ?>
<?php echo tsx_LoadPage('forum/headers/footer'); ?>
<?php if (count($tsx['threads']) >= 0): ?>
	<script>
		$(".forum-posts-load").click(function () {
			  
		      $.ajax({
		         url: tsx_Ajax_Requests_File(),
		         type: 'GET',
		         dataType: 'json',
		         data: {
		         	f:"load-my-forum-posts",

		         	offset:($(".mythread-list").length > 0) ? $(".mythread-list:last").attr('data-thread-ident') : 0,

		         },
		         success:function(data){
		         	
		            if (data['status'] == 200) {

		                $(".threads-table tbody").append(data['html'])
		             }else{

		               $(".posts_load").remove()
		               
		             }

		         }
		      });
		   	});
	</script>
<?php endif ?>


