<?php echo tsx_LoadPage('forum/headers/header'); ?>
<div class="row" id="threadreply">
	<label class="col-md-2"></label>
	<div class="col-md-8">
		<div class="joinda_content mt-0">
			<div class="tsx_page_hdng pag_neg_padd pag_alone">
				<div class="tsx_page_hdng_innr">
					<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M10,9V5L3,12L10,19V14.9C15,14.9 18.5,16.5 21,20C20,15 17,10 10,9Z"></path></svg></span> <?php echo $tsx['lang']['reply'];?> > <?php echo $tsx['reply']['post_subject']; ?>
				</div>
			</div>
		</div>

		<div class="page-margin joinda_content joinda_sett_content">
			<form action="#" class="form" id="quotereply" method="post">
				<div id="quotereply-alert"></div>
				<div class="joinda_form_fields">
					<label for="subject"><?php echo $tsx['lang']['subject']; ?></label>
					<input type="text" name="subject" id="subject" value="<?php echo($tsx['reply']['post_subject']); ?>">
				</div>
				<div class="joinda_form_fields">
					<label for="newquotereply"><?php echo $tsx['lang']['your_reply']; ?></label>
					<textarea id="newquotereply" name="content">[quote][b]<?php echo $tsx['reply']['user_data']["username"]; ?> <?php echo $tsx['lang']['wrote']; ?>:[/b][nl]<?php echo $tsx['reply']['post_text']; ?>[/quote]</textarea>
				</div>
				<div class="text-center">
					<button class="btn btn-main btn-mat btn-mat-raised add_joinda_loader" id="forum-search-btn" type="submit"><?php echo $tsx['lang']['reply']; ?></button>
				</div>
			</form>
		</div>
		<div class="clear"></div>
	</div>
	<label class="col-md-2"></label>
</div>


<?php if (isset($tsx['bbcodeditor']) && $tsx['bbcodeditor']): ?>
<script>
	jQuery(document).ready(function($) {


		$('#quotereply').ajaxForm({

	      url: tsx_Ajax_Requests_File()  +  '?f=threadreply&tid=<?php echo $tsx['reply']['thread_id']; ?>&fid=<?php echo $tsx['reply']['forum_id']; ?>&q=1&hash=' + $('.main_session').val(),
	      beforeSend: function() {
	        tsx_progressIconLoader($('#quotereply').find('button'));
	      },
	      success: function(data) {
	        scrollToTop();
	        if (data['status'] == 200) {
	        	if (node_socket_flow == "1") {
			        socket.emit("user_notification", { to_id: data.user_id, user_id: _getCookie("user_id"), type: "added" });
			    }
	         	$("#quotereply-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	         	window.location = data.url;
	          
	        } else {
	        	
	         	$("#quotereply-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	        } 
	        tsx_progressIconLoader($('#quotereply').find('button'));
	      }
		});
		$('#newquotereply').bbcode();
		$("#newquotereply").autogrow({vertical: true, horizontal: false});

	});

</script>
	
<?php endif ?>

<?php echo tsx_LoadPage('forum/headers/footer'); ?>