<div class="joinda_form_fields">
	<label><?php echo $tsx['field']['name']?></label>
<?php 
      if ($tsx['field']['select_type'] == 'yes') {
      	$options = @explode(',', $tsx['field']['type']); ?>
      	<select name="<?php echo $tsx['field']['fid'];?>">
      	<?php
      	foreach ($options as $key => $value) {
      		?>
      		<option value="<?php echo $key + 1;?>"><?php echo $value;?></option>
      		<?php
      	}
      	?>
      	</select>

      	<?php
      } else {
      	if ($tsx['field']['type'] == 'textbox') { ?>
      		<input id="<?php echo $tsx['field']['fid'];?>" name="<?php echo $tsx['field']['fid'];?>" type="text">
      	<?php } else if ($tsx['field']['type'] == 'textarea') {?>
      		<textarea id="<?php echo $tsx['field']['fid'];?>" name="<?php echo $tsx['field']['fid'];?>" rows="3"></textarea>
<?php } } ?>
</div>