<style>
   .login_left_content{
      background: url('<?php echo $tsx['config']['theme_url'];?>/img/welcome/Cartoons.svg');
   }
   .login_div>div {
    width: 100%;
}
.footer {
    margin-top: 110px;
}
</style>
<div class="wrapper">

<svg class="black-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="749.408" height="205.786" viewBox="0 0 749.408 205.786">
  <defs>
    <linearGradient id="linear-gradient" x1="0.5" x2="0.5" y2="1" gradientUnits="objectBoundingBox">
      <stop offset="0" stop-color="#343535"/>
      <stop offset="1" stop-color="#181717"/>
    </linearGradient>
  </defs>
  <path id="Path_6944" data-name="Path 6944" d="M-5446.921,2382.22s56.339,35.212,97.03,139.591,142.954,58.659,183.2,40.26,58.17-10.726,116.144-16.1,98.37-35.6,112.644-71.44,41.936-71.2,87.934-74.325,54.709,7.772,82.308,11.222,70.146-26.449,70.146-26.449Z" transform="translate(5446.921 -2382.22)" fill="url(#linear-gradient)"/>
</svg>
<img class="red-svg" src="<?php echo $tsx['config']['theme_url'];?>/img/welcome/red-wave.svg" alt="wave">


   <div class="new_login">
      <div class="login_header">
         <div>
            <div class="header_logo">
               <a href="<?php echo $tsx['config']['site_url'];?>" class="logo"><img src="<?php echo $tsx['config']['theme_url'];?>/img/logo.<?php echo $tsx['config']['logo_extension'];?>" alt="Logo"> </a>
            </div>
            <div class="header_text">
               <p><?php echo str_replace(array('{site_name}', '{Site_Name}', '{sito_name}'), array($tsx['config']['siteName'], $tsx['config']['siteName'], $tsx['config']['siteName']), $tsx['lang']['register_create_account'])?></p>
            </div>
         </div>
         <div class="form-tabs">
            <a href="<?php echo $tsx['config']['site_url'];?>"><button><?php echo $tsx['lang']['login']?></button></a>
         </div>
         <div class="dontHaveAnAccount">
            <p><?php echo $tsx['lang']['dont_have_account']?> <a class="dec main" href="<?php echo tsx_SeoLink('index.php?link1=register');?>"><?php echo $tsx['lang']['register']?></a></p>
         </div>
      </div>
      <div class="login_div" id="login_div">
        <div class="formDiv">
		<?php
			$allow_switch = false;
			if ($tsx['config']['sms_provider'] == 'twilio') {
        if( $tsx['config']['sms_twilio_username'] !== "" AND  $tsx['config']['sms_twilio_passtsxrd'] !== "" ){
					if( $tsx['config']['emailValidation'] == 1 ) {
						if( $tsx['config']['sms_or_email'] == "sms" ) {
							$allow_switch = true;
						}
					}
				}
			} else if ($tsx['config']['sms_provider'] == 'bulksms') {
        if( $tsx['config']['sms_username'] !== "" AND  $tsx['config']['sms_passtsxrd'] !== "" ){
					if( $tsx['config']['emailValidation'] == 1 ) {
						if( $tsx['config']['sms_or_email'] == "sms" ) {
							$allow_switch = true;
						}
					}
				}
			} else if ($tsx['config']['sms_provider'] == 'infobip') {
        if( $tsx['config']['infobip_api_key'] !== "" AND  $tsx['config']['infobip_base_url'] !== "" ){
					if( $tsx['config']['emailValidation'] == 1 ) {
						if( $tsx['config']['sms_or_email'] == "sms" ) {
							$allow_switch = true;
						}
					}
				}
			}
		?>

		<?php if( $allow_switch ){ ?>
			<form  class="x_chooser">
				<div class="login_signup_combo joinda_forgot_choice">
					<div class="login__">
						<button type="button" class="btn btn-main btn-mat" id="recover_passtsxrd_by_email"><?php echo $tsx['lang']['recover_passtsxrd_by_email']?></button>&nbsp;&nbsp;
						<button type="button" class="btn btn-main btn-mat" id="recover_passtsxrd_by_sms"><?php echo $tsx['lang']['recover_passtsxrd_by_sms']?></button>
					</div>
				</div>
			</form>
		<?php } ?>

		<form id="forgot-form" class="recover_passtsxrd_by_email" method="post" <?php if( $allow_switch ){ echo 'style="display: none;"'; } ?>>
			<p class="title"><?php echo $tsx['lang']['forget_passtsxrd']?></p>
			<div class="alert alert-danger login_errors"></div>
			<div class="joinda_form_fields">
				<label for="recoveremail"><?php echo $tsx['lang']['email']?></label>
				<input id="recoveremail" name="recoveremail" type="email" autofocus />
			</div>
			<?php if($tsx['config']['reCaptcha'] == 1) {?>
				<div class="form-group" style="margin-top:10px;">
					<div class="g-recaptcha" data-sitekey="<?php echo $tsx['config']['reCaptchaKey']?>"></div>
				</div>
			<?php } ?>
			<div class="login_signup_combo">
				<div class="login__">
					<button type="submit" style="background-color: #c32e3a!important;" class="btn btn-main btn-mat add_joinda_loader"><?php echo $tsx['lang']['recover_passtsxrd']?></button>
				</div>
			</div>
		</form>

		<form id="forgot-form-sms" class="recover_passtsxrd_by_sms" method="post" style="display: none;">
			<div class="login_errors"></div>
			<div class="joinda_form_fields">
				<label for="recoverphone"><?php echo $tsx['lang']['phone_number']?></label>
				<input id="recoverphone" name="recoverphone" type="text" autofocus />
			</div>

			<div class="login_signup_combo">
				<div class="login__">
					<button type="submit" style="background-color: #c32e3a!important;" class="btn btn-main btn-mat add_joinda_loader"><?php echo $tsx['lang']['recover_passtsxrd']?></button>
				</div>
			</div>
		</form>
        </div>
      </div>
      <div class="footer">
   <?php echo tsx_LoadPage('footer/welcome');?>
   <div class="clearfix"></div>
</div>
   </div>
</div>
<script>

var tsxrking = false;
var $this = $('#forgot-form');
var $this_sms = $('#forgot-form-sms');
var $state = $this.find('.login_errors');
var $state_sms = $this_sms.find('.login_errors');
$(function() {
	$('#recover_passtsxrd_by_email').click(function(){
		$('.x_chooser').hide();
		$('.recover_passtsxrd_by_email').show();
	});
	$('#recover_passtsxrd_by_sms').click(function(){
		$('.x_chooser').hide();
		$('.recover_passtsxrd_by_sms').show();
	});

  tsx_SetTimer();
  $this.ajaxForm({
    url: tsx_Ajax_Requests_File() + '?f=recover',
    beforeSend: function() {
		tsxrking = true;
		$this.find('button').attr("disabled", true);
		$this.find('.add_joinda_loader').addClass('btn-loading');
    },
    success: function(data) {
      if (data.status == 200) {
				$state.removeClass('alert-danger');
      	$state.addClass('alert-success');
        $state.html('<?php echo $tsx['lang']['email_sent'] ?>');
		$this.find('.add_joinda_loader').removeClass('btn-loading');
      } else {
		$this.find('button').attr("disabled", false);
		$this.find('.add_joinda_loader').removeClass('btn-loading');
        $state.html(data.errors);
      }
      tsxrking = false;
    }
  });

	$this_sms.ajaxForm({
    url: tsx_Ajax_Requests_File() + '?f=recoversms',
    beforeSend: function() {
		tsxrking = true;
		$this_sms.find('button').attr("disabled", true);
		$this_sms.find('.add_joinda_loader').addClass('btn-loading');
    },
    success: function(data) {
      if (data.status == 200) {
				$state_sms.removeClass('alert-danger');
      	$state_sms.addClass('alert-success');
        $state_sms.html('<?php echo $tsx['lang']['recoversms_sent'] ?>');
				$this_sms.find('.add_joinda_loader').removeClass('btn-loading');
				setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else {
				$this_sms.find('button').attr("disabled", false);
				$this_sms.find('.add_joinda_loader').removeClass('btn-loading');
        $state_sms.html(data.errors);
      }
      tsxrking = false;
    }
  });

});
</script>
