<?php echo tsx_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
	<?php echo tsx_LoadPage('welcome/welcome-header-logo');?>
	<form class="login" id="forgot-form" method="post" style="padding-bottom:10px;">
		<h5><?php echo $tsx['lang']['invalid_markup']; ?>.</h5>
		<a href="<?php echo tsx_SeoLink('index.php?link1=welcome');?>"><?php echo $tsx['lang']['go_back'] ?></a>
	</form>
	<?php echo tsx_LoadPage('footer/welcome');?>
</div>
<?php echo tsx_LoadPage('welcome/welcome-users-profiles');?>