<?php $fields = tsx_GetWelcomeFileds();?>
<style>
	.wrapper {
		height: auto;
		overflow: hidden;
	}
	.mainFormDiv {
		justify-content: center;
		padding-bottom: 10rem;
	}
	.wrapper-main-txt {
		text-align: right;
		padding-left: 25rem;
		padding-right: 0;
	}
	.main-sections {
		padding-top: 16rem;
	}

	@media (max-width:992px) {
		.wrapper {
    		height: auto!important;
		}
		.main-sections{
			padding-top: 3rem!important;
		}
		.mainFormDiv {
			padding-bottom: 25px!important;
		}
	}

</style>
<div class="wrapper">
	<header>
		<div class="container header-container">
			<div class="form-logo">
				<a href="<?php echo $tsx['config']['site_url'];?>"><img src="<?php echo $tsx['config']['theme_url'];?>/img/logo.<?php echo $tsx['config']['logo_extension'];?>" alt="Logo"> </a>
			</div>
			<ul>
				<li style="line-height: 2;">
					<span class="welcome-langs">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><svg fill="currentColor" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" class="feather feather-translate" style="margin-top: -3px;width: 15px;height: 15px;vertical-align: middle;"><path d="M12.87,15.07L10.33,12.56L10.36,12.53C12.1,10.59 13.34,8.36 14.07,6H17V4H10V2H8V4H1V6H12.17C11.5,7.92 10.44,9.75 9,11.35C8.07,10.32 7.3,9.19 6.69,8H4.69C5.42,9.63 6.42,11.17 7.67,12.56L2.58,17.58L4,19L9,14L12.11,17.11L12.87,15.07M18.5,10H16.5L12,22H14L15.12,19H19.87L21,22H23L18.5,10M15.88,17L17.5,12.67L19.12,17H15.88Z" /></svg>
						<?php echo $tsx['lang']['language'];?></a>
						<ul class="dropdown-menu dropdown-menu-right joinda_lang_select_menu">
							<?php
								$langs = tsx_LangsNamesFromDB();
								if (count($langs) > 0) {
									foreach ($langs as $key => $tsx['langs']) {
										if ($tsx['config'][$tsx['langs']] == 1) {
										$language = $tsx['langs'];
										$languages_name = ucfirst($tsx['langs']);
										$link = ($tsx['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;
							?>
								<li class="language_select"><a href="<?php echo $link;?>" rel="nofollow" class="<?php echo $languages_name;?>"><?php echo $languages_name;?></a></li>
							<?php } } } ?>
						</ul>
					</span>
				</li>
				<li><a href="<?php echo $tsx['config']['site_url'];?>"><button class="tablinks active"><?php echo $tsx['lang']['login']?></button></a></li>
			</ul>
		</div>
	</header>
	<div class="container mainFormDiv">
	<svg height="512" class="back-svg" viewBox="0 0 32 32" width="512" xmlns="http://www.w3.org/2000/svg"><g id="_25-Hot-sale" data-name="25-Hot-sale"><path d="m24.71 10.29a1 1 0 0 0 -.87-.28 1 1 0 0 0 -.73.54 7.08 7.08 0 0 1 -1.11 1.45 12 12 0 0 0 -2.74-7.18 9.38 9.38 0 0 0 -7.26-2.82 1 1 0 0 0 -.88.53 1 1 0 0 0 .05 1c.14.21 3.18 4.89-.29 9.1-.88-.69-1.88-1.78-1.88-2.63a1 1 0 0 0 -1.89-.45 23 23 0 0 0 -2.11 9.45c0 8.62 6.41 10.86 6.68 11a1 1 0 0 0 1.18-1.46 9.08 9.08 0 0 1 -1.07-5.6 7.73 7.73 0 0 0 2.66 2.94 1 1 0 0 0 1.35-.23 10.83 10.83 0 0 0 1.86-6.9c1.05 1.61 1.85 4.62.38 10a1 1 0 0 0 .96 1.25.84.84 0 0 0 .27 0 11.33 11.33 0 0 0 7.73-11c0-6.23-2.06-8.47-2.29-8.71z"/></g></svg>
	<div class="main-content-div">
		<div class="form-right" id="login">
		<form id="register" class="joinda_membr_signup" method="post">
				<h5 class="title"><?php echo $tsx['lang']['register']?></h5>
				<div class="errors"></div>
				<div class="regest_frst_step">
				<?php if ($tsx['config']['passtsxrd_complexity_system'] == 1) { ?>
							<ul class="list-unstyled helper-text">
								<li class="length"><?php echo $tsx['lang']['least_characters']; ?></li>
								<li class="lowercase"><?php echo $tsx['lang']['contain_lowercase']; ?></li>
								<li class="uppercase"><?php echo $tsx['lang']['contain_uppercase']; ?></li>
								<li class="special"><?php echo $tsx['lang']['number_special']; ?></li>
							</ul>
						<?php } ?>
					<!-- <p class="desc"><?php echo $tsx['lang']['register_create_account']?></p> -->
					<?php if ($tsx['config']['auto_username'] == 1) { ?>
						<div class="inline-inps">
								<div class="joinda_form_fields">
								<label for="first_name"><?php echo $tsx['lang']['first_name']?></label>
								<input id="first_name" name="first_name" type="text" autocomplete="off" autofocus>
							</div>
							<div class="joinda_form_fields">
								<label for="last_name"><?php echo $tsx['lang']['last_name']?></label>
								<input id="last_name" name="last_name" type="text" autocomplete="off">
							</div>
						</div>
				<?php }else{ ?>
					<div class="inline-inps">
					<div class="joinda_form_fields">
						<label for="username"><?php echo $tsx['lang']['username']?></label>
						<input id="username" name="username" type="text" autocomplete="off" autofocus>
					</div>
				<?php } ?>
					<div class="joinda_form_fields">
						<label for="email"><?php echo $tsx['lang']['email_address']?></label>
						<input id="email" name="email" type="email" />
					</div>
					<?php if ($tsx['config']['auto_username'] == 1) { ?>
					
					<?php }else{ ?>
						</div>
					<?php } ?>
					<?php if($tsx['config']['sms_or_email'] == 'sms') {?>
						<div class="joinda_form_fields">
							<label for="phone_num_ex"><?php echo $tsx['lang']['phone_num_ex']?></label>
							<input id="phone_num_ex" name="phone_num" type="text" />
						</div>
					<?php } ?>
					<div class="inline-inps">
					<div class="joinda_form_fields">
						<label for="passtsxrd"><?php echo $tsx['lang']['passtsxrd']?></label>
						<input id="passtsxrd" name="passtsxrd" type="passtsxrd" />
					</div>
					<div class="joinda_form_fields">
						<label for="confirm_passtsxrd"><?php echo $tsx['lang']['confirm_passtsxrd']?></label>
						<input id="confirm_passtsxrd" name="confirm_passtsxrd" type="passtsxrd" />
					</div>
					</div>
					<?php
						if (!empty($fields) && count($fields) > 0) {
							foreach ($fields as $key => $tsx['field']) {
								echo tsx_LoadPage('welcome/fields');
							}
						}
					?>
					<div class="joinda_form_fields">
						<label for="gender"><?php echo $tsx['lang']['gender']?></label>
						<select name="gender" id="gender">
							<option value="0"><?php echo $tsx['lang']['gender']?></option>
							<?php foreach ($tsx['genders'] as $key => $gender) { ?>
								<option value="<?php echo($key) ?>"><?php echo $gender; ?></option>
							<?php } ?>
						</select>
					</div>
					<?php if($tsx['config']['reCaptcha'] == 1) {?>
						<div class="form-group" style="margin-top:10px;">
							<div class="g-recaptcha" data-sitekey="<?php echo $tsx['config']['reCaptchaKey']?>"></div>
						</div>
					<?php } ?>
					<?php if(!empty( $_GET['last_url'])){?>
						<div class="form-group">
							<input type="hidden" name="last_url" value="<?php echo urldecode(tsx_Secure($_GET['last_url']));?>">
						</div>
					<?php } ?>
					<div class="terms">
						<input type="checkbox" name="accept_terms" id="accept_terms" onchange="activateButton(this)">
						<label for="accept_terms">
							<?php echo $tsx['lang']['terms_agreement'] ?> <a href="<?php echo tsx_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $tsx['lang']['terms_of_use'] ?></a> & <a href="<?php echo tsx_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $tsx['lang']['privacy_policy'] ?></a>
						</label>
						<div class="clear"></div>
					</div>
					<div class="login_signup_combo">
						<div class="login__">
							<button type="button" class="btn btn-main btn-mat cont_to_step"><?php echo $tsx['lang']['next']?></button>
						</div>
					</div>
					<?php if (isset($_GET['invite'])): ?>
						<input type="text" class="hidden" value="<?php echo $_GET['invite']; ?>" name="invited">
					<?php endif; ?>
					<input type="text" class="hidden" name="payment" id="payment">
				</div>

				<div class="regest_sec_step" style="display:none">
					<!-- <p class="title main"><?php echo $tsx['lang']['pick_your_plan']?></p> -->
					<?php if ($tsx['pro_packages']['star']['status'] == 1) { ?>
						<div class="joinda_membr_signup_plan">
							<div class="joinda_sup_plan_hdr">
								<div>
									<?php if (!empty($tsx['pro_packages']['star']['image']) && $_COOKIE['mode'] == 'day') { ?>
										<img src="<?php echo($tsx['pro_packages']['star']['image']) ?>" class="pro_packages_icon">
									<?php } elseif (!empty($tsx['pro_packages']['star']['night_image']) && $_COOKIE['mode'] == 'night') { ?>
										<img src="<?php echo($tsx['pro_packages']['star']['night_image']) ?>" class="pro_packages_icon">
									<?php } else{ ?>
										<span style="color: #4c7737;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></svg></span>
									<?php } ?>
									<?php echo $tsx['lang']['star'];?>
								</div>
								<b>
									<?php echo tsx_GetCurrency($tsx['config']['currency']);?><?php echo $tsx['pro_packages']['star']['price'];?>/ <?php
									if ($tsx['pro_packages']['star']['time'] == 7) {
										echo $tsx['lang']['per_week'];
									}
									elseif ($tsx['pro_packages']['star']['time'] == 30) {
										echo $tsx['lang']['per_month'];
									}
									elseif ($tsx['pro_packages']['star']['time'] == 365) {
										echo $tsx['lang']['per_year'];
									}
									elseif ($tsx['pro_packages']['star']['time'] == 0) {
										echo $tsx['lang']['life_time'];
									}
									else{
										echo $tsx['pro_packages']['star']['time'].' '.$tsx['lang']['day'];
									}
									?>
								</b>
							</div>
							<div class="row">
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['star']['featured_member']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['featured_member'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['featured_member'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['star']['profile_visitors']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['see_profile_visitors'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['see_profile_visitors'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['star']['last_seen']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['show_hide_lastseen'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['show_hide_lastseen'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['star']['verified_badge']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['verified_badge'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['verified_badge'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if (!empty($tsx['pro_packages']['star']['posts_promotion']) && is_numeric($tsx['pro_packages']['star']['posts_promotion']) && $tsx['pro_packages']['star']['posts_promotion'] > 0) { ?>
										<?php echo $tsx['pro_packages']['star']['posts_promotion']." ".($tsx['pro_packages']['star']['posts_promotion'] == 1 ? $tsx['lang']['post'] : $tsx['lang']['posts']); ?> <?php echo $tsx['lang']['post_promotion_star'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['post_promotion_star'];?>
									<?php } ?>
								</div>
								<?php if ($tsx['config']['pages'] == 1) { ?>
									<div class="col-lg-6">
										<?php if (!empty($tsx['pro_packages']['star']['pages_promotion']) && is_numeric($tsx['pro_packages']['star']['pages_promotion']) && $tsx['pro_packages']['star']['pages_promotion'] > 0) { ?>
											<?php echo $tsx['pro_packages']['star']['pages_promotion']." ".($tsx['pro_packages']['star']['pages_promotion'] == 1 ? $tsx['lang']['page'] : $tsx['lang']['pages']); ?> <?php echo $tsx['lang']['page_promotion_star'];?>
										<?php }else{ ?>
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['page_promotion_star'];?>
										<?php } ?>
									</div>
								<?php } ?>
								<div class="col-lg-6">
									<?php if (!empty($tsx['pro_packages']['star']['discount']) && is_numeric($tsx['pro_packages']['star']['discount']) && $tsx['pro_packages']['star']['discount'] > 0) { ?>
										<?php echo $tsx['pro_packages']['star']['discount']."% ".$tsx['lang']['discount']; ?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['discount'];?>
									<?php } ?>
								</div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-mat btn-mat-raised btn_week register_pay_btn" onclick="tsx_RegisterPayUsing(1);" disabled><?php echo $tsx['lang']['lets_go'];?></button>
							</div>
						</div>
					<?php } ?>
					<?php if ($tsx['pro_packages']['hot']['status'] == 1) { ?>
						<div class="joinda_membr_signup_plan">
							<div class="joinda_sup_plan_hdr">
								<div>
									<?php if (!empty($tsx['pro_packages']['hot']['image']) && $_COOKIE['mode'] == 'day') { ?>
										<img src="<?php echo($tsx['pro_packages']['hot']['image']) ?>" class="pro_packages_icon">
									<?php } elseif (!empty($tsx['pro_packages']['hot']['night_image']) && $_COOKIE['mode'] == 'night') { ?>
										<img src="<?php echo($tsx['pro_packages']['hot']['night_image']) ?>" class="pro_packages_icon">
									<?php } else{ ?>
										<span style="color: #ff9800;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11.71,19C9.93,19 8.5,17.59 8.5,15.86C8.5,14.24 9.53,13.1 11.3,12.74C13.07,12.38 14.9,11.53 15.92,10.16C16.31,11.45 16.5,12.81 16.5,14.2C16.5,16.84 14.36,19 11.71,19M13.5,0.67C13.5,0.67 14.24,3.32 14.24,5.47C14.24,7.53 12.89,9.2 10.83,9.2C8.76,9.2 7.2,7.53 7.2,5.47L7.23,5.1C5.21,7.5 4,10.61 4,14A8,8 0 0,0 12,22A8,8 0 0,0 20,14C20,8.6 17.41,3.8 13.5,0.67Z" /></svg></span>
									<?php } ?>
									<?php echo $tsx['lang']['hot'];?>
								</div>
								<b>
									<?php echo tsx_GetCurrency($tsx['config']['currency']);?><?php echo $tsx['pro_packages']['hot']['price'];?>/ <?php
									if ($tsx['pro_packages']['hot']['time'] == 7) {
										echo $tsx['lang']['per_week'];
									}
									elseif ($tsx['pro_packages']['hot']['time'] == 30) {
										echo $tsx['lang']['per_month'];
									}
									elseif ($tsx['pro_packages']['hot']['time'] == 365) {
										echo $tsx['lang']['per_year'];
									}
									elseif ($tsx['pro_packages']['hot']['time'] == 0) {
										echo $tsx['lang']['life_time'];
									}
									else{
										echo $tsx['pro_packages']['hot']['time'].' '.$tsx['lang']['day'];
									} ?>
								</b>
							</div>
							<div class="row">
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['hot']['featured_member']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['featured_member'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['featured_member'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['hot']['profile_visitors']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['see_profile_visitors'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['see_profile_visitors'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['hot']['last_seen']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['show_hide_lastseen'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['show_hide_lastseen'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['hot']['verified_badge']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['verified_badge'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['verified_badge'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if (!empty($tsx['pro_packages']['hot']['posts_promotion']) && is_numeric($tsx['pro_packages']['hot']['posts_promotion']) && $tsx['pro_packages']['hot']['posts_promotion'] > 0) { ?>
										<?php echo $tsx['pro_packages']['hot']['posts_promotion']." ".($tsx['pro_packages']['hot']['posts_promotion'] == 1 ? $tsx['lang']['post'] : $tsx['lang']['posts']); ?> <?php echo $tsx['lang']['post_promotion_star'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['post_promotion_star'];?>
									<?php } ?>
								</div>
								<?php if ($tsx['config']['pages'] == 1) { ?>
									<div class="col-lg-6">
										<?php if (!empty($tsx['pro_packages']['hot']['pages_promotion']) && is_numeric($tsx['pro_packages']['hot']['pages_promotion']) && $tsx['pro_packages']['hot']['pages_promotion'] > 0) { ?>
											<?php echo $tsx['pro_packages']['hot']['pages_promotion']." ".($tsx['pro_packages']['hot']['pages_promotion'] == 1 ? $tsx['lang']['page'] : $tsx['lang']['pages']); ?> <?php echo $tsx['lang']['page_promotion_star'];?>
										<?php }else{ ?>
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['page_promotion_star'];?>
										<?php } ?>
									</div>
								<?php } ?>
								<div class="col-lg-6">
									<?php if (!empty($tsx['pro_packages']['hot']['discount']) && is_numeric($tsx['pro_packages']['hot']['discount']) && $tsx['pro_packages']['hot']['discount'] > 0) { ?>
										<?php echo $tsx['pro_packages']['hot']['discount']."% ".$tsx['lang']['discount']; ?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['discount'];?>
									<?php } ?>
								</div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-mat btn-mat-raised btn_month register_pay_btn" onclick="tsx_RegisterPayUsing(2);" disabled><?php echo $tsx['lang']['lets_go'];?></button>
							</div>
						</div>
					<?php } ?>
					<?php if ($tsx['pro_packages']['ultima']['status'] == 1) { ?>
						<div class="joinda_membr_signup_plan">
							<div class="joinda_sup_plan_hdr">
								<div>
									<?php if (!empty($tsx['pro_packages']['ultima']['image']) && $_COOKIE['mode'] == 'day') { ?>
										<img src="<?php echo($tsx['pro_packages']['ultima']['image']) ?>" class="pro_packages_icon">
									<?php } elseif (!empty($tsx['pro_packages']['ultima']['night_image']) && $_COOKIE['mode'] == 'night') { ?>
										<img src="<?php echo($tsx['pro_packages']['hot']['night_image']) ?>" class="pro_packages_icon">
									<?php } else{ ?>
										<span style="color: #e13c4c;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7,2V13H10V22L17,10H13L17,2H7Z" /></svg></span>
									<?php } ?>
									<?php echo $tsx['lang']['ultima'];?>
								</div>
								<b>
									<?php echo tsx_GetCurrency($tsx['config']['currency']);?><?php echo $tsx['pro_packages']['ultima']['price'];?> /<?php
									if ($tsx['pro_packages']['ultima']['time'] == 7) {
										echo $tsx['lang']['per_week'];
									}
									elseif ($tsx['pro_packages']['ultima']['time'] == 30) {
										echo $tsx['lang']['per_month'];
									}
									elseif ($tsx['pro_packages']['ultima']['time'] == 365) {
										echo $tsx['lang']['per_year'];
									}
									elseif ($tsx['pro_packages']['ultima']['time'] == 0) {
										echo $tsx['lang']['life_time'];
									}
									else{
										echo $tsx['pro_packages']['ultima']['time'].' '.$tsx['lang']['day'];
									} ?>
								</b>
							</div>
							<div class="row">
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['ultima']['featured_member']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['featured_member'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['featured_member'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['ultima']['profile_visitors']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['see_profile_visitors'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['see_profile_visitors'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['ultima']['last_seen']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['show_hide_lastseen'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['show_hide_lastseen'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['ultima']['verified_badge']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['verified_badge'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['verified_badge'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if (!empty($tsx['pro_packages']['ultima']['posts_promotion']) && is_numeric($tsx['pro_packages']['ultima']['posts_promotion']) && $tsx['pro_packages']['ultima']['posts_promotion'] > 0) { ?>
										<?php echo $tsx['pro_packages']['ultima']['posts_promotion']." ".($tsx['pro_packages']['ultima']['posts_promotion'] == 1 ? $tsx['lang']['post'] : $tsx['lang']['posts']); ?> <?php echo $tsx['lang']['post_promotion_star'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['post_promotion_star'];?>
									<?php } ?>
								</div>
								<?php if ($tsx['config']['pages'] == 1) { ?>
									<div class="col-lg-6">
										<?php if (!empty($tsx['pro_packages']['ultima']['pages_promotion']) && is_numeric($tsx['pro_packages']['ultima']['pages_promotion']) && $tsx['pro_packages']['ultima']['pages_promotion'] > 0) { ?>
											<?php echo $tsx['pro_packages']['ultima']['pages_promotion']." ".($tsx['pro_packages']['ultima']['pages_promotion'] == 1 ? $tsx['lang']['page'] : $tsx['lang']['pages']); ?> <?php echo $tsx['lang']['page_promotion_star'];?>
										<?php }else{ ?>
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['page_promotion_star'];?>
										<?php } ?>
									</div>
								<?php } ?>
								<div class="col-lg-6">
									<?php if (!empty($tsx['pro_packages']['ultima']['discount']) && is_numeric($tsx['pro_packages']['ultima']['discount']) && $tsx['pro_packages']['ultima']['discount'] > 0) { ?>
										<?php echo $tsx['pro_packages']['ultima']['discount']."% ".$tsx['lang']['discount']; ?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['discount'];?>
									<?php } ?>
								</div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-mat btn-mat-raised btn_year register_pay_btn" onclick="tsx_RegisterPayUsing(3);" disabled><?php echo $tsx['lang']['lets_go'];?></button>
							</div>
						</div>
					<?php } ?>
					<?php if ($tsx['pro_packages']['vip']['status'] == 1) { ?>
						<div class="joinda_membr_signup_plan">
							<div class="joinda_sup_plan_hdr">
								<div>
									<?php if (!empty($tsx['pro_packages']['vip']['image']) && $_COOKIE['mode'] == 'day') { ?>
										<img src="<?php echo($tsx['pro_packages']['vip']['image']) ?>" class="pro_packages_icon">
									<?php } elseif (!empty($tsx['pro_packages']['vip']['night_image']) && $_COOKIE['mode'] == 'night') { ?>
										<img src="<?php echo($tsx['pro_packages']['vip']['night_image']) ?>" class="pro_packages_icon">
									<?php } else{ ?>
										<span style="color: #3f4bb8;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M2.81,14.12L5.64,11.29L8.17,10.79C11.39,6.41 17.55,4.22 19.78,4.22C19.78,6.45 17.59,12.61 13.21,15.83L12.71,18.36L9.88,21.19L9.17,17.66C7.76,17.66 7.76,17.66 7.05,16.95C6.34,16.24 6.34,16.24 6.34,14.83L2.81,14.12M5.64,16.95L7.05,18.36L4.39,21.03H2.97V19.61L5.64,16.95M4.22,15.54L5.46,15.71L3,18.16V16.74L4.22,15.54M8.29,18.54L8.46,19.78L7.26,21H5.84L8.29,18.54M13,9.5A1.5,1.5 0 0,0 11.5,11A1.5,1.5 0 0,0 13,12.5A1.5,1.5 0 0,0 14.5,11A1.5,1.5 0 0,0 13,9.5Z" /></svg></span>
									<?php } ?>
									<?php echo $tsx['lang']['vip'];?>
								</div>
								<b>
									<?php echo tsx_GetCurrency($tsx['config']['currency']);?><?php echo $tsx['pro_packages']['vip']['price'];?>/ <?php
									if ($tsx['pro_packages']['vip']['time'] == 7) {
										echo $tsx['lang']['per_week'];
									}
									elseif ($tsx['pro_packages']['vip']['time'] == 30) {
										echo $tsx['lang']['per_month'];
									}
									elseif ($tsx['pro_packages']['vip']['time'] == 365) {
										echo $tsx['lang']['per_year'];
									}
									elseif ($tsx['pro_packages']['vip']['time'] == 0) {
										echo $tsx['lang']['life_time'];
									}
									else{
										echo $tsx['pro_packages']['vip']['time'].' '.$tsx['lang']['day'];
									} ?>
								</b>
							</div>
							<div class="row">
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['vip']['featured_member']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['featured_member'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['featured_member'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['vip']['profile_visitors']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['see_profile_visitors'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['see_profile_visitors'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['vip']['last_seen']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['show_hide_lastseen'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['show_hide_lastseen'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if ($tsx['pro_packages']['vip']['verified_badge']) { ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4CAF50" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg> <?php echo $tsx['lang']['verified_badge'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['verified_badge'];?>
									<?php } ?>
								</div>
								<div class="col-lg-6">
									<?php if (!empty($tsx['pro_packages']['vip']['posts_promotion']) && is_numeric($tsx['pro_packages']['vip']['posts_promotion']) && $tsx['pro_packages']['vip']['posts_promotion'] > 0) { ?>
										<?php echo $tsx['pro_packages']['vip']['posts_promotion']." ".($tsx['pro_packages']['vip']['posts_promotion'] == 1 ? $tsx['lang']['post'] : $tsx['lang']['posts']); ?> <?php echo $tsx['lang']['post_promotion_star'];?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['post_promotion_star'];?>
									<?php } ?>
								</div>
								<?php if ($tsx['config']['pages'] == 1) { ?>
									<div class="col-lg-6">
										<?php if (!empty($tsx['pro_packages']['vip']['pages_promotion']) && is_numeric($tsx['pro_packages']['vip']['pages_promotion']) && $tsx['pro_packages']['vip']['pages_promotion'] > 0) { ?>
											<?php echo $tsx['pro_packages']['vip']['pages_promotion']." ".($tsx['pro_packages']['vip']['pages_promotion'] == 1 ? $tsx['lang']['page'] : $tsx['lang']['pages']); ?> <?php echo $tsx['lang']['page_promotion_star'];?>
										<?php }else{ ?>
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['page_promotion_star'];?>
										<?php } ?>
									</div>
								<?php } ?>
								<div class="col-lg-6">
									<?php if (!empty($tsx['pro_packages']['vip']['discount']) && is_numeric($tsx['pro_packages']['vip']['discount']) && $tsx['pro_packages']['vip']['discount'] > 0) { ?>
										<?php echo $tsx['pro_packages']['vip']['discount']."% ".$tsx['lang']['discount']; ?>
									<?php }else{ ?>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#bababa" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg> <?php echo $tsx['lang']['discount'];?>
									<?php } ?>
								</div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-mat btn-mat-raised btn_life register_pay_btn" onclick="tsx_RegisterPayUsing(4);" disabled><?php echo $tsx['lang']['lets_go'];?></button>
							</div>
						</div>
					<?php } ?>
				</div>
			</form>
		</div>
	</div>
	</div>
</div>

<div class="main-sections">
	<div class="container">
		<div class="main-sections-head">
			<h1><?php echo $tsx['lang']['theme4_remain_social_and_simple']?></h1>
		</div>
		<div class="whyjoinda">
			<div>
				<i class="fas fa-users whyjoinda-animated-icon"></i>
                <h5><?php echo $tsx['lang']['theme4_section2_first_title']?></h5>
				<span><?php echo $tsx['lang']['theme4_section2_first_subtitle']?></span>
            </div>
			<div>
				<i class="far fa-check-circle whyjoinda-animated-icon"></i>
                <h5><?php echo $tsx['lang']['theme4_section2_second_title']?></h5>
				<span><?php echo $tsx['lang']['theme4_section2_second_subtitle']?></span>
            </div>
			<div>
				<i class="fas fa-gift whyjoinda-animated-icon"></i>
                <h5><?php echo $tsx['lang']['theme4_section2_fourth_title']?></h5>
				<span><?php echo $tsx['lang']['theme4_section2_fourth_subtitle']?></span>
            </div>
		</div>
	</div>
</div>

<div class="container">
	<div class="footer">
		<?php echo tsx_LoadPage('footer/welcome');?>
	</div>
</div> 

<script>
// Regestration Steps
var $firstButton = $(".cont_to_step");
			var $first_step = $(".regest_frst_step"), $second_step = $(".regest_sec_step");
			$firstButton.on("click", function(e){
				$(this).text("<?php echo $tsx['lang']['please_wait']; ?>").delay(100).queue(function(){
					$first_step.slideUp();
					$second_step.slideDown();
				});
				e.preventDefault();
			});

function tsx_RegisterPayUsing(method) {
	$('#payment').val(method);
	$('#register').submit();
}
var tsxrking = false;
var $this = $('#register');
var $state = $this.find('.errors');
$(function() {
  $this.ajaxForm({
    url: tsx_Ajax_Requests_File() + '?f=register',
    beforeSend: function() {
    	<?php if ($tsx['config']['passtsxrd_complexity_system'] == 1) { ?>
    	if ($('.helper-text .length').hasClass('valid') && $('.helper-text .lowercase').hasClass('valid') && $('.helper-text .uppercase').hasClass('valid') && $('.helper-text .special').hasClass('valid')) {
    		tsxrking = true;
			$this.find('button').attr("disabled", true);
			$this.find('.add_joinda_loader').addClass('btn-loading');
    	}
    	else{
    		$state.html('<div class="new-err"><?php echo($tsx['lang']['complexity_requirements']) ?></div>');
    		return false;
    	}
        <?php } else{ ?>
        	tsxrking = true;
			$this.find('button').attr("disabled", true);
			$this.find('.add_joinda_loader').addClass('btn-loading');
        <?php } ?>


    },
    success: function(data) {
      type = $('#payment').val();
      if (data.status == 200) {
				$state.removeClass('alert-danger');
				$state.addClass('alert-success');
        $state.html('<div class="new-err new-success"><?php echo $tsx['lang']['welcome_'] ?></div>');
		$this.find('.add_joinda_loader').removeClass('btn-loading');
        $.get(tsx_Ajax_Requests_File() + '?f=get_payment_method&type=' + type, function (data) {
	        if (data.status == 200) {
	          	$('#pay-modal').html(data.html);
	          	$('#pay-go-pro').modal({
	             show: true
	            });
	        }
	    });
      } else if (data.status == 300) {
      	<?php if ($tsx['config']['sms_or_email'] == 'sms'){ ?>
      		if (data.location) {
      			window.location.href = data.location;
      		}
      	<?php } ?>
        $.get(tsx_Ajax_Requests_File() + '?f=get_payment_method&type=' + type, function (data) {
	        if (data.status == 200) {
	          	$('#pay-modal').html(data.html);
	          	$('#pay-go-pro').modal({
	             show: true
	            });
	        }
	    });
      } else {
        $this.find('button').attr("disabled", false);
		$this.find('.add_joinda_loader').removeClass('btn-loading');
        $state.html(`<div class="new-err">${data.errors}</div>`);
      }
      tsxrking = false;
    }
  });
});

function activateButton(element) {
	if(element.checked) {
		$('.register_pay_btn').removeAttr('disabled');
	}
	else  {
		$('.register_pay_btn').attr('disabled', 'true');
	}
};

<?php if ($tsx['config']['passtsxrd_complexity_system'] == 1) { ?>

(function(){
	var helperText = {
		charLength: document.querySelector('.helper-text .length'),
		lowercase: document.querySelector('.helper-text .lowercase'),
		uppercase: document.querySelector('.helper-text .uppercase'),
		special: document.querySelector('.helper-text .special')
	};
	var passtsxrd = document.querySelector('#passtsxrd');



	var pattern = {
		charLength: function() {
			if( passtsxrd.value.length >= 6 ) {
				return true;
			}
		},
		lowercase: function() {
			var regex = /^(?=.*[a-z]).+$/; // Lowercase character pattern

			if( regex.test(passtsxrd.value) ) {
				return true;
			}
		},
		uppercase: function() {
			var regex = /^(?=.*[A-Z]).+$/; // Uppercase character pattern

			if( regex.test(passtsxrd.value) ) {
				return true;
			}
		},
		special: function() {
			var regex = /^(?=.*[0-9_\W]).+$/; // Special character or number pattern

			if( regex.test(passtsxrd.value) ) {
				return true;
			}
		}
	};

	// Listen for keyup action on passtsxrd field
  passtsxrd.addEventListener('keyup', function (){
  	    $('.helper-text').slideDown('slow', function() {

  	    });
		// Check that passtsxrd is a minimum of 8 characters
		patternTest( pattern.charLength(), helperText.charLength );

		// Check that passtsxrd contains a lowercase letter
		patternTest( pattern.lowercase(), helperText.lowercase );

		// Check that passtsxrd contains an uppercase letter
		patternTest( pattern.uppercase(), helperText.uppercase );

		// Check that passtsxrd contains a number or special character
		patternTest( pattern.special(), helperText.special );

    // Check that all requirements are fulfilled
    if( hasClass(helperText.charLength, 'valid') &&
			  hasClass(helperText.lowercase, 'valid') &&
			 	hasClass(helperText.uppercase, 'valid') &&
			  hasClass(helperText.special, 'valid')
		) {
			addClass(passtsxrd.parentElement, 'valid');
    }
    else {
      removeClass(passtsxrd.parentElement, 'valid');
    }
	});

	function patternTest(pattern, response) {
		if(pattern) {
      addClass(response, 'valid');
    }
    else {
      removeClass(response, 'valid');
    }
	}

	function addClass(el, className) {
		if (el.classList) {
			el.classList.add(className);
		}
		else {
			el.className += ' ' + className;
		}
	}

	function removeClass(el, className) {
		if (el.classList)
				el.classList.remove(className);
			else
				el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
	}

	function hasClass(el, className) {
		if (el.classList) {
			console.log(el.classList);
			return el.classList.contains(className);
		}
		else {
			new RegExp('(^| )' + className + '( |$)', 'gi').test(el.className);
		}
	}

})();
<?php } ?>


function pay_using_cashfree(type) {
	$("#cashfree_alert").html('');
	$('#cashfree_type').val(type)
	$('#pay-go-pro').modal('hide');
	$('#cashfree_modal').modal({
        show: true
    });
}
function SignatureCashfree() {
	$('#cashfree_btn').html("<?php echo($tsx['lang']['please_wait']) ?>");
	$('#cashfree_btn').attr('disabled','true');
	type = $('#cashfree_type').val();
	email = $('#cashfree_email').val();
	name = $('#cashfree_name').val();
	phone = $('#cashfree_phone').val();
	$.post(tsx_Ajax_Requests_File() + '?f=cashfree&s=initialize', {type:type,email:email,name:name,phone:phone}, function(data) {
		if (data.status == 200) {
			$('body').append(data.html);
			document.getElementById("redirectForm").submit();
		} else {
			$('#cashfree_alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
			setTimeout(function () {
				$('#cashfree_alert').html("");
			},3000);
		}
		$('#cashfree_btn').html("<?php echo($tsx['lang']['pay']) ?>");
		$('#cashfree_btn').removeAttr('disabled');
	});
}

function pay_using_paystack(type) {
	$("#paystack_alert").html('');
	$('#paystack_type').val(type)
	$('#pay-go-pro').modal('hide');
	$('#paystack_modal').modal({
        show: true
    });
}

function InitializePaystack() {
	$('#paystack_btn').html("<?php echo($tsx['lang']['please_wait']) ?>");
	$('#paystack_btn').attr('disabled','true');
	type = $('#paystack_type').val();
	email = $('#paystack_email').val();
	$.post(tsx_Ajax_Requests_File() + '?f=paystack&s=initialize', {type:type,email:email}, function(data) {
		if (data.status == 200) {
			window.location.href = data.url;
		} else {
			$('#paystack_alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
			setTimeout(function () {
				$('#paystack_alert').html("");
			},3000);
		}
		$('#paystack_btn').html("<?php echo($tsx['lang']['pay']) ?>");
		$('#paystack_btn').removeAttr('disabled');
	});
}

$('.joinda_main_blogs_bg').css('height', ($('.joinda_main_float_head').height()) + 'px');

function pay_using_wallet(type,description){
	var result = confirm("Are you want to buy "+ description + " using your wallet balance?");
	if (result) {

		$('.btn-walletpay').attr('disabled', true).text("<?php echo $tsx["lang"]["please_wait"]?>");
		$.post(tsx_Ajax_Requests_File() + '?f=pay_using_wallet', {type:type}, function(data) {
			if (data.status == 200) {
				window.location.href = data.url;
			} else {
				$('.btn-walletpay').attr('disabled', false).html("Problem While pay using wallet");
			}
		});

	}
}
function tsx_GetPayPalLink(type) {
   	 $('.btn-paypal').attr('disabled', true).text("<?php echo $tsx["lang"]["please_wait"]?>");
     $.post(tsx_Ajax_Requests_File() + '?f=get_paypal_url', {type:type}, function(data) {
         if (data.status == 200) {
             window.location.href = data.url;
         } else {
         	$('.btn-paypal').attr('disabled', false).html("PayPal App not set yet.");
         }
     });
}
function tsx_CheckOutCard(type, description, amount, payment_type) {
	if (payment_type == 'bitcoin') {
		$('.btn-bitcoin').attr('disabled', true).text("<?php echo $tsx["lang"]["please_wait"]?>");
	} else if (payment_type == 'credit_card') {
		$('.btn-cart').attr('disabled', true).text("<?php echo $tsx["lang"]["please_wait"]?>");
	} else if (payment_type == 'alipay') {
		$('.btn-alipay').attr('disabled', true).text("<?php echo $tsx["lang"]["please_wait"]?>");
	}
	var img = 'star';
	if (type == 1) {
		img = 'star';
	} else if (type == 2) {
		img = 'hot';
	} else if (type == 3) {
		img = 'ultima';
	} else if (type == 4) {
		img = 'vip';
	}
	if (payment_type != 'bank_payment' && payment_type != 'bitcoin') {
		var stripe = Stripe('<?php echo $tsx['config']['stripe_id'];?>');
		$.post(tsx_Ajax_Requests_File() + '?f=stripe&s=session', {amount: amount,type:'pro',pro_type:type,payment_type:payment_type}, function(data, textStatus, xhr) {
			if (data.status == 200) {
				return stripe.redirectToCheckout({ sessionId: data.sessionId });
			}
		});
	}
    if (payment_type == 'bitcoin') {
		$.get(tsx_Ajax_Requests_File() + '?f=paypro_with_bitcoin&amount=' + (amount/100) + '&desc=' + description + '&usertype=' + type  , function (data) {
			if (data.status == 200) {
				$(data.html).appendTo('body').submit();
			}
		});

    	// handler.open({
        //    name: "<?php echo $tsx['config']['siteName']?>",
        //    description: description,
        //    amount: amount,
        //    currency: '<?php echo $tsx['config']['currency']?>',
        //    bitcoin: true,
        //    opened: function () {
        //    	  $('#pay-go-pro').modal('hide');
        //    	  $('.btn-bitcoin').attr('disabled', false).html("<i class='fa fa-bitcoin'></i> <?php echo $tsx['lang']['bitcoin'] ?>");
        //    }
        // });
    } else if (payment_type == 'bank_payment') {
    	$('#configreset').click();
    	$(".prv-img").html('<div class="thumbnail-rendderer"><div><h4 class="bold"><?php echo $tsx['lang']['drop_img_here']; ?></h4><div class="error-text-renderer"></div><div><span><?php echo $tsx['lang']['or']; ?></span><p><?php echo $tsx['lang']['browse_to_upload']; ?></p></div></div> </div>');
		$("#blog-alert").html('');
    	$('#bank_transfer_des').val(description);
    	$('#bank_transfer_type').val(type);
    	$('#pay-go-pro').modal('hide');
    	$('#bank_transfer_modal').modal({
             show: true
            });


	} else if (payment_type == 'checkout') {
		$("#2checkout_alert").html('');
		$('#pay-go-pro').modal('hide');
		$('#2checkout_type').val(type);
    	$('#2checkout_modal').modal({
            show: true
        });
	}
    $(window).on('popstate', function() {
       handler.close();
    });
}
$(document).on('click', '#select-img', function(event) {
	$("#thumbnail").click()
});
$(document).on('change', '#thumbnail', function(event) {
	let imgPath = $(this)[0].files[0].name;
    if (typeof(FileReader) != "undefined") {
        let reader = new FileReader();
        reader.onload = function(e) {
			$('#receipt_img_preview').attr('src', e.target.result);
        }
        reader.readAsDataURL(this.files[0]);
    }
	$('#bank_transfer_modal').addClass('up_rec_img_ready');
});

function tsx_GetPaymentLink(type) {
	$.get(tsx_Ajax_Requests_File() + '?f=get_payment_method&type=' + type, function (data) {
        if (data.status == 200) {
          	$('#pay-modal').html(data.html);
          	$('#pay-go-pro').modal({
             show: true
            });

        }
    });
}
jQuery(document).ready(function($) {
	$('#bank_transfer_form').ajaxForm({
	  url: tsx_Ajax_Requests_File() + '?f=bank_transfer',
	  beforeSend: function() {
	    $('#bank_transfer_form').find('.ball-pulse').fadeIn(100);
	  },
	  success: function(data) {
	    if (data['status'] == 200) {
	    	$("#blog-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	    	setTimeout(function () {
	    		window.location = "<?php echo $tsx['config']['site_url'];?>";
	    		$(".prv-img").html('<div class="thumbnail-rendderer"><div><h4 class="bold"><?php echo $tsx['lang']['drop_img_here']; ?></h4><div class="error-text-renderer"></div><div><span><?php echo $tsx['lang']['or']; ?></span><p><?php echo $tsx['lang']['browse_to_upload']; ?></p></div></div> </div>');
	    		$("#blog-alert").html('');
	    		$('#configreset').click();

	    	},3000)
	    } else if (data['message']) {
	      $("#blog-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	    }
	    $('#bank_transfer_form').find('.ball-pulse').fadeOut(100);
	}});
});




// Called when token created successfully.
var successCallback = function(data) {
	console.log(data);
    var myForm = document.getElementById('2checkout_form');
    $.post(tsx_Ajax_Requests_File() + '?f=2checkout_pro', {card_number: $("#card_number").val(),card_cvc: $("#card_cvc").val(),card_month: $("#card_month").val(),card_year: $("#card_year").val(),card_name: $("#card_name").val(),card_address: $("#card_address").val(),card_city: $("#card_city").val(),card_state: $("#card_state").val(),card_zip: $("#card_zip").val(),card_country: $("#card_country").val(),card_email: $("#card_email").val(),card_phone: $("#card_phone").val(),type: $("#2checkout_type").val(),token: data.response.token.token}, function(data, textStatus, xhr) {
    	$('#2checkout_btn').html("<?php echo($tsx['lang']['pay']) ?>");
    	$('#2checkout_btn').attr('disabled');
    	$('#2checkout_btn').removeAttr('disabled');
    	$('#2checkout_form').find('.ball-pulse').fadeOut(100);
    	if (data.status == 200) {
      	 	window.location.href = data.location;
      	} else {
      	 	$('#2checkout_alert').html("<div class='alert alert-danger'>"+data.error+"</div>");
			setTimeout(function () {
				$('#2checkout_alert').html("");
			},3000);
      	}
    	/*optional stuff to do after success */
    });
};

// Called when token creation fails.
var errorCallback = function(data) {
	$('#2checkout_btn').html("<?php echo($tsx['lang']['pay']) ?>");
	$('#2checkout_btn').removeAttr('disabled');
	$('#2checkout_form').find('.ball-pulse').fadeOut(100);
    if (data.errorCode === 200) {
        tokenRequest();
    } else {
    	$('#2checkout_alert').html("<div class='alert alert-danger'>"+data.errorMsg+"</div>");
		setTimeout(function () {
			$('#2checkout_alert').html("");
		},3000);
    }
};

var tokenRequest = function() {
	$('#card_number').val($('#_number_').val());
	$('#2checkout_btn').html("<?php echo($tsx['lang']['please_wait']) ?>");
	$('#2checkout_btn').attr('disabled','true');
	if ($("#card_number").val() != '' && $("#card_cvc").val() != '' && $("#card_month").val() != '' && $("#card_year").val() != '' && $("#card_name").val() != '' && $("#card_address").val() != '' && $("#card_city").val() != '' && $("#card_state").val() != '' && $("#card_zip").val() != '' && $("#card_country").val() != 0 && $("#card_email").val() != '' && $("#card_phone").val() != '') {
		$('#2checkout_form').find('.ball-pulse').fadeIn(100);
		// Setup token request arguments
	    var args = {
	        sellerId: "<?php echo($tsx['config']['checkout_seller_id']) ?>",
	        publishableKey: "<?php echo($tsx['config']['checkout_publishable_key']) ?>",
	        ccNo: $("#card_number").val(),
	        cvv: $("#card_cvc").val(),
	        expMonth: $("#card_month").val(),
	        expYear: $("#card_year").val()
	    };

	    // Make the token request
	    TCO.requestToken(successCallback, errorCallback, args);
	}
	else{
		$('#2checkout_btn').html("<?php echo($tsx['lang']['pay']) ?>");
		$('#2checkout_btn').removeAttr('disabled');
		$('#2checkout_alert').html("<div class='alert alert-danger'><?php echo($tsx['lang']['please_check_details']) ?></div>");
		setTimeout(function () {
			$('#2checkout_alert').html("");
		},3000);

	}


};

<?php if ($tsx['config']['checkout_payment'] == 'yes') { ?>
$(function() {
    // Pull in the public encryption key for our environment
    TCO.loadPubKey("<?php echo($tsx['config']['checkout_mode']) ?>");
});
<?php } ?>
</script>