<div id="welcomeheader" class="navbar-default">
	<div class="container">
		<div class="logo <?php echo tsx_RightToLeft('pull-left');?>">
			<a href="<?php echo $tsx['config']['site_url'];?>"><img src="<?php echo $tsx['config']['theme_url'];?>/img/logo.<?php echo $tsx['config']['logo_extension'];?>" alt="Logo"> </a>
		</div>
		<?php if ($tsx['config']['user_registration'] == 1): ?>
			<ul class="nav navbar-nav navbar-right <?php echo tsx_RightToLeft('pull-right');?>">
				<li class="absul-right">
					<a class="mdbtn" href="<?php echo tsx_SeoLink('index.php?link1=register');?>"><?php echo $tsx['lang']['register']?></a>
				</li>
			</ul>
		<?php endif ?>
	</div>
</div>