<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 middlecol">
    <div class="page-margin mt-0">
					<div class="wo_page_hdng pag_neg_padd pag_alone">
						<div class="wo_page_hdng_innr big_size">
						<svg width="546" height="483" viewBox="0 0 546 483" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M502.45 0.459961H43.03C19.26 0.459961 0 19.73 0 43.49V439.97C0 463.74 19.27 483 43.03 483H502.45C526.22 483 545.48 463.73 545.48 439.97V43.49C545.48 19.73 526.21 0.459961 502.45 0.459961ZM451.07 42.42C470.77 42.42 486.74 58.39 486.74 78.09C486.74 97.79 470.77 113.76 451.07 113.76C431.37 113.76 415.4 97.79 415.4 78.09C415.4 58.39 431.37 42.42 451.07 42.42ZM325.91 428.45H64.68C48.77 428.45 37.97 415.85 44.04 404.4L181.02 146.09C187.09 134.64 203.5 134.64 209.57 146.09L346.55 404.4C352.63 415.86 341.82 428.45 325.91 428.45ZM478.58 428.45C478.58 428.45 364.09 428.45 359.32 428.45C359.32 428.45 373.64 419.38 368.74 403.78C367.2 398.89 302.7 291.05 302.7 291.05L352.73 195.97C360.36 181.46 382.15 181.46 389.78 195.97L497.11 399.97C503.99 413.05 493.98 428.45 478.58 428.45Z" fill="url(#paint0_linear_1118_254)"/>
							<defs>
							<linearGradient id="paint0_linear_1118_254" x1="-37.265" y1="68.8534" x2="532.042" y2="386.334" gradientUnits="userSpaceOnUse">
							<stop offset="0.1555" stop-color="#8200FF"/>
							<stop offset="0.267" stop-color="#832AF6"/>
							<stop offset="0.4549" stop-color="#866CE8"/>
							<stop offset="0.6256" stop-color="#88A0DD"/>
							<stop offset="0.773" stop-color="#89C6D5"/>
							<stop offset="0.8914" stop-color="#8ADDD0"/>
							<stop offset="0.9659" stop-color="#8AE5CE"/>
							</linearGradient>
							</defs>
						</svg>

						<?php echo $wo['album']['title'];?>
						</div>
					</div>
				</div>

            <div class="page-margin wow_content wow_sett_content">
				<form class="create-album-form form-horizontal" method="post">
					<div class="wow_form_fields">
						<label for="album_name"><?php echo $wo['lang']['album_name']; ?></label>
						<input id="album_name" name="album_name" type="text" value="<?php echo $wo['album']['album_name'];?>">
						<span class="help-block"><?php echo $wo['lang']['album_name_help'] ?></span>
					</div>
					<div class="wow_form_fields"  data-block="thumdrop-zone">
						<label><?php echo $wo['lang']['photos'];?></label>
						<div class="wow_fcov_image">
							<div id="productimage-holder"></div>
							<div class="upload_ad_image" onclick="document.getElementById('publisher-photos').click(); return false">
								<div class="upload_ad_image_content">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z"></path></svg> <?php echo $wo['lang']['drop_img_here'] ?> <?php echo $wo['lang']['or']; ?> <?php echo $wo['lang']['browse_to_upload']; ?>
								</div>
							</div>
						</div>
					</div>
					<div class="publisher-hidden-option">
						<div id="progress">
							<span id="percent">0%</span>
							<div class="progress">
								<div id="bar" class="progress-bar progress-bar-striped active"></div> 
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="hidden">
						<input type="file" id="publisher-photos" accept="image/x-png, image/gif, image/jpeg" name="postPhotos[]" multiple="multiple">
					</div>
					<div class="app-general-alert setting-update-alert"></div>
					<input type="hidden" name="id" class="form-control input-md" value="<?php echo $wo['album']['id'];?>">
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
					<div class="text-center">
						<a class="btn btn-mat" data-ajax="?link1=albums" href="<?php echo Wo_SeoLink('index.php?link1=albums');?>">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> <?php echo $wo['lang']['go_back'];?>
						</a>
						<button class="btn btn-main btn-mat btn-mat-raised add_wow_loader" type="submit"><?php echo $wo['lang']['publish']; ?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php echo Wo_LoadPage('sidebar/content');?>
<script type="text/javascript">
jQuery(document).ready(function($) {
    var thumb_drop_block = $("[data-block='thumdrop-zone']");

    if (typeof(window.FileReader) == 'undefined') {
      thumb_drop_block.find('.upload_ad_image_content').text('Drag drop is not supported in your browser!');
    }
    else{
      thumb_drop_block[0].ondragover = function() {
          thumb_drop_block.addClass('hover');
          return false;
      };
          
      thumb_drop_block[0].ondragleave = function() {
          thumb_drop_block.removeClass('hover');
          return false;
      };

      thumb_drop_block[0].ondrop = function(event) {
          event.preventDefault();
          var product_image_holder = $("#productimage-holder");
					product_image_holder.find('img').remove();

          thumb_drop_block.removeClass('hover');
          var file = event.dataTransfer.files;
          for (var i = file.length - 1; i >= 0; i--) {
          	product_image_holder.append("<img src='" + window.URL.createObjectURL(file[i]) + "' alt='Picture' class='thumb-image'>")
          }

          $("#publisher-photos").prop('files', file);
          $("#photo-form input").val(file.length + ' file(s) selected');
          $("#photo-form").slideDown(200);
      };
    }
  });
$(document).ready(function() {
	$("#publisher-photos").on('change', function() {
	//Get count of selected files
	var product_countFiles = $(this)[0].files.length;
	var product_imgPath = $(this)[0].value;
	var extn = product_imgPath.substring(product_imgPath.lastIndexOf('.') + 1).toLowerCase();
	var product_image_holder = $("#productimage-holder");
	product_image_holder.empty();
	if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
		if (typeof(FileReader) != "undefined") {
		//loop for each file selected for uploaded.
		for (var i = 0; i < product_countFiles; i++) 
		{
			var product_reader = new FileReader();
			product_reader.onload = function(e) {
				$("<img />", {
                    "src": e.target.result,
                    "class": "thumb-image"
                  }).appendTo(product_image_holder);
                }
                product_image_holder.show();
                product_reader.readAsDataURL($(this)[0].files[i]);
              }
            } else {
              product_image_holder.html("<p>This browser does not support FileReader.</p>");
            }
         }
	});
});

   $(function() {
    var bar = $('#bar');
    var percent = $('#percent');
    var status = $('#status');
    var publisher_button = $('#publisher-button');
   
     $('form.create-album-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=album&s=create_album',
       beforeSend: function() {
         var percentVal = '0%';
         bar.width(percentVal);
         percent.html(percentVal);
         $('form.create-album-form').find('.add_wow_loader').addClass('btn-loading');
   
       },
       uploadProgress: function (event, position, total, percentComplete) {
           var percentVal = percentComplete + '%';
           bar.width(percentVal);
           $('#progress').slideDown(200);
           if(percentComplete > 50) {
             percent.addClass('white');
           }
           percent.html(percentVal);
      },
       success: function(data) {
         if (data.status == 200) {
           window.location.href = data.href;
         } else {
             var errors = data.errors.join("<br>");
             $('.app-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         $('form.create-album-form').find('.add_wow_loader').removeClass('btn-loading');
         $('#progress').slideUp(200);
       }
     });
   });
</script>