<div class="joinda_content settings-head">
	<div class="infoz">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="background-color: #fef9f8;"><path fill="#e0624b" d="M15,14C17.67,14 23,15.33 23,18V20H7V18C7,15.33 12.33,14 15,14M15,12A4,4 0 0,1 11,8A4,4 0 0,1 15,4A4,4 0 0,1 19,8A4,4 0 0,1 15,12M5,9.59L7.12,7.46L8.54,8.88L6.41,11L8.54,13.12L7.12,14.54L5,12.41L2.88,14.54L1.46,13.12L3.59,11L1.46,8.88L2.88,7.46L5,9.59Z"></path></svg>
		<p style="color:#e0624b;"><?php echo $tsx['lang']['blocked_users']; ?></p>
	</div>
</div>
<div class="tsx_settings_page joinda_content profile-lists">
	<div class="setting-well">
         <?php
         $blocked_users = tsx_GetBlockedMembers($tsx['setting']['user_id']);
         if (count($blocked_users) > 0) {
            foreach ($blocked_users as $tsx['member']) {
                echo tsx_LoadPage('setting/blocked-users-list');
            }
         } else {
            echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z" /></svg>' . $tsx['lang']['no_members_found'] . '</div>';
         }
         ?>
      <div class="clear"></div>
   </div>
</div>