<div class="joinda_content settings-head">
	<div class="infoz">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="background-color: #ddeff2;"><path fill="#00bcd4" d="M12,17A2,2 0 0,0 14,15C14,13.89 13.1,13 12,13A2,2 0 0,0 10,15A2,2 0 0,0 12,17M18,8A2,2 0 0,1 20,10V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V10C4,8.89 4.9,8 6,8H7V6A5,5 0 0,1 12,1A5,5 0 0,1 17,6V8H18M12,3A3,3 0 0,0 9,6V8H15V6A3,3 0 0,0 12,3Z"></path></svg>
		<p style="color:#00bcd4;"><?php echo $tsx['lang']['change_passtsxrd']; ?></p>
	</div>
</div>
<div class="tsx_settings_page joinda_content">
	<form class="form-horizontal setting-change-passtsxrd-form" method="post">
		<div class="setting-passtsxrd-alert setting-update-alert"></div>
        
		<?php if ($tsx['setting']['user_id'] == $tsx['user']['user_id']) { ?>
		<div class="joinda_form_fields">
			<label for="current_passtsxrd"><?php echo $tsx['lang']['current_passtsxrd']; ?></label>  
			<input id="current_passtsxrd" name="current_passtsxrd" type="passtsxrd" class="form-control input-md">
		</div>
		<?php } ?>
		<div class="row">
			<div class="col-md-6">
				<div class="joinda_form_fields">
					<label for="new_passtsxrd"><?php echo $tsx['lang']['new_passtsxrd']; ?></label>
					<input id="new_passtsxrd" name="new_passtsxrd" type="passtsxrd" class="form-control input-md">
					<?php if ($tsx['config']['passtsxrd_complexity_system'] == 1) { ?>
						<ul class="helper-text">
							<li class="length"><?php echo $tsx['lang']['least_characters']; ?></li>
							<li class="lowercase"><?php echo $tsx['lang']['contain_lowercase']; ?></li>
							<li class="uppercase"><?php echo $tsx['lang']['contain_uppercase']; ?></li>
							<li class="special"><?php echo $tsx['lang']['number_special']; ?></li>
						</ul>
					<?php } ?>
				</div>
			</div>
			<div class="col-md-6">
				<div class="joinda_form_fields">
					<label for="repeat_new_passtsxrd"><?php echo $tsx['lang']['repeat_passtsxrd']; ?></label>
					<input id="repeat_new_passtsxrd" name="repeat_new_passtsxrd" type="passtsxrd" class="form-control input-md">
				</div>
			</div>
		</div>
		<hr>
		<div class="joinda_form_fields">
			<label for="ttsx_factor"><?php echo $tsx['lang']['ttsx_factor']; ?></label>  
			<select id="country" name="ttsx_factor" class="form-control">
				<option value="1" <?php echo ($tsx['setting']['ttsx_factor'] == '1')   ? 'selected' : '';?> ><?php echo $tsx['lang']['enable']; ?></option>
				<option value="0" <?php echo ($tsx['setting']['ttsx_factor'] == '0')   ? 'selected' : '';?> ><?php echo $tsx['lang']['disable']; ?></option>
			</select>
		</div>
		
		<div class="text-center">
			<button type="submit" class="btn btn-main btn-mat btn-mat-raised add_joinda_loader"><?php echo $tsx['lang']['save']; ?></button>
		</div>

		<input type="hidden" name="user_id" value="<?php echo $tsx['setting']['user_id'];?>">
        <input type="hidden" name="hash_id" value="<?php echo tsx_CreateSession();?>">
   </form>
</div>
<script type="text/javascript">
$(function() {
  $('form.setting-change-passtsxrd-form').ajaxForm({
    url: tsx_Ajax_Requests_File() + '?f=update_user_passtsxrd',
    beforeSend: function() {
    	<?php if ($tsx['config']['passtsxrd_complexity_system'] == 1) { ?>
    		if ($('.helper-text .length').hasClass('valid') && $('.helper-text .lowercase').hasClass('valid') && $('.helper-text .uppercase').hasClass('valid') && $('.helper-text .special').hasClass('valid')) {
	    		$('.tsx_settings_page').find('.add_joinda_loader').addClass('btn-loading');
	    	}
	    	else{
	    		$('.setting-passtsxrd-alert').html("<div class='alert alert-danger'><?php echo($tsx['lang']['complexity_requirements']) ?></div>");
	    		return false;
	    	}

        <?php } else{ ?>
        	$('.tsx_settings_page').find('.add_joinda_loader').addClass('btn-loading');
        <?php } ?>


      
    },
    success: function(data) {
      if (data.status == 200) {
        $('.setting-passtsxrd-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          $(this).delay(2500).slideUp(500, function() {
              $(this).remove();
          });
        });
        $('form.setting-change-passtsxrd-form').clearForm();
      } else if (data.errors) {
        var errors = data.errors.join("<br>");
        $('.setting-passtsxrd-alert').html('<div class="alert alert-danger">' + errors + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      $('.tsx_settings_page').find('.add_joinda_loader').removeClass('btn-loading');
    }
  });
});

<?php if ($tsx['config']['passtsxrd_complexity_system'] == 1) { ?>

(function(){
	var helperText = {
		charLength: document.querySelector('.helper-text .length'),
		lowercase: document.querySelector('.helper-text .lowercase'),
		uppercase: document.querySelector('.helper-text .uppercase'),
		special: document.querySelector('.helper-text .special')
	};
	var passtsxrd = document.querySelector('#new_passtsxrd');
	
	
	
	var pattern = {
		charLength: function() {
			if( passtsxrd.value.length >= 6 ) {
				return true;
			}
		},
		lowercase: function() {
			var regex = /^(?=.*[a-z]).+$/; // Lowercase character pattern

			if( regex.test(passtsxrd.value) ) {
				return true;
			}
		},
		uppercase: function() {
			var regex = /^(?=.*[A-Z]).+$/; // Uppercase character pattern

			if( regex.test(passtsxrd.value) ) {
				return true;
			}
		},
		special: function() {
			var regex = /^(?=.*[0-9_\W]).+$/; // Special character or number pattern

			if( regex.test(passtsxrd.value) ) {
				return true;
			}
		}   
	};
	
	// Listen for keyup action on passtsxrd field
  function CheckCPasstsxrd() {
		$('.helper-text').slideDown('slow', function() {
  	    	
  	    });
		// Check that passtsxrd is a minimum of 8 characters
		patternTest( pattern.charLength(), helperText.charLength );
		
		// Check that passtsxrd contains a lowercase letter		
		patternTest( pattern.lowercase(), helperText.lowercase );
		
		// Check that passtsxrd contains an uppercase letter
		patternTest( pattern.uppercase(), helperText.uppercase );
		
		// Check that passtsxrd contains a number or special character
		patternTest( pattern.special(), helperText.special );
    
	    // Check that all requirements are fulfilled
	    if( hasClass(helperText.charLength, 'valid') &&
				  hasClass(helperText.lowercase, 'valid') && 
				 	hasClass(helperText.uppercase, 'valid') && 
				  hasClass(helperText.special, 'valid')
			) {
				addClass(passtsxrd.parentElement, 'valid');
	    }
	    else {
	      removeClass(passtsxrd.parentElement, 'valid');
	    }
	}
  passtsxrd.addEventListener('keyup', CheckCPasstsxrd);
  passtsxrd.addEventListener('input', CheckCPasstsxrd);
	
	function patternTest(pattern, response) {
		if(pattern) {
      addClass(response, 'valid');
    }
    else {
      removeClass(response, 'valid');
    }
	}
	
	function addClass(el, className) {
		if (el.classList) {
			el.classList.add(className);
		}
		else {
			el.className += ' ' + className;
		}
	}
	
	function removeClass(el, className) {
		if (el.classList)
				el.classList.remove(className);
			else
				el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
	}
	
	function hasClass(el, className) {
		if (el.classList) {
			console.log(el.classList);
			return el.classList.contains(className);	
		}
		else {
			new RegExp('(^| )' + className + '( |$)', 'gi').test(el.className);	
		}
	}
	
})();
<?php } ?>
</script>
<style type="text/css">
	 .helper-text {
	    display: none;
	    margin-top: 6px;
	    font-size: 12px;
	    line-height: 22px;
	    color: #808080;
	  }
	  li.valid {
      color: #1fd34a;
    }
</style>