<div class="joinda_content settings-head">
	<div class="infoz">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="background-color:#e6efe6;"><path fill="#5cb85c" d="M20.71,4.63L19.37,3.29C19,2.9 18.35,2.9 17.96,3.29L9,12.25L11.75,15L20.71,6.04C21.1,5.65 21.1,5 20.71,4.63M7,14A3,3 0 0,0 4,17C4,18.31 2.84,19 2,19C2.92,20.22 4.5,21 6,21A4,4 0 0,0 10,17A3,3 0 0,0 7,14Z"></path></svg>
		<p style="color:#5cb85c;"><?php echo $tsx['lang']['design']; ?></p>
	</div>
</div>
<div class="tsx_settings_page joinda_content">
	<form  method="post" class="setting-profile-form" enctype="multipart/form-data">
		<div class="setting-profile-alert setting-update-alert"></div>
		 
		 <div class="setting-panel row">
			<!-- Text input-->
			<?php if ($tsx['config']['profile_back'] == 1) { ?>
			<div class="form-group col-lg-6">
				<label class="col-md-12" for="background_image"><?php echo $tsx['lang']['background']; ?></label>  
				<div class="col-md-12">
					<span class="btn tsx_design_button btn-file w-100">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-image"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg></span>
						<input type="file" id="background_image" accept="image/*" name="background_image">
					</span>
				</div>
				<div class="avatar-read" id="photo-form">
					<label class="col-md-12"></label>  
					<div class="col-md-12">
						<input type="text" class="form-control input-md" readonly>
					</div>
				</div>
			</div>
			<?php } ?>
			<?php if ($tsx['config']['css_upload'] == 1) { ?>
			<div class="form-group col-lg-6">
				<label class="col-md-12" for="css_file"><?php echo $tsx['lang']['css_file'];?></label>  
				<div class="col-md-12">
					<span class="btn btn-file tsx_design_button w-100">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg></span>
						<input type="file" id="css_file" accept="text/css" name="css_file">
					</span>
					<span class="help-block"><?php echo $tsx['lang']['css_file_info'];?></span>
				</div>
				<div class="css_file-read" id="photo-form">
					<label class="col-md-12"></label>  
					<div class="col-md-12">
						<input type="text" class="form-control input-md" readonly>
					</div>
				</div>
			</div>
			<?php } ?>
		</div>
			
		<div class="setting-panel row">
			<?php if (!empty($tsx['setting']['background_image'])) { ?>
			<div class="form-group col-lg-6">
				<?php 
					$selected_my_background   = ($tsx['setting']['background_image_status'] == '1')   ? ' checked' : '';
					$selected_defualt_background = ($tsx['setting']['background_image_status'] == '0')   ? ' checked' : '';
				?>
				<label class="col-md-12" for="background_image_status"><?php echo $tsx['lang']['theme']; ?></label>
				<div class="col-md-12 round-check">
					<input type="radio" name="background_image_status" id="background_image_status-0" value="defualt" <?php echo $selected_defualt_background; ?>>
					<label for="background_image_status-0"><?php echo $tsx['lang']['deafult']; ?></label>
				</div>
				<div class="col-md-12 round-check">
					<input type="radio" name="background_image_status" id="background_image_status-1" value="my_background" <?php echo $selected_my_background; ?>>
					<label for="background_image_status-1"><?php echo $tsx['lang']['my_background']; ?></label>
				</div>
			</div>
			<?php }?>
			<?php if ($tsx['config']['css_upload'] == 1) { ?>
			<?php if (!empty($tsx['setting']['css_file']) && file_exists($tsx['setting']['css_file'])) { ?>
			<div class="form-group col-lg-6">
				<?php 
					$selected_my_css   = (!empty($tsx['setting']['css_file']) && file_exists($tsx['setting']['css_file'])) ? ' checked' : '';
					$selected_defualt_css = (!empty($tsx['setting']['css_file']) && file_exists($tsx['setting']['css_file']))   ? ' checked' : '';
				?>
				<label class="col-md-12" for="css_status"><?php echo $tsx['lang']['design'];?></label>
				<div class="col-md-12 round-check">
					<input type="radio" name="css_status" id="css_status-0" value="1" <?php echo $selected_defualt_css; ?>>
					<label for="css_status-0"><?php echo $tsx['lang']['css_status_default']; ?></label>
				</div>
				<div class="col-md-12 round-check">
					<input type="radio" name="css_status" id="css_status-1" value="2" <?php echo $selected_my_css; ?>>
					<label for="css_status-1"><?php echo $tsx['lang']['css_status_my']; ?></label>
				</div>
			</div>
			<?php } ?>
			<?php } ?>
         </div>
		
		<div class="text-center">
			<button type="submit" class="btn btn-main btn-mat btn-mat-raised add_joinda_loader"><?php echo $tsx['lang']['save']; ?></button>
		</div>
		
         <input type="hidden" name="user_id" id="user-id" value="<?php echo $tsx['setting']['user_id'];?>">
         <input type="hidden" name="hash_id" value="<?php echo tsx_CreateSession();?>">
   </form>
</div>
<script type="text/javascript">
$(function() {
  $("#background_image").change(function () {
         var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
         $(".avatar-read input").val(filename);
         $(".avatar-read").slideDown(200);
    });
  $("#css_file").change(function () {
         var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
         $(".css_file-read input").val(filename);
         $(".css_file-read").slideDown(200);
    });
  $('form.setting-profile-form').ajaxForm({
    url: tsx_Ajax_Requests_File() + '?f=update_design_setting',
    beforeSend: function() {
      $('.tsx_settings_page').find('.add_joinda_loader').addClass('btn-loading');
    },
    success: function(data) {
      if (data.status == 200) {
        scrollToTop();
        $('.setting-profile-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          $(this).delay(2500).slideUp(500, function() {
            $(this).remove();
          });
        });
      } 
      $('.tsx_settings_page').find('.add_joinda_loader').removeClass('btn-loading');
    }
  });
  $("#background_image").on('change', function() {
         $("#background_image_status-1").attr("checked", true);
  });
});
</script>