<div class="leftcol-sidebar"><?php echo tsx_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 middlecol">
    <div class="page-margin mt-0">
					<div class="tsx_page_hdng pag_neg_padd pag_alone">
						<div class="tsx_page_hdng_innr big_size">
						<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="28" height="21.778" viewBox="0 0 28 21.778">
						<defs>
							<linearGradient id="linear-gradient318" x1="0.5" x2="0.5" y2="1" gradientUnits="objectBoundingBox">
							<stop offset="0" stop-color="#e335f1"></stop>
							<stop offset="1" stop-color="#fc6519"></stop>
							</linearGradient>
						</defs>
						<path id="Icon_awesome-images" data-name="Icon awesome-images" d="M23.333,20.917v.778A2.333,2.333,0,0,1,21,24.028H2.333A2.333,2.333,0,0,1,0,21.694V9.25A2.333,2.333,0,0,1,2.333,6.917h.778V17.028A3.893,3.893,0,0,0,7,20.917ZM28,17.028V4.583A2.333,2.333,0,0,0,25.667,2.25H7A2.333,2.333,0,0,0,4.667,4.583V17.028A2.333,2.333,0,0,0,7,19.361H25.667A2.333,2.333,0,0,0,28,17.028ZM12.444,6.917a2.333,2.333,0,1,1-2.333-2.333A2.333,2.333,0,0,1,12.444,6.917Zm-4.667,7,2.7-2.7a.583.583,0,0,1,.825,0l1.921,1.921L19.81,6.551a.583.583,0,0,1,.825,0l4.254,4.254V16.25H7.778Z" transform="translate(0 -2.25)" fill="url(#linear-gradient318)"></path>
						</svg><?php echo $tsx['album']['title'];?>
						</div>
					</div>
				</div>

            <div class="page-margin joinda_content joinda_sett_content">
				<form class="create-album-form form-horizontal" method="post">
					<div class="joinda_form_fields">
						<label for="album_name"><?php echo $tsx['lang']['album_name']; ?></label>
						<input id="album_name" name="album_name" type="text" value="<?php echo $tsx['album']['album_name'];?>">
						<span class="help-block"><?php echo $tsx['lang']['album_name_help'] ?></span>
					</div>
					<div class="joinda_form_fields"  data-block="thumdrop-zone">
						<label><?php echo $tsx['lang']['photos'];?></label>
						<div class="joinda_fcov_image">
							<div id="productimage-holder"></div>
							<div class="upload_ad_image" onclick="document.getElementById('publisher-photos').click(); return false">
								<div class="upload_ad_image_content">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z"></path></svg> <?php echo $tsx['lang']['drop_img_here'] ?> <?php echo $tsx['lang']['or']; ?> <?php echo $tsx['lang']['browse_to_upload']; ?>
								</div>
							</div>
						</div>
					</div>
					<div class="publisher-hidden-option">
						<div id="progress">
							<span id="percent">0%</span>
							<div class="progress">
								<div id="bar" class="progress-bar progress-bar-striped active"></div> 
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="hidden">
						<input type="file" id="publisher-photos" accept="image/x-png, image/gif, image/jpeg" name="postPhotos[]" multiple="multiple">
					</div>
					<div class="app-general-alert setting-update-alert"></div>
					<input type="hidden" name="id" class="form-control input-md" value="<?php echo $tsx['album']['id'];?>">
					<input type="hidden" name="hash_id" value="<?php echo tsx_CreateSession();?>">
					<div class="text-center">
						<a class="btn btn-mat" data-ajax="?link1=albums" href="<?php echo tsx_SeoLink('index.php?link1=albums');?>">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> <?php echo $tsx['lang']['go_back'];?>
						</a>
						<button class="btn btn-main btn-mat btn-mat-raised add_joinda_loader" type="submit"><?php echo $tsx['lang']['publish']; ?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php echo tsx_LoadPage('sidebar/content');?>
<script type="text/javascript">
jQuery(document).ready(function($) {
    var thumb_drop_block = $("[data-block='thumdrop-zone']");

    if (typeof(window.FileReader) == 'undefined') {
      thumb_drop_block.find('.upload_ad_image_content').text('Drag drop is not supported in your browser!');
    }
    else{
      thumb_drop_block[0].ondragover = function() {
          thumb_drop_block.addClass('hover');
          return false;
      };
          
      thumb_drop_block[0].ondragleave = function() {
          thumb_drop_block.removeClass('hover');
          return false;
      };

      thumb_drop_block[0].ondrop = function(event) {
          event.preventDefault();
          var product_image_holder = $("#productimage-holder");
					product_image_holder.find('img').remove();

          thumb_drop_block.removeClass('hover');
          var file = event.dataTransfer.files;
          for (var i = file.length - 1; i >= 0; i--) {
          	product_image_holder.append("<img src='" + window.URL.createObjectURL(file[i]) + "' alt='Picture' class='thumb-image'>")
          }

          $("#publisher-photos").prop('files', file);
          $("#photo-form input").val(file.length + ' file(s) selected');
          $("#photo-form").slideDown(200);
      };
    }
  });
$(document).ready(function() {
	$("#publisher-photos").on('change', function() {
	//Get count of selected files
	var product_countFiles = $(this)[0].files.length;
	var product_imgPath = $(this)[0].value;
	var extn = product_imgPath.substring(product_imgPath.lastIndexOf('.') + 1).toLowerCase();
	var product_image_holder = $("#productimage-holder");
	product_image_holder.empty();
	if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
		if (typeof(FileReader) != "undefined") {
		//loop for each file selected for uploaded.
		for (var i = 0; i < product_countFiles; i++) 
		{
			var product_reader = new FileReader();
			product_reader.onload = function(e) {
				$("<img />", {
                    "src": e.target.result,
                    "class": "thumb-image"
                  }).appendTo(product_image_holder);
                }
                product_image_holder.show();
                product_reader.readAsDataURL($(this)[0].files[i]);
              }
            } else {
              product_image_holder.html("<p>This browser does not support FileReader.</p>");
            }
         }
	});
});

   $(function() {
    var bar = $('#bar');
    var percent = $('#percent');
    var status = $('#status');
    var publisher_button = $('#publisher-button');
   
     $('form.create-album-form').ajaxForm({
       url: tsx_Ajax_Requests_File() + '?f=album&s=create_album',
       beforeSend: function() {
         var percentVal = '0%';
         bar.width(percentVal);
         percent.html(percentVal);
         $('form.create-album-form').find('.add_joinda_loader').addClass('btn-loading');
   
       },
       uploadProgress: function (event, position, total, percentComplete) {
           var percentVal = percentComplete + '%';
           bar.width(percentVal);
           $('#progress').slideDown(200);
           if(percentComplete > 50) {
             percent.addClass('white');
           }
           percent.html(percentVal);
      },
       success: function(data) {
         if (data.status == 200) {
           window.location.href = data.href;
         } else {
             var errors = data.errors.join("<br>");
             $('.app-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         $('form.create-album-form').find('.add_joinda_loader').removeClass('btn-loading');
         $('#progress').slideUp(200);
       }
     });
   });
</script>