<div class="leftcol-sidebar"><?php echo tsx_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 profile-lists middlecol">
            <div class="page-margin mt-0">
				<div class="tsx_page_hdng pag_neg_padd pag_alone">
					<div class="tsx_page_hdng_innr big_size">
					<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26.528" height="30.112" viewBox="0 0 26.528 30.112">
				<defs>
					<linearGradient id="linear-gradient3125" x1="0.5" x2="0.5" y2="1" gradientUnits="objectBoundingBox">
					<stop offset="0" stop-color="#88cdff"></stop>
					<stop offset="1" stop-color="#169eff"></stop>
					</linearGradient>
				</defs>
				<path id="Path_5295" data-name="Path 5295" d="M3434.293,9936.6V9928h4.3a1.419,1.419,0,0,1,1.434,1.434v5.736a1.42,1.42,0,0,1-1.434,1.434Zm-2.868,20.075a1.419,1.419,0,0,1-1.434,1.434h-5.736a1.419,1.419,0,0,1-1.434-1.434V9936.6H3413.5v-2.768a1.518,1.518,0,0,1,.187-.7,1.445,1.445,0,0,1,.531-.53l7.886-4.6h9.321Z" transform="translate(-3413.5 -9928.001)" fill="url(#linear-gradient3125)"></path>
				</svg> <?php echo $tsx['lang']['pokes']; ?>
					</div>
				</div>
			</div>

			<div class="tsx_my_pages">
				<div id="poke_content">
					<?php
                        $pokes = $tsx['poke'];
						if (count($pokes) > 0) {
                            ?>
                            <?php
							foreach ($pokes as $key => $tsx['poke']) {
								echo "<div class='tsx_pokes_cont'>" . tsx_LoadPage('poke/poke-list') . "</div>";
                            }
                            ?>
                            <?php
						} else {
							echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,9A1,1 0 0,1 22,10A1,1 0 0,1 21,11H16.53L16.4,12.21L14.2,17.15C14,17.65 13.47,18 12.86,18H8.5C7.7,18 7,17.27 7,16.5V10C7,9.61 7.16,9.26 7.43,9L11.63,4.1L12.4,4.84C12.6,5.03 12.72,5.29 12.72,5.58L12.69,5.8L11,9H21M2,18V10H5V18H2Z" /></svg>' . $tsx['lang']['no_pokes_found'] . '</div>';
						}
					?>
				    <div class="clear"></div>
				</div>
                <div class="clear"></div>
                <?php  if (count($pokes) > 8): ?>
                <div class="load-more">
                    <button class="btn btn-default text-center pointer load-more-pokes">
                    <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather"><polyline points="6 9 12 15 18 9"></polyline></svg>
                    <?php echo $tsx['lang']['load_more'] ?>
                    </button>
                </div>
                <?php endif ?>
			</div>
		</div>
		<?php echo tsx_LoadPage('sidebar/content');?>
	</div>
</div>
<script>
    function tsx_RegisterPokeBack(received_user_id ,self,  send_user_id, poke_id){
        if (!received_user_id || !self || !send_user_id || !poke_id ) {
            return false;
        }
        $(self).attr('disabled',true);
        $(self).find('.button-text').html("<?php echo $tsx['lang']['txt_poked'];?>");

        $.ajax({
            url: tsx_Ajax_Requests_File(),
            type: 'GET',
            dataType: 'json',
            data: {f: 'poke',received_user_id:received_user_id,send_user_id:send_user_id,poke_id:poke_id},
        })
        .done(function(data) {
            if (node_socket_flow == "1") {
                socket.emit("user_notification", { to_id: received_user_id, user_id: _getCookie("user_id")});
            }
            if (data.status == 200) {
                $(self).parent('div').parent('.poke_info').parent('.tsx_poke_users').parent('.tsx_pokes_cont').remove();
                tsx_Delay(function(){
                    $('#pokeuser_' + received_user_id).remove();
                },2000);
            }else{
                $(self).attr('disabled',false);
                $(self).find('.button-text').html("<?php echo $tsx['lang']['poke_back'];?>");
            }
        })
        .fail(function() {
            $(self).attr('disabled',false);
            $(self).find('.button-text').html("<?php echo $tsx['lang']['poke_back'];?>");
            console.log("error");
        })
    }
    $(document).on('click', '.load-more-pokes', function(event) {
        var id = $('.tsx_poke_users').last().attr('id');
        $.post(tsx_Ajax_Requests_File()+"?f=load_poke", {id: id}, function(data, textStatus, xhr) {
            if (data.status == 200 && data.html != '') {
                $('#poke_content').append(data.html);
            }
            else{
                $('.load-more-pokes').remove();
            }
        });
    });
</script>