<div class="tsx_poke_users" id="<?php echo $tsx['poke']['poke_id'];?>">
	<div class="poke_info">
		<div class="<?php echo tsx_RightToLeft('pull-left');?>">
			<a href="<?php echo $tsx['poke']['url'];?>" data-ajax="?link1=timeline&amp;u=<?php echo $tsx['poke']['username']?>">
				<div class="avatar" style="background-image:url(<?php echo $tsx['poke']['avatar']?>)"></div>
			</a>
		</div>
		<div>
			<div>
				<span class="user-popover" data-id="<?php echo $tsx['poke']['user_id'];?>" data-type="user">
					<a href="<?php echo $tsx['poke']['url'];?>" data-ajax="?link1=timeline&amp;u=<?php echo $tsx['poke']['username']?>">
						<span class="user-name"><?php echo $tsx['poke']['name'];?></span>
					</a>
				</span>
			</div>
			<?php //if( !tsx_IsPoked( $tsx['poke']['user_id'] , $tsx['user']['user_id'] ) ) { ?>
				<button type="button" onclick="tsx_RegisterPokeBack(<?php echo $tsx['poke']['user_id'];?>,this,<?php echo $tsx['user']['user_id'];?>,<?php echo $tsx['poke']['id'];?>)" class="btn btn-default btn-sm btn-main">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,9A1,1 0 0,1 22,10A1,1 0 0,1 21,11H16.53L16.4,12.21L14.2,17.15C14,17.65 13.47,18 12.86,18H8.5C7.7,18 7,17.27 7,16.5V10C7,9.61 7.16,9.26 7.43,9L11.63,4.1L12.4,4.84C12.6,5.03 12.72,5.29 12.72,5.58L12.69,5.8L11,9H21M2,18V10H5V18H2Z" /></svg> <span class="button-text"><?php echo $tsx['lang']['poke_back'];?></span>
				</button>
			<?php //} ?>
		</div>
	</div>
</div>