<div class="col-md-4" data-blog-id="<?php echo $tsx['article']['id']; ?>">
	<div class="joinda_main_blogs">
		<div class="avatar">
			<img src="<?php echo $tsx['article']['thumbnail']; ?>" alt="<?php echo $tsx['article']['title']; ?>">
			<div class="joinda_main_blogs_info">
				<a class="postCategory" href="<?php echo $tsx['article']['category_link']; ?>" data-ajax="?link1=blog-category&id=<?php echo $tsx['article']['category']; ?>"><?php echo $tsx['blog_categories'][$tsx['article']['category']]; ?></a>
				<h2 class="art-title"><a href="<?php echo $tsx['article']['url']; ?>"><?php echo $tsx['article']['title']; ?></a></h2>
				<div class="postMeta--author-text">
					<a href="<?php echo $tsx['article']['author']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $tsx['article']['author']['username']; ?>"><?php echo $tsx['article']['author']['name']; ?></a>
					<span class="middot">·</span>
					<time><?php echo date("d M Y",$tsx['article']['posted']); ?></time>
				</div>
				<a href="<?php echo $tsx['article']['url']; ?>" class="btn btn-mat"><?php echo $tsx['lang']['read_more'] ?></a>
			</div>
		</div>
	</div>
</div>