<div class="owl-item" data-blog-id="<?php echo $tsx['article']['id']; ?>">
	<div class="format-standard" style="background-image:url(<?php echo $tsx['article']['thumbnail']; ?>)">
		<div class="blog-h-desc postCategory">
			<h5><?php echo $tsx['blog_categories'][$tsx['article']['category']]; ?></h5>
			<h4 class="art-title"><?php echo $tsx['article']['title']; ?></h4>
		 	<div class="blog-meta-desc">
			 	<span>
				 	<span>
				 		<?php echo $tsx['lang']['by'] ?>
				 	</span>
				 	<a href="<?php echo $tsx['article']['author']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $tsx['article']['author']['username']; ?>">
				 		<?php echo $tsx['article']['author']['name']; ?>
				 	</a>
			 	</span>
				<span class="middot">·</span>
			 	<time>
				 	<?php echo date("d M Y",$tsx['article']['posted']); ?>
			 	</time>
		 	</div>
	 	</div>
		<a href="<?php echo $tsx['article']['url']; ?>" class="o-overlayLink"></a>
	</div>
</div>