<ul class="page-margin wow_content negg_padd list-unstyled event-options-list" id="sidebar-albums-list-container">
	<div class="wo_page_hdng" style="margin-bottom: 5px;">
		<div class="wo_page_hdng_innr">
			<a href="<?php echo Wo_SeoLink('index.php?link1=albums&user=' . $wo['user_profile']['username']);?>" data-ajax="?link1=albums&user=<?php echo $wo['user_profile']['username'];?>"><?php echo $wo['lang']['albums'];?></a>&nbsp;<div style="font-weight: normal">(<?php echo number_format($wo['user_profile']['details']['album_count']);?>)</div>
		</div>
	</div>
	<li>
		<div class="sidebar-albums-container list-sidebar-element"><?php 
			foreach (Wo_GetUserAlbums($wo['user_profile']['user_id'], 'sidebar', 12) as $wo['album']) {
				$wo['album']['album_name'] = $wo['album']['album_name'];
				echo Wo_LoadPage('sidebar/sidebar-album-list');
			}
			?></div>
	</li>
	<li><div class="clear"></div></li>
</ul>