<style>
	li.list-group-item.sidebar-title-back.left-sidebarpro {
    	width: 100%;
	}
</style>
<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 middlecol">
			<div class="page-margin mt-0">
				<div class="pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
					<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="25" height="28.853" viewBox="0 0 25 28.853">
					<defs>
						<linearGradient id="linear-gradient3" x1="0.874" y1="0.355" x2="0" y2="0.366" gradientUnits="objectBoundingBox">
						<stop offset="0" stop-color="#fccf31"></stop>
						<stop offset="1" stop-color="#f55555"></stop>
						</linearGradient>
					</defs>
					<path id="Path_7632" data-name="Path 7632" d="M3754.389,2147h22.222a1.376,1.376,0,0,1,1.388,1.389v26.778a.646.646,0,0,1-.083.319.715.715,0,0,1-.236.264.659.659,0,0,1-.319.1.549.549,0,0,1-.333-.056l-11.529-5.138-11.527,5.138a.551.551,0,0,1-.333.056.661.661,0,0,1-.319-.1.717.717,0,0,1-.236-.264.647.647,0,0,1-.084-.319v-26.778a1.376,1.376,0,0,1,1.389-1.389Zm11.111,15.972,4.083,2.153-.777-4.556,3.292-3.222-4.556-.653-2.042-4.139-2.042,4.139-4.569.653,3.306,3.222-.778,4.556Z" transform="translate(-3753 -2147)" fill="url(#linear-gradient3)"></path>
					</svg><?php echo $wo['lang']['saved_posts']; ?>
					</div>
				</div>
			</div>
			
			<div class="saved-posts">
				<?php
					$stories = Wo_GetSavedPosts($wo['user']['user_id']);
					if (count($stories) <= 0) {
						echo Wo_LoadPage('saved-posts/no-posts');
					} else {
						foreach ($stories as $wo['story']) {
							echo Wo_LoadPage('story/content');
						}
					}
				?>
			</div>
		</div>
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>