<div class="group_chat_mbr_part pointer" title="<?php echo $tsx['lang']['add']; ?>" id="<?php echo $tsx['part']['id']; ?>">
    <div class="avatar <?php echo tsx_RightToLeft('pull-left');?>">
        <img src="<?php echo $tsx['part']['avatar'];?>" alt="<?php echo $tsx['part']['name']; ?> Profile Picture" />
    </div>
    <span class="user-popover" data-id="<?php echo $tsx['part']['id'];?>" data-type="<?php echo $tsx['part']['type'];?>">
        <span class="user-name">
            <?php echo $tsx['part']['name']; ?>
            <?php  if($tsx['part']['verified'] == 1) {   ?>
				<span class="verified-color"><i class="fa fa-check-circle" data-toggle="tooltip" title="<?php echo $tsx['lang']['verified_user'];?>"></i></span>
            <?php  } ?>
        </span>
    </span>
    <?php if($tsx['config']['user_lastseen'] == 1 && $tsx['part']['showlastseen'] != 0) { ?>
    <div class="user-lastseen">
        <?php echo tsx_UserStatus($tsx['part']['user_id'],$tsx['part']['lastseen']); ?>
    </div>
    <?php } ?>
</div>