<div class="recipient-chat-user groups-list" id="group_tab_<?php echo $tsx['group']['group_id'];?>" data-chat-group="<?php echo $tsx['group']['group_id'];?>">
	<div class="user-info" onclick="tsx_OpenChatTab(0,<?php echo $tsx['group']['group_id'];?>);" <?php if (!empty($tsx['group']['last_message'])): ?>title="<?php echo $tsx['group']['last_message']['user_data']['name']; ?>: <?php echo tsx_Time_Elapsed_String($tsx['group']['last_message']['time']); ?>"<?php else: ?>title="<?php echo $tsx['lang']['never']; ?>"<?php endif; ?>>
		<img src="<?php echo $tsx['group']['avatar'];?>"/>
		<span class="chat-user-text" id="chat-tab-id"><?php echo $tsx['group']['group_name']; ?></span>
		<div class="joinda_chat_list-right">
			<?php if (is_array($tsx['group']['last_seen']) && in_array($tsx['group']['group_id'], $tsx['group']['last_seen'])): ?>
				<svg xmlns="http://www.w3.org/2000/svg" width="9" height="9" viewBox="0 0 24 24" ><path fill="#60d465" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
			<?php endif;?>
			<span class="chat-loading-icon"></span>
		</div>
	</div>
</div>
<div class="clear"></div>