<div class="home-sidebar profile-style invitation-users-cont" data-hide-invited-user="<?php echo $tsx['user']['id']; ?>">
    <div class="avatar <?php echo tsx_RightToLeft('pull-left');?>">
            <img src="<?php echo $tsx['user']['avatar'];?>" alt="<?php echo $tsx['user']['name']; ?> Profile Picture" />
     </div>
     <span class="user-popover bold" data-id="<?php echo $tsx['user']['id'];?>" data-type="<?php echo $tsx['user']['type'];?>">
    <a href="<?php echo $tsx['user']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $tsx['user']['username']?>">
        <span class="user-name">
            <?php echo $tsx['user']['name']; ?>
            <?php  if($tsx['user']['verified'] == 1) {   ?>
            <span class="verified-color">
            <i class="fa fa-check-circle" data-toggle="tooltip" title="<?php echo $tsx['lang']['verified_user'];?>"></i>
            </span>
            <?php  } ?>
        </span>
    </a>
    </span>
    <div class="<?php echo tsx_RightToLeft('pull-right');?> user-follow-btn">
        <button class="btn btn-default btn-sm" onclick="tsx_SendEventInvation($(this).attr('data-invited-user'))" data-invited-user="<?php echo $tsx['user']['id']; ?>">
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
			<?php echo $tsx['lang']['invite']; ?>
		</button>
    </div>
</div>