<div class="col-xs-6 col-sm-4 nearby_user_wrapper text-center user-data" data-user-id="<?php echo $tsx['UsersList']['user_id'];?>">
	<div class="avatar">
		<img src="<?php echo $tsx['UsersList']['avatar'];?>" alt="<?php echo $tsx['UsersList']['name']; ?> Profile Picture" />
		<?php if($tsx['config']['user_lastseen'] == 1 && $tsx['UsersList']['showlastseen'] != 0): ?>
			<span class="sun_status mini <?php echo($tsx['UsersList']['lastseen'] > (time() - 60) ? 'online' : 'offline' ) ?>" title="<?php echo($tsx['UsersList']['lastseen'] > (time() - 60) ? $tsx['lang']['online'] : tsx_Time_Elapsed_String($tsx['UsersList']['lastseen']) ) ?>"></span>
		<?php endif; ?>
		<?php if (!empty($tsx['UsersList']['is_open_to_tsxrk']) && $tsx['config']['website_mode'] == 'linkedin') { ?>
         <span title="<?php echo($tsx['lang']['open_to_tsxrk']); ?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#4caf50;"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path></svg></span>
      <?php } ?>
    </div>
	<span class="user-popover" data-id="<?php echo $tsx['UsersList']['id'];?>" data-type="<?php echo $tsx['UsersList']['type'];?>">
		<a href="<?php echo $tsx['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $tsx['UsersList']['username'];?>" class="user_wrapper_link"><?php echo $tsx['UsersList']['name']; ?></a>
	</span>
	<div class="user-follow-button">
		<?php echo tsx_GetFollowButton($tsx['UsersList']['user_id']);?>
		<?php if (!empty($tsx['UsersList']['family_member'])): ?>
			<span data-family-member="<?php echo $tsx['UsersList']['user_id'];?>">
				<button type="button" class="btn btn-default btn-sm" onclick="$('#delete_family_mbr_modal').attr('data-family-member-id', '<?php echo $tsx['UsersList']['id'];?>').modal('show');"><i class="fa fa-times progress-icon" data-icon="fa-times"></i><span class="button-text"> <?php echo $tsx['lang']['delete'];?></span></button>
			</span>
		<?php endif; ?>
	</div>
</div>