<div class="story_views_" id="<?php echo $tsx['story']['id']; ?>">
	<div class="story_view_list">
		<div class="user-avatar">
			<img src="<?php echo $tsx['story']['avatar'];?>" alt="">
		</div>
		<div class="user-name">
			<span class="user-popover" data-type="user" data-id="<?php echo $tsx['story']['user_id']; ?>">
				<a href="<?php echo $tsx['story']['url'];?>"><?php echo $tsx['story']['name'];?></a>
			</span>
		</div>
	</div>
	<div class="clear"></div>
</div>