<div class="col-md-4">
	<div class="profile-style promoted-style page_admin_list" id="member-<?php echo $tsx['member']['user_id'] ?>" >
		<div class="avatar">
			<a href="<?php echo $tsx['member']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $tsx['member']['username']?>">
				<img src="<?php echo $tsx['member']['avatar'];?>" alt="<?php echo $tsx['member']['name']; ?> Profile Picture" />
			</a>
		</div>
		
		<h6>
			<a href="<?php echo $tsx['member']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $tsx['member']['username']?>"><?php echo $tsx['member']['name']; ?></a>
		</h6>
   
		<div class="page-website">
			<?php echo tsx_UserStatus($tsx['member']['user_id'],$tsx['member']['lastseen']); ?>
		</div>
		
		<div class="foot">
			<button type="button" onclick="tsx_AddPageAdmin(<?php echo $tsx['member']['user_id'];?>, <?php echo $tsx['member']['page_id'];?>,this)" class="btn btn-default btn-sm btn-mat">
				<?php if (tsx_IsPageAdminExists($tsx['member']['user_id'],$tsx['member']['page_id'])): ?>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z" /></svg>
				<?php else: ?>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
				<?php endif; ?>
				<span class="button-text"> <?php echo $tsx['lang']['admin'];?></span>
			</button>
			<button type="button" class="btn btn-default btn-sm btn-mat" id="privileges_admin_page_<?php echo($tsx['member']['user_id']) ?>" style="<?php echo tsx_IsPageAdminExists($tsx['member']['user_id'],$tsx['member']['page_id']) ? '' : 'display: none;'; ?>">
				<a href="<?php echo tsx_SeoLink('index.php?link1=page-setting&page=' . $tsx['member']['page_name'] . '&link3=admins');?>?name=<?php echo $tsx['member']['username']?>"  data-ajax="?link1=page-setting&page=<?php echo $tsx['member']['page_name'];?>&link3=admins&name=<?php echo $tsx['member']['username']?>"><?php echo $tsx['lang']['privileges'];?></a>
			</button>
		</div>
	</div>
</div>