<meta property="og:title" content="<?php echo $tsx['story']['product']['name'];?>" />
<meta property="og:type" content="article" />
<meta property="og:image" content="<?php echo $tsx['story']['product']['images'][0]['image']?>" />
<meta property="og:description" content="<?php echo strip_tags($tsx['story']['product']['description']);?>" />
<meta property="og:url" content="<?php echo $tsx['story']['product']['url'];?>" />   
<meta name="twitter:title" content="<?php echo $tsx['story']['product']['name'];?>" />
<meta name="twitter:description" content="<?php echo strip_tags($tsx['story']['product']['description']);?>" />
<meta name="twitter:image" content="<?php echo$tsx['story']['product']['images'][0]['image']?>" />