<meta property="og:type" content="article" />
	  <meta property="og:title" content="<?php echo $tsx['story']['postLinkTitle'];?>" />
	  <meta property="og:image" content="<?php echo ($tsx['story']['postLinkImage'])?>" />
	  <meta property="og:description" content=" <?php echo ($tsx['story']['postLinkContent'])?>" />
	  <meta name="twitter:card" content="summary">
      <meta name="twitter:title" content="<?php echo $tsx['story']['postLinkTitle'];?>" />
      <meta name="twitter:image" content="<?php echo ($tsx['story']['postLinkImage'])?>" />
	  <meta name="twitter:description" content="<?php echo ($tsx['story']['postLinkContent'])?>" /> 