<meta property="og:title" content="<?php echo $tsx['title'];?>" />
      <meta property="og:type" content="article" />
      <meta property="og:image" content="<?php echo $tsx['story']['postSticker']?>" />
      <meta property="og:description" content="<?php echo $tsx['description'];?>" />    
      <meta name="twitter:title" content="<?php echo $tsx['title'];?>" />
      <meta name="twitter:description" content="<?php echo $tsx['description'];?>" />
      <meta name="twitter:image" content="<?php echo $tsx['story']['postSticker']?>" />