<div class="col-md-6 col-sm-12">
	<div class="joinda_content joinda_dev_apps">
		<div class="ap_hdr">
			<div class="avatar <?php echo tsx_RightToLeft('pull-left');?>">
				<a href="<?php echo tsx_SeoLink('index.php?link1=app&app_id=' .  $tsx['app']['id']);?>" data-ajax="?link1=app&app_id=<?php echo($tsx['app']['id']); ?>"><img src="<?php echo $tsx['app']['app_avatar'];?>" alt="<?php echo $tsx['app']['app_name']; ?>" /></a>
			</div>
			<div class="info">
				<div class="ap_name"><a href="<?php echo tsx_SeoLink('index.php?link1=app&app_id=' .  $tsx['app']['id']);?>" data-ajax="?link1=app&app_id=<?php echo($tsx['app']['id']); ?>"><?php echo $tsx['app']['app_name']; ?></a></div>
				<p>App ID: <?php echo $tsx['app']['app_id']; ?></p>
				<a href="<?php echo tsx_SeoLink('index.php?link1=app&app_id=' .  $tsx['app']['id']);?>" data-ajax="?link1=app&app_id=<?php echo($tsx['app']['id']); ?>" class="btn btn-default btn-block btn-mat"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z" /></svg> <?php echo $tsx['lang']['edit']; ?></a>
			</div>
		</div>
	</div>
</div>