<?php echo tsx_LoadPage('forum/headers/header'); ?>
<div class="page-margin joinda_content mt-0">
	<div class="tsx_page_hdng pag_neg_padd pag_alone">
		<div class="tsx_page_hdng_innr">
			<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z"></path></svg></span> <?php echo str_replace('<br>', ', ', $tsx['search-qry']); ?>
		</div>
	</div>
</div>

<?php if (count($tsx['threads']) > 0): ?>
	<table class="table threads-table">
	    <thead class="joinda_forum_dis_thead">
			<tr>
				<th><?php echo $tsx['lang']['topic']; ?></th>
				<th><?php echo $tsx['lang']['replies']; ?> <?php echo $tsx['lang']['views']; ?></th>
				<th><?php echo $tsx['lang']['last_post']; ?></th>
			</tr>
	    </thead>
	    <tbody id="forum-threads">
	    <?php foreach ($tsx['threads'] as $tsx['thread']): ?>
	    	<?php echo tsx_LoadPage("forum/includes/post-list"); ?>
	    <?php endforeach; ?>
	    </tbody>
	</table>
<?php else: ?>
	<?php echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z"></path></svg>' . $tsx['lang']['no_threads_found'] .  '</div>'; ?>
<?php endif; ?>
<?php echo tsx_LoadPage('forum/headers/footer'); ?>