<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 middlecol">
			<div class="page-margin mt-0">
				<div class="pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
					<svg width="553" height="417" viewBox="0 0 553 417" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path d="M276.5 121.84C310.803 121.84 338.61 94.5652 338.61 60.92C338.61 27.2748 310.803 0 276.5 0C242.198 0 214.39 27.2748 214.39 60.92C214.39 94.5652 242.198 121.84 276.5 121.84Z" fill="#03131D"/>
						<path d="M436.09 150.82C466.206 150.82 490.62 126.737 490.62 97.03C490.62 67.3226 466.206 43.24 436.09 43.24C405.974 43.24 381.56 67.3226 381.56 97.03C381.56 126.737 405.974 150.82 436.09 150.82Z" fill="#03131D"/>
						<path d="M111.5 150.82C141.616 150.82 166.03 126.737 166.03 97.03C166.03 67.3226 141.616 43.24 111.5 43.24C81.3841 43.24 56.9702 67.3226 56.9702 97.03C56.9702 126.737 81.3841 150.82 111.5 150.82Z" fill="#03131D"/>
						<path d="M474.34 199.42H405.84C399.72 199.42 393.83 200.39 388.3 202.15C393.64 212.55 396.71 224.32 396.71 236.83V326.77C396.71 330.35 396.19 333.89 395.17 337.33C393.04 344.5 388.55 357.13 380.7 368.59C382.99 369.17 385.35 369.49 387.74 369.49H493.71C500.67 369.49 507.49 367.03 512.49 362.26C522.86 352.38 528.22 337.98 530.38 330.85C531.15 328.29 531.55 325.65 531.55 322.97V255.88C531.56 224.69 505.94 199.42 474.34 199.42Z" fill="#03131D"/>
						<path d="M156.28 326.18V236.83C156.28 224.49 159.28 212.87 164.49 202.58C158.61 200.57 152.32 199.42 145.75 199.42H77.2498C45.6498 199.42 20.0298 224.69 20.0298 255.87V322.52C20.0298 325.43 20.4798 328.32 21.4198 331.08C23.7698 337.97 29.3198 351.3 39.8398 361.77C44.9098 366.82 51.9398 369.48 59.1398 369.48H165.11C167.97 369.48 170.8 369.04 173.49 368.22C165.25 356.69 160.44 344.68 158.09 337.65C156.88 333.95 156.28 330.08 156.28 326.18Z" fill="#03131D"/>
						<path d="M372.6 209.98C361.5 190.25 340.11 176.88 315.51 176.88H237.49C212.59 176.88 190.97 190.59 179.99 210.72C175.1 219.69 172.31 229.93 172.31 240.81V316.3C172.31 319.6 172.82 322.87 173.9 325.99C176.18 332.63 181.14 344.55 189.94 355.26C191.48 357.13 193.1 358.98 194.88 360.75C200.66 366.47 208.66 369.48 216.87 369.48H337.58C345.5 369.48 353.27 366.69 358.97 361.29C360.63 359.71 362.16 358.02 363.6 356.28C372.4 345.65 377.24 332.66 379.35 325.71C380.23 322.81 380.69 319.82 380.69 316.79V240.81C380.69 229.63 377.75 219.12 372.6 209.98Z" fill="#03131D"/>
						<path d="M553 393.06H0V416.64H553V393.06Z" fill="#03131D"/>
					</svg>

					<?php echo $wo['lang']['create_new_group']; ?>
					</div>
				</div>
			</div>
			
			<div class="page-margin wow_content wow_sett_content">
				<form class="create-group-form form-horizontal" method="post">
					<div class="wow_form_fields">
						<label for="group_title"><?php echo $wo['lang']['group_name']; ?></label>
						<input id="group_title" name="group_title" type="text">
					</div>
					<div class="wow_form_fields">
						<label for="group_name"><?php echo $wo['lang']['group'];?> URL</label>
						<div class="input-group">
							<span class="input-group-addon"><?php echo $wo['config']['site_url'];?>/</span>
							<input id="group_name" name="group_name" type="text">
						</div>
					</div>
					<div class="wow_form_fields">
						<label for="group_about"><?php echo $wo['lang']['description']; ?></label>
						<textarea name="about" id="group_about" rows="3"></textarea>
					</div>
					<div class="row">
						<div class="col-md-6">
							<div class="wow_form_fields">
								<label for="privacy"><?php echo $wo['lang']['group_type']; ?></label>
								<select id="privacy" name="privacy">
									<option value="1" ><?php echo $wo['lang']['public'];?> </option>
									<option value="2" ><?php echo $wo['lang']['private'];?> </option>
								</select>
							</div>
						</div>
						<div class="col-md-6">
							<div class="wow_form_fields">
								<label for="category"><?php echo $wo['lang']['category']; ?></label>
								<select name="category" id="category" onchange="GetGroupSubCategory(this)">
									<?php foreach ($wo['group_categories'] as $category_id => $category_name) {?>
									<option value="<?php echo $category_id?>"><?php echo $category_name; ?></option>
									<?php } ?>
								</select>
							</div>
						</div>
						<?php if (!empty($wo['group_sub_categories'])) { ?>
						<div class="col-md-6">
							<div class="wow_form_fields">
								<label for="group_sub_category"><?php echo $wo['lang']['sub_category']; ?></label>
								<select name="group_sub_category" id="group_sub_category">
									<?php
									if (!empty($wo['group_sub_categories'][array_keys($wo['group_categories'])[0]])) {
									foreach ($wo['group_sub_categories'][array_keys($wo['group_categories'])[0]] as $id => $sub_category) { ?>
										<option value="<?php echo $sub_category['id']?>"><?php echo $sub_category['lang']; ?></option>
									<?php } } ?>
								</select>
							</div>
						</div>
					    <?php } ?>
						<div class="clear"></div>
						<?php $fields = Wo_GetCustomFields('group'); 
						if (!empty($fields)) {
							foreach ($fields as $key => $wo['field']) {
								echo Wo_LoadPage('group/fields');
							}
						}
						?>
					</div>
					<div class="app-general-alert setting-update-alert"></div>
					<div class="text-center">
						<a class="btn btn-mat" data-ajax="?link1=groups" href="<?php echo Wo_SeoLink('index.php?link1=groups');?>">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> <?php echo $wo['lang']['go_back'];?>
						</a>
						<button class="btn btn-main btn-mat btn-mat-raised add_wow_loader" type="submit"><?php echo $wo['lang']['create']; ?></button>
					</div>
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
				</form>
			</div>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
	<!-- .row -->
</div>
<!-- .page-margin -->
<script type="text/javascript">
	<?php 
$js_array = json_encode($wo['group_sub_categories']);
echo "var sub_categories_array = ". $js_array . ";\n";
?>
	function GetGroupSubCategory(self) {
		id = $(self).val();
		var text = "";
		if (typeof(sub_categories_array[id]) == 'undefined') {
		    $('#group_sub_category').html('');
		}
		else{
		   	sub_categories_array[id].forEach(function(entry) {
				text = text + "<option value='"+entry.id+"'>"+entry.lang+"</option>";
			});
		    $('#group_sub_category').html(text);
		}
	}
   $(function() {
     $('form.create-group-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=groups&s=create_group',
       beforeSend: function() {
         $('.create-group-form').find('.add_wow_loader').addClass('btn-loading');
       },
       success: function(data) {
         scrollToTop();
         if (data.status == 200) {
           window.location.href = data.location;
         } else {
             var errors = data.errors.join("<br>");
             $('.app-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         $('.create-group-form').find('.add_wow_loader').removeClass('btn-loading');
       }
     });
   });
</script>