<div class="leftcol-sidebar left-col-sidebar-hidden"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="wow_main_float_head contactus">
		<div class="container">
				<h1 class="text-center"> 
					<?php echo $wo['lang']['about'];?> <?php echo $wo['config']['siteName'];?>
				</h1>
		</div>
	</div>
	
	<div class="wow_main_blogs_bg"></div>
	
	<div class="wow_content wo_terms_page">
		<div class="setting-well">
			<?php echo $wo['lang']['about_page'];?>
		</div>
	</div>
</div>


<?php echo Wo_Loadpage('footer/content'); ?>