<style>
   .login_left_content{
      background: url('<?php echo $wo['config']['theme_url'];?>/img/welcome/Cartoons.svg');
   }
   .login_div>div {
    width: 100%;
}
.footer {
    margin-top: 110px;
}
</style>
<div class="wrapper">

<svg class="black-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="749.408" height="205.786" viewBox="0 0 749.408 205.786">
  <defs>
    <linearGradient id="linear-gradient" x1="0.5" x2="0.5" y2="1" gradientUnits="objectBoundingBox">
      <stop offset="0" stop-color="#343535"/>
      <stop offset="1" stop-color="#181717"/>
    </linearGradient>
  </defs>
  <path id="Path_6944" data-name="Path 6944" d="M-5446.921,2382.22s56.339,35.212,97.03,139.591,142.954,58.659,183.2,40.26,58.17-10.726,116.144-16.1,98.37-35.6,112.644-71.44,41.936-71.2,87.934-74.325,54.709,7.772,82.308,11.222,70.146-26.449,70.146-26.449Z" transform="translate(5446.921 -2382.22)" fill="url(#linear-gradient)"/>
</svg>
<img class="red-svg" src="<?php echo $wo['config']['theme_url'];?>/img/welcome/red-wave.svg" alt="wave">


   <div class="new_login">
      <div class="login_header">
         <div>
            <div class="header_logo">
               <a href="<?php echo $wo['config']['site_url'];?>" class="logo"><img src="<?php echo $wo['config']['theme_url'];?>/img/logo.<?php echo $wo['config']['logo_extension'];?>" alt="Logo"> </a>
            </div>
            <div class="header_text">
               <p><?php echo str_replace(array('{site_name}', '{Site_Name}', '{sito_name}'), array($wo['config']['siteName'], $wo['config']['siteName'], $wo['config']['siteName']), $wo['lang']['register_create_account'])?></p>
            </div>
         </div>
         <div class="form-tabs">
            <a href="<?php echo $wo['config']['site_url'];?>"><button><?php echo $wo['lang']['login']?></button></a>
         </div>
         <div class="dontHaveAnAccount">
            <p><?php echo $wo['lang']['dont_have_account']?> <a class="dec main" href="<?php echo Wo_SeoLink('index.php?link1=register');?>"><?php echo $wo['lang']['register']?></a></p>
         </div>
      </div>
      <div class="login_div" id="login_div">
        <div class="formDiv">
        <form id="confirm-form" method="post">
         <p class="title">Confrim your phone</p>
			<div class="alert alert-danger errors"></div>
			<div class="wow_form_fields">
				<label for="phone_num"><?php echo $wo['lang']['phone_number']?></label>
				<input id="phone_num" name="phone_num" type="text" value="<?php echo $wo['confirm_user']['phone_number'];?>" />
			</div>
			<div class="wow_form_fields">
				<label for="confirm_code">Confirmation code</label>
				<input id="confirm_code" name="confirm_code" type="text" autofocus />
			</div>
			<input type="hidden" name="user_id" id="confirm-user-id" value="<?php echo $wo['confirm_user']['user_id'];?>"/>
			<div id="hideMsg" class="item">
				<h2><span>60</span></h2>
			</div>
			<div class="form-group" id="re-send" style="display:none">
				<div class="text-center"><?php echo $wo['lang']['activation_get_code_again'];?> <a href="javascript:void(0);" onclick="Wo_ResendCode();"><i class="fa fa-repeat"></i> <?php echo $wo['lang']['activation_resend'];?></a>
				</div>
			</div>
			<div class="login_signup_combo">
				<div class="login__">
					<button type="submit" style="background-color: #c32e3a!important;" class="btn btn-main btn-mat add_wow_loader"><?php echo $wo['lang']['confirm']?></button>
				</div>
				<div class="signup__"></div>
			</div>
		</form>
        </div>
      </div>
      <div class="footer">
   <?php echo Wo_LoadPage('footer/welcome');?>
   <div class="clearfix"></div>
</div>
   </div>
</div>
<script>

var working = false;
var $this = $('#confirm-form');
var $state = $this.find('.errors');
$(function() {
  Wo_SetTimer();
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=confirm_user',
    beforeSend: function() {
		working = true;$this.find('button').attr("disabled", true);
		$this.find('.add_wow_loader').addClass('btn-loading');
    },
    success: function(data) {
      if (data.status == 200) {
				$state.removeClass('alert-danger');
      	$state.addClass('alert-success');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
		$this.find('.add_wow_loader').removeClass('btn-loading');
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else {
        $this.find('button').attr("disabled", false);
		$this.find('.add_wow_loader').removeClass('btn-loading');
        $state.html(data.errors);
      }
      working = false;
    }
  });
});
</script>
