<style>
   .login_left_content{
      background: url('<?php echo $wo['config']['theme_url'];?>/img/welcome/Cartoons.svg');
   }
   .login_div>div {
    width: 100%;
}
.footer {
    margin-top: 110px;
}
</style>
<div class="wrapper">

<svg class="black-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="749.408" height="205.786" viewBox="0 0 749.408 205.786">
  <defs>
    <linearGradient id="linear-gradient" x1="0.5" x2="0.5" y2="1" gradientUnits="objectBoundingBox">
      <stop offset="0" stop-color="#343535"/>
      <stop offset="1" stop-color="#181717"/>
    </linearGradient>
  </defs>
  <path id="Path_6944" data-name="Path 6944" d="M-5446.921,2382.22s56.339,35.212,97.03,139.591,142.954,58.659,183.2,40.26,58.17-10.726,116.144-16.1,98.37-35.6,112.644-71.44,41.936-71.2,87.934-74.325,54.709,7.772,82.308,11.222,70.146-26.449,70.146-26.449Z" transform="translate(5446.921 -2382.22)" fill="url(#linear-gradient)"/>
</svg>
<img class="red-svg" src="<?php echo $wo['config']['theme_url'];?>/img/welcome/red-wave.svg" alt="wave">

   <div class="new_login">
      <div class="login_header">
         <div>
            <div class="header_logo">
               <a href="<?php echo $wo['config']['site_url'];?>" class="logo"><img src="<?php echo $wo['config']['theme_url'];?>/img/logo.<?php echo $wo['config']['logo_extension'];?>" alt="Logo"> </a>
            </div>
            <div class="header_text">
               <p><?php echo str_replace(array('{site_name}', '{Site_Name}', '{sito_name}'), array($wo['config']['siteName'], $wo['config']['siteName'], $wo['config']['siteName']), $wo['lang']['register_create_account'])?></p>
            </div>
         </div>
         <div class="form-tabs">
            <a href="<?php echo $wo['config']['site_url'];?>"><button><?php echo $wo['lang']['login']?></button></a>
         </div>
         <div class="dontHaveAnAccount">
            <p><?php echo $wo['lang']['dont_have_account']?> <a class="dec main" href="<?php echo Wo_SeoLink('index.php?link1=register');?>"><?php echo $wo['lang']['register']?></a></p>
         </div>
      </div>
      <div class="login_div" id="login_div">
        <div class="formDiv">
		<form id="reset-form" method="post">
			<div class="alert- alert-danger errors"></div>
			<div class="wow_form_fields">
				<label for="password"><?php echo $wo['lang']['new_password']?></label>
				<input id="password" name="password" type="text" autofocus />
				<?php if ($wo['config']['password_complexity_system'] == 1) { ?>
					<ul class="helper-text">
						<li class="length"><?php echo $wo['lang']['least_characters']; ?></li>
						<li class="lowercase"><?php echo $wo['lang']['contain_lowercase']; ?></li>
						<li class="uppercase"><?php echo $wo['lang']['contain_uppercase']; ?></li>
						<li class="special"><?php echo $wo['lang']['number_special']; ?></li>
					</ul>
				<?php } ?>
			</div>
			<input type="hidden" name="id" value="<?php echo $_GET['code'];?>">
			<div class="login_signup_combo">
				<div class="login__">
					<button type="submit" style="background-color: #c32e3a!important;" class="btn btn-main btn-mat add_wow_loader"><?php echo $wo['lang']['reset_password']?></button>
				</div>
				<div class="signup__"></div>
			</div>
		</form>
        </div>
      </div>
      <div class="footer">
   <?php echo Wo_LoadPage('footer/welcome');?>
   <div class="clearfix"></div>
</div>
   </div>
</div>
<script>

var working = false;
var $this = $('#reset-form');
var $state = $this.find('.errors');
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=reset_password',
    beforeSend: function() {
    	<?php if ($wo['config']['password_complexity_system'] == 1) { ?>
    		if ($('.helper-text .length').hasClass('valid') && $('.helper-text .lowercase').hasClass('valid') && $('.helper-text .uppercase').hasClass('valid') && $('.helper-text .special').hasClass('valid')) {
	    		working = true;
				$this.find('button').attr("disabled", true);
				$this.find('.add_wow_loader').addClass('btn-loading');
	    	}
	    	else{
	    		$state.html("<?php echo($wo['lang']['complexity_requirements']) ?>");
	    		return false;
	    	}

        <?php } else{ ?>
        	working = true;
			$this.find('button').attr("disabled", true);
			$this.find('.add_wow_loader').addClass('btn-loading');
        <?php } ?>


    },
    success: function(data) {
      if (data.status == 200 || data.status == 600) {
				$state.removeClass('alert-danger');
      	$state.addClass('alert-success');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
		$this.find('.add_wow_loader').removeClass('btn-loading');
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else {
        $this.find('button').attr("disabled", false);
		$this.find('.add_wow_loader').removeClass('btn-loading');
        $state.html(data.errors);
      }
      working = false;
    }
  });
});

<?php if ($wo['config']['password_complexity_system'] == 1) { ?>

(function(){
	var helperText = {
		charLength: document.querySelector('.helper-text .length'),
		lowercase: document.querySelector('.helper-text .lowercase'),
		uppercase: document.querySelector('.helper-text .uppercase'),
		special: document.querySelector('.helper-text .special')
	};
	var password = document.querySelector('#password');



	var pattern = {
		charLength: function() {
			if( password.value.length >= 6 ) {
				return true;
			}
		},
		lowercase: function() {
			var regex = /^(?=.*[a-z]).+$/; // Lowercase character pattern

			if( regex.test(password.value) ) {
				return true;
			}
		},
		uppercase: function() {
			var regex = /^(?=.*[A-Z]).+$/; // Uppercase character pattern

			if( regex.test(password.value) ) {
				return true;
			}
		},
		special: function() {
			var regex = /^(?=.*[0-9_\W]).+$/; // Special character or number pattern

			if( regex.test(password.value) ) {
				return true;
			}
		}
	};

	// Listen for keyup action on password field
  function CheckCPassword() {
		$('.helper-text').slideDown('slow', function() {
  	    	
  	    });
		// Check that password is a minimum of 8 characters
		patternTest( pattern.charLength(), helperText.charLength );
		
		// Check that password contains a lowercase letter		
		patternTest( pattern.lowercase(), helperText.lowercase );
		
		// Check that password contains an uppercase letter
		patternTest( pattern.uppercase(), helperText.uppercase );
		
		// Check that password contains a number or special character
		patternTest( pattern.special(), helperText.special );
    
	    // Check that all requirements are fulfilled
	    if( hasClass(helperText.charLength, 'valid') &&
				  hasClass(helperText.lowercase, 'valid') && 
				 	hasClass(helperText.uppercase, 'valid') && 
				  hasClass(helperText.special, 'valid')
			) {
				addClass(password.parentElement, 'valid');
	    }
	    else {
	      removeClass(password.parentElement, 'valid');
	    }
	}
  password.addEventListener('keyup', CheckCPassword);
  password.addEventListener('input', CheckCPassword);

	function patternTest(pattern, response) {
		if(pattern) {
      addClass(response, 'valid');
    }
    else {
      removeClass(response, 'valid');
    }
	}

	function addClass(el, className) {
		if (el.classList) {
			el.classList.add(className);
		}
		else {
			el.className += ' ' + className;
		}
	}

	function removeClass(el, className) {
		if (el.classList)
				el.classList.remove(className);
			else
				el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
	}

	function hasClass(el, className) {
		if (el.classList) {
			console.log(el.classList);
			return el.classList.contains(className);
		}
		else {
			new RegExp('(^| )' + className + '( |$)', 'gi').test(el.className);
		}
	}

})();
<?php } ?>
</script>
