<div class="col-xs-3 col-md-3">
	<div class="joinda_pop_gam_list">
		<a href="<?php echo $tsx['game']['url'];?>" data-ajax="?link1=game&id=<?php echo $tsx['game']['id'];?>">
			<div class="avatar">
				<img src="<?php echo $tsx['game']['game_avatar'];?>" alt="<?php echo $tsx['game']['game_name']; ?> Profile Picture" />
			</div>
			<div class="game-name"><?php echo $tsx['game']['game_name']; ?></div>
			<p><?php echo $tsx['lang']['last_play'];?> <?php echo tsx_Time_Elapsed_String($tsx['game']['last_play']);?></p>
		</a>
	</div>
</div>