<div class="col-xs-12 col-md-3" id="game_<?php echo $tsx['game']['id'];?>">
	<div class="joinda_content tsx_game_style">
		<a href="<?php echo $tsx['game']['url'];?>" data-ajax="?link1=game&id=<?php echo $tsx['game']['id'];?>">
			<div class="avatar">
				<img src="<?php echo $tsx['game']['game_avatar'];?>" alt="<?php echo $tsx['game']['game_name']; ?> Profile Picture" />
			</div>
			<div class="game-name"><?php echo $tsx['game']['game_name']; ?></div>
			<div class="btn btn-main btn-mat btn-mat-raised"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M9,2V7.5L12,10.5L15,7.5V2H9M2,9V15H7.5L10.5,12L7.5,9H2M16.5,9L13.5,12L16.5,15H22V9H16.5M12,13.5L9,16.5V22H15V16.5L12,13.5M11,18H13V20H11V18Z" /></svg> <?php echo $tsx['lang']['play'];?></div>
		</a>
	</div>
</div>