<div class="col-xs-6 col-md-2" id="game_<?php echo $tsx['game']['id'];?>">
	<div class="joinda_pop_gam_list">
		<a href="<?php echo $tsx['game']['url'];?>" data-ajax="?link1=game&id=<?php echo $tsx['game']['id'];?>">
			<div class="avatar">
				<img src="<?php echo $tsx['game']['game_avatar'];?>" alt="<?php echo $tsx['game']['game_name']; ?> Profile Picture" />
			</div>
			<div class="game-name"><?php echo $tsx['game']['game_name']; ?></div>
			<p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="#DF2A39" d="M9,2V7.5L12,10.5L15,7.5V2H9M2,9V15H7.5L10.5,12L7.5,9H2M16.5,9L13.5,12L16.5,15H22V9H16.5M12,13.5L9,16.5V22H15V16.5L12,13.5M11,18H13V20H11V18Z" /></svg> <?php echo $tsx['game']['players']; ?> <?php echo $tsx['lang']['users_playing']; ?></p>
		</a>
	</div>
</div>