<?php if (!empty($tsx['story']['color_id']) && !empty($tsx['post_colors'][$tsx['story']['color_id']])) { ?>
	<div dir="auto" 
		<?php if($tsx['config']['colored_posts_system'] == 1){ ?>
			class="tsx_actual_colrd_post" style="
			<?php if (!empty($tsx['post_colors'][$tsx['story']['color_id']]) && !empty($tsx['post_colors'][$tsx['story']['color_id']]->color_1) && !empty($tsx['post_colors'][$tsx['story']['color_id']]->color_2) && !empty($tsx['post_colors'][$tsx['story']['color_id']]->text_color)) { ?>
				background-image: linear-gradient(45deg, <?php echo $tsx['post_colors'][$tsx['story']['color_id']]->color_1; ?> 0%, <?php echo $tsx['post_colors'][$tsx['story']['color_id']]->color_2; ?> 100%);
			<?php }else{ ?>
				background-image:url('<?php echo tsx_GetMedia($tsx['post_colors'][$tsx['story']['color_id']]->image); ?>'); <?php } ?>
			<?php if(strlen($tsx['story']['postText']) > 330){ ?>font-size: 16px;font-weight: normal;<?php } ?>"
		<?php } ?>
	>
		<span data-translate-text="<?php echo $tsx['story']['id']; ?>" <?php if($tsx['config']['colored_posts_system'] == 1){ ?> style="<?php if (!empty($tsx['post_colors'][$tsx['story']['color_id']]) && !empty($tsx['post_colors'][$tsx['story']['color_id']]->text_color)) { ?>color:<?php echo $tsx['post_colors'][$tsx['story']['color_id']]->text_color; ?><?php } ?>"<?php } ?>> <?php echo $tsx['story']['postText']; ?></span>
		<?php if (!empty($tsx['story']['postFeeling']) && $extra_exists == 1) { ?>
			<span class="feeling-text"> — <i class="twa-lg twa twa-<?php echo $tsx['story']['postFeelingIcon'];?>"></i> <?php echo $tsx['lang']['feeling'];?> <?php echo $tsx['lang'][$tsx['story']['postFeeling']];?></span>
		<?php } ?>
		<?php if (!empty($tsx['story']['postTraveling']) && $extra_exists == 1) { ?>
			<span class="feeling-text"> — <i class="fa fa-plane"></i> <?php echo $tsx['lang']['traveling'];?><?php echo $tsx['story']['postTraveling'];?></span>
		<?php } ?>
		<?php if (!empty($tsx['story']['postWatching']) && $extra_exists == 1) { ?>
			<span class="feeling-text"> — <i class="fa fa-eye"></i> <?php echo $tsx['lang']['watching'];?> <?php echo $tsx['story']['postWatching'];?></span>
		<?php } ?>
		<?php if (!empty($tsx['story']['postPlaying']) && $extra_exists == 1) { ?>
			<span class="feeling-text"> — <i class="fa fa-gamepad"></i> <?php echo $tsx['lang']['playing'];?> <?php echo $tsx['story']['postPlaying'];?></span>
		<?php } ?>
		<?php if (!empty($tsx['story']['postListening']) && $extra_exists == 1) { ?>
			<span class="feeling-text"> — <i class="fa fa-headphones"></i> <?php echo $tsx['lang']['listening'];?> <?php echo $tsx['story']['postListening'];?></span>
		<?php } ?>
	</div>
<?php } ?>