<div class="post-fetched-url tsx_post_fetch_event tsx_post_fetch_offer" id="fullsizeimg">
   <a href="<?php echo $tsx['story']['offer']['url'];?>">
      <?php if (!empty($tsx['story']['offer']['image'])) {?>
         <img src="<?php echo $tsx['story']['offer']['image'];?>"/>
      <?php } ?>
      <div class="fetched-url-text">
         <div class="short_start_dt">
            <b><?php echo $tsx['lang']['end_date']." ".$tsx['story']['offer']['expire_date'];?></b>
         </div>
         <div class="url"><?php echo $tsx['story']['offer']['offer_text'].' '.$tsx['story']['offer']['discounted_items']; ?></div>
      </div>
      <div class="clear"></div>
   </a>
</div>