<?php
$post_shared_from = array();
$current_post = $tsx['current_post'] = $tsx['story'];
 ?>
<div class="post-container">
  <div class="post<?php echo (!empty($tsx['story']['post_is_promoted'])) ? ' boosted': '';?>" id="post-<?php echo $tsx['story']['id']; ?>" data-post-id="<?php echo $tsx['story']['id'];?>" <?php if( isset( $tsx['story']['LastTotal'] ) ) { echo 'data-post-total="'.$tsx['story']['LastTotal'].'"'; }?> <?php if( isset( $tsx['story']['ids'] ) ) { echo 'data-post-ids="'.$tsx['story']['ids'].'"'; }?> <?php if( isset( $tsx['story']['dt'] ) ) { echo 'data-post-dt="'.$tsx['story']['dt'].'"'; }?> data-post-type="<?php if (!empty($tsx['story']['parent_id'])) { echo('share'); } ?>">
    <?php
      if (empty($tsx['page'])) {
        $tsx['page'] = 'home';
      }
     if ($tsx['story']['is_post_pinned'] === true && ($tsx['page'] == 'timeline' || $tsx['page'] == 'events' || $tsx['page'] == 'page' || $tsx['page'] == 'group' )) {?>
    <div class="pin-icon" data-toggle="tooltip" title="<?php echo $tsx['lang']['pinned_post'];?>">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bookmark"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path></svg>
    </div>
    <?php } ?>
    <div class="panel panel-white panel-shadow">
      <!-- header -->
      <?php include 'header.phtml'; ?>
      <!-- header -->


      <div class="post-description" id="post-description-<?php echo $tsx['story']['id']; ?>">
        <?php if (!empty($tsx['story']['parent_id'])) { ?>
        <div><p class="edited_text"><?php echo $tsx['story']['postText']; ?></p></div>
        <?php } ?>

        <?php if (!empty($tsx['story']['fund_raise_id']) && empty($tsx['story']['parent_id'])) { ?>
			<?php if (!empty($tsx['story']['fund']['fund']['image'])): ?>
				<div class="post-file" id="fullsizeimg">
					<a href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund']['fund']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund']['fund']['hashed_id']) ?>">
						<img src="<?php echo $tsx['story']['fund']['fund']['image']; ?>" alt="Picture" class="fund">
					</a>
					<div class="joinda_dontd_posts">
						<div class="joinda_dontd_posts_innr">
							<div class="joinda_dontd_posts_left">
								<h4>
									<a href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund']['fund']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund']['fund']['hashed_id']) ?>"><?php echo $tsx['story']['fund']['fund']['title']; ?></a>
								</h4>
								<!--<h5><?php echo $tsx['lang']['amount'] ?> : <?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund']['amount']; ?></h5>-->
								<a href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund']['fund']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund']['fund']['hashed_id']) ?>">
									<p><?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund']['fund']['raised']; ?>  <?php echo $tsx['lang']['raised_of']; ?> <?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund']['fund']['amount']; ?></p>
								</a>
							</div>
							<?php if ($tsx['story']['fund']['fund']['amount'] > $tsx['story']['fund']['fund']['raised']) { ?>
							<div class="joinda_dontd_posts_right">
								<a class="btn" href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund']['fund']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund']['fund']['hashed_id']) ?>"><?php echo $tsx['lang']['donate'] ?></a>
							</div>
							<?php } ?>
						</div>
						<div class="fund_raise_bar">
							<div class="progress">
								<div class="progress-bar" role="progressbar" style="width: <?php echo $tsx['story']['fund']['fund']['bar']; ?>%" aria-valuenow="<?php echo $tsx['story']['fund']['fund']['bar']; ?>" aria-valuemin="0" aria-valuemax="<?php echo($tsx['story']['fund']['fund']['amount']) ?>"></div>
							</div>
						</div>
					</div>
				</div>
			<?php endif; ?>
		<?php } ?>

		<?php if (!empty($tsx['story']['fund_id']) && empty($tsx['story']['parent_id'])) { ?>
			<?php if (!empty($tsx['story']['fund_data']['image'])): ?>
				<div class="post-file" id="fullsizeimg">
					<a href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund_data']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund_data']['hashed_id']) ?>">
						<img src="<?php echo $tsx['story']['fund_data']['image']; ?>" alt="Picture" class="fund">
					</a>
					<div class="joinda_dontd_posts">
						<div class="joinda_dontd_posts_innr">
							<div class="joinda_dontd_posts_left">
								<h4>
									<a href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund_data']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund_data']['hashed_id']) ?>"><?php echo $tsx['story']['fund_data']['title']; ?></a>
								</h4>
								<!--<h5><?php echo $tsx['lang']['amount'] ?> : <?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund_data']['amount']; ?></h5>-->
								<a href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund_data']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund_data']['hashed_id']) ?>">
									<p><?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund_data']['raised']; ?>  <?php echo $tsx['lang']['raised_of']; ?> <?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund_data']['amount']; ?></p>
								</a>
							</div>
							<?php if ($tsx['story']['fund_data']['amount'] > $tsx['story']['fund_data']['raised']) { ?>
							<div class="joinda_dontd_posts_right">
								<a class="btn" href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund_data']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund_data']['hashed_id']) ?>"><?php echo $tsx['lang']['donate'] ?></a>
							</div>
							<?php } ?>
						</div>
						<div class="fund_raise_bar">
							<div class="progress">
								<div class="progress-bar" role="progressbar" style="width: <?php echo $tsx['story']['fund_data']['bar']; ?>%" aria-valuenow="<?php echo $tsx['story']['fund_data']['bar']; ?>" aria-valuemin="0" aria-valuemax="<?php echo($tsx['story']['fund_data']['amount']) ?>"></div>
							</div>
						</div>
					</div>
				</div>
			<?php endif; ?>
		<?php } ?>


        <!-- shared_post -->
         <?php include 'shared_post.phtml'; ?>
        <!-- shared_post -->

		<?php  if (empty($current_post['parent_id'])) { ?>
      <!-- product -->
       <?php include 'product.phtml'; ?>
      <!-- product -->

      <!-- feeling -->
      <?php include 'feeling.phtml'; ?>
      <!-- feeling -->

      <!-- colored post -->
      <?php include 'colored.phtml'; ?>
      <!-- colored post -->

      <!-- embed -->
      <?php include 'embed.phtml'; ?>
      <!-- embed -->

        <!-- postMap -->
        <?php if(!empty($tsx['story']['postMap']) && empty($tsx['story']['postVine']) && empty($tsx['story']['postSoundCloud']) && empty($tsx['story']['postVimeo']) && empty($tsx['story']['postDailymotion']) && empty($tsx['story']['postYoutube']) && empty($tsx['story']['postPlaytube']) && empty($tsx['story']['postDeepsound']) && empty($tsx['story']['postFile']) && ($tsx['config']['google_map'] == 1 || $tsx['config']['yandex_map'] == 1) && (empty($tsx['story']['photo_album']) || (!empty($tsx['story']['photo_album']) && count($tsx['story']['photo_album']) < 2)) && $tsx['story']['multi_image'] != 1) { ?>
        <div class="post-map">
          <?php if ($tsx['config']['google_map'] == 1) { ?>
          <img src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $tsx['story']['postMap'];?>&zoom=13&size=600x250&maptype=roadmap&markers=color:red%7C<?php echo $tsx['story']['postMap'];?>&key=<?php echo $tsx['config']['google_map_api'];?>" width="100%">
          <?php } ?>
           <?php if ($tsx['config']['yandex_map'] == 1) { ?>
            <div id="place_<?php echo($tsx['story']['id']) ?>" <?php echo($tsx['config']['yandex_map'] == 1 ? 'style="width: 100%; height: 300px; padding: 0; margin: 0;"' : '') ?>></div>
            <script type="text/javascript">
                  <?php if (!empty($tsx['story']['postMap'])) { ?>
                    setTimeout(function () {
                      var myMap;
                      ymaps.geocode("<?php echo($tsx['story']['postMap']); ?>").then(function (res) {
                          myMap = new ymaps.Map('place_<?php echo($tsx['story']['id']) ?>', {
                              center: res.geoObjects.get(0).geometry.getCoordinates(),
                              zoom : 10
                          });
                          myMap.geoObjects.add(new ymaps.Placemark(res.geoObjects.get(0).geometry.getCoordinates(), {
                              balloonContent: ''
                          }));
                      });
                    },1000);
                  <?php } ?>
                </script>
          <?php } ?>
        </div>
        <?php } ?>
        <!-- postMap -->

        <!-- fetched_url -->
         <?php include 'fetched_url.phtml'; ?>
        <!-- fetched_url -->

        <!-- event -->
         <?php include 'event.phtml'; ?>
        <!-- event -->

        <!-- blog -->
         <?php include 'blog.phtml'; ?>
        <!-- blog -->

        <!-- forum -->
         <?php include 'forum.phtml'; ?>
        <!-- forum -->

        <!-- thread -->
         <?php include 'thread.phtml'; ?>
        <!-- thread -->
        <!-- offer -->
         <?php
         if (!empty($tsx['story']['offer']) && !empty($tsx['story']['offer_id'])) {
           include 'offer.phtml';
         }
        ?>
        <!-- offer -->

        <!-- postFile -->
        <?php if(!empty($tsx['story']['postFile'])) { ?>

        <div class="post-file tsx_shared_doc_file" id="fullsizeimg">
          <!-- <div style="width: 100%;height: 100%;position: absolute;background-color: rgba(0,0,0,0.3);filter: blur(5px);"></div> -->
            <?php
            $media = array(
                'type' => 'post',
                'storyId' => $tsx['story']['id'],
                'filename' => $tsx['story']['postFile'],
                'name' => $tsx['story']['postFileName'],
                'postFileThumb' => $tsx['story']['postFileThumb'],
            );
            echo tsx_DisplaySharedFile($media, '', $tsx['story']['cache']);
            ?>
        </div>

        <?php } ?>
        <!-- postFile -->

        <!-- postSticker -->
        <?php if (tsx_IsUrl($tsx['story']['postSticker'])): ?>
          <div class="post-file tsx_video_post">
            <?php if (strpos('.mp4', $tsx['story']['postSticker'])) { ?>
            <video autoplay loop><source src="<?php echo $tsx['story']['postSticker']; ?>" type="video/mp4"></video>
            <?php } else { ?>
            <img src="<?php echo $tsx['story']['postSticker']; ?>" alt="GIF">
            <?php } ?>
          </div>
        <?php endif; ?>
        <!-- postSticker -->

        <!-- postPhoto -->
        <?php if (tsx_IsUrl($tsx['story']['postPhoto'])): ?>
          <div class="post-file" id="fullsizeimg">
            <img src="<?php echo $tsx['story']['postPhoto']; ?>" alt="Picture">
          </div>
        <?php endif; ?>
        <!-- postPhoto -->

        <!-- postRecord -->
        <?php if(!empty($tsx['story']['postRecord'])) { ?>
        <div class="post-file">
            <?php
              $media = array(
                'type' => 'post',
                'storyId' => $tsx['story']['id'],
                'filename' => $tsx['story']['postRecord'],
                'name' => ''
              );
              echo  tsx_DisplaySharedFile($media,'record');
            ?>
        </div>
        <?php } ?>

        <!-- Live Video -->
        <?php if (!empty($tsx['story']['stream_name']) && empty($tsx['story']['agora_resource_id']) && empty($tsx['story']['agora_token']) && empty($tsx['story']['agora_sid']) && !$tsx['story']['is_still_live']) { ?>
          <div class="post-file" <?php echo $tsx['story']['is_still_live'] ? 'style="/*height: 440px;*/"' : ''; ?> id="fullsizeimg">
            <?php
            $tsx['media'] = array('filename' => 'https://viewer.millicast.com/v2?streamId='.$tsx['config']['live_account_id'].'/'.$tsx['story']['stream_name']);
          $media = array(
             'type' => 'post',
             'storyId' => $tsx['story']['id'],
             'filename' => 'https://viewer.millicast.com/v2?streamId='.$tsx['config']['live_account_id'].'/'.$tsx['story']['stream_name'],
             'name' => $tsx['story']['postFileName'],
             'postFileThumb' => $tsx['story']['postFileThumb'],
           );
           echo tsx_DisplaySharedFile($media, '', $tsx['story']['cache'],true); ?>
          </div>

         <?php } ?>
        <?php if ($tsx['config']['live_video'] == 1 && !empty($tsx['story']['stream_name'])) { ?>
			<div class="post-file" <?php echo $tsx['story']['is_still_live'] ? 'style="/*height: 440px;*/"' : ''; ?> id="fullsizeimg">
				<?php
        if ($tsx['config']['millicast_live_video'] == 1) {
         if ($tsx['story']['is_still_live']) { ?>
					<div class="embed-responsive embed-responsive-4by3">
            <iframe src="https://viewer.millicast.com/v2?streamId=<?php echo($tsx['config']['live_account_id']) ?>/<?php echo($tsx['story']['stream_name']) ?>" class="embed-responsive-item"></iframe>
						<div class="joinda_liv_counter"><span id="live_tsxrd_<?php echo($tsx['story']['id']) ?>"><?php echo $tsx['lang']['live']; ?></span> <span id="live_count_<?php echo($tsx['story']['id']) ?>"> <?php echo $tsx['story']['live_sub_users']; ?></span></div>
					</div>
          <?php if ($tsx['page'] != 'story') { ?>
          <a href="<?php echo $tsx['story']['url'];?>" target="_blank" class="live_link_style live_link_<?php echo($tsx['story']['id']) ?>"></a>
          <?php } ?>
					<?php if ( $tsx['story']['comments_status'] == 1) { ?>
						<div id="live_post_comments_<?php echo($tsx['story']['id']) ?>" class="joinda_liv_comments_feed">
							<?php if (!empty($tsx['story']['get_post_comments'])) {
								$count = 0;
								for ($i=count($tsx['story']['get_post_comments'])-1; $i >= 0 ; $i--){
									$tsx['comment'] = $tsx['story']['get_post_comments'][$i];
									if (!empty($tsx['comment']['text'])) {
										echo tsx_LoadPage('story/includes/live_comment');
										$count = $count + 1;
										if ($count == 4) {
											break;
										}
									}
								}
							}
							?>
						</div>
					<?php } ?>
				<?php } ?>
          <?php
        }
        elseif ($tsx['config']['agora_live_video'] == 1) {
          if ($tsx['story']['is_still_live']) { ?>
            <div class="embed-responsive embed-responsive-4by3" id="post_live_video_<?php echo($tsx['story']['id']) ?>">
            <div class="joinda_liv_counter"><span id="live_tsxrd_<?php echo($tsx['story']['id']) ?>"><?php echo $tsx['lang']['live']; ?></span> <span id="live_count_<?php echo($tsx['story']['id']) ?>"> <?php echo $tsx['story']['live_sub_users']; ?></span></div>
          </div>
          <?php if ($tsx['page'] != 'story') { ?>
          <a href="<?php echo $tsx['story']['url'];?>" target="_blank" class="live_link_style live_link_<?php echo($tsx['story']['id']) ?>"></a>
          <?php } ?>
          <?php if ( $tsx['story']['comments_status'] == 1) { ?>
            <div id="live_post_comments_<?php echo($tsx['story']['id']) ?>" class="joinda_liv_comments_feed">
              <?php if (!empty($tsx['story']['get_post_comments'])) {
                $count = 0;
                for ($i=count($tsx['story']['get_post_comments'])-1; $i >= 0 ; $i--){
                  $tsx['comment'] = $tsx['story']['get_post_comments'][$i];
                  if (!empty($tsx['comment']['text'])) {
                    echo tsx_LoadPage('story/includes/live_comment');
                    $count = $count + 1;
                    if ($count == 4) {
                      break;
                    }
                  }
                }
              }
              ?>
            </div>
          <?php }
          }
        }
				?>
			</div>
        <?php } ?>

        <div id="fullsizeimg" style="position: relative;">
          <!-- photo_album -->
            <?php include 'photo_album.phtml'; ?>
          <!-- photo_album -->


          <!-- multi_image -->
            <?php include 'photo_multi.phtml'; ?>
          <!-- multi_image -->

        <div class="clear"></div>
        </div>
        <!-- poll -->
        <?php
        if ($tsx['story']['poll_id'] == 1) {
           echo tsx_LoadPage('story/entries/options');
        }
        ?>
        <!-- poll -->
         <?php } ?>
        <div class="clear"></div>
        <!-- footer -->
         <?php include 'footer.phtml'; ?>
        <!-- footer -->

      <?php
        if ($tsx['loggedin'] == true) {
            echo tsx_LoadPage('modals/edit-post');
            echo tsx_LoadPage('modals/delete-post');
        }
        ?>
    </div>
  </div>
</div>

<script type="text/javascript">
$(function () {
  <?php if (!empty($tsx['story']['product_id'])): ?>
  ReadMoreText("#post-<?php echo $tsx['story']['id']; ?> .product-description-<?php echo $tsx['story']['product_id']; ?>");
  <?php endif; ?>
  ReadMoreText("#post-<?php echo $tsx['story']['id']; ?> .post-description p");
    $("#post-<?php echo $tsx['story']['id']; ?> .textarea").triggeredAutocomplete({
       hidden: '#hidden_inputbox_comment',
       source: tsx_Ajax_Requests_File() + "?f=mention",
       trigger: "@"
    });
    $('[data-toggle="tooltip"]').tooltip();
    $('.dropdown-menu.post-recipient, .dropdown-menu.post-options, .tsx_emoji_post').click(function (e) {
      e.stopPropagation();
    });
});

jQuery(document).click(function(event){
    if (!(jQuery(event.target).closest(".remove_combo_on_click").length)) {
        jQuery('.remove_combo_on_click').removeClass('comment-toggle');
		$('#gif-form-<?php echo $tsx['story']['id']; ?>').slideUp(200);
		$('#sticker-form-<?php echo $tsx['story']['id']; ?>').slideUp(200);
    }
});
<?php if ($tsx['config']['live_video'] == 1 && !empty($tsx['story']['stream_name']) && $tsx['story']['is_still_live'] && $tsx['story']['comments_status'] == 1 && $tsx['story']['live_ended'] == 0) { ?>
  var post_live_<?php echo $tsx['story']['id']; ?> = setInterval(function(){
      data = {};
      for (var i = 0; i < $('.live_comments').length; i++) {
        if ($($('.live_comments')[i]).attr('live_comment_id')) {
          data[i] = $($('.live_comments')[i]).attr('live_comment_id');
        }
      }
      $.post(tsx_Ajax_Requests_File() + "?f=live&s=check_comments", {post_id: <?php echo $tsx['story']['id']; ?>,ids:data,page:"<?php echo($tsx['page']) ?>"}, function(data, textStatus, xhr) {
        if (data.status == 200) {
          if (data.still_live == 'offline') {
            $('#live_post_comments_<?php echo $tsx['story']['id']; ?>').remove();
            $('.was_live_text_<?php echo $tsx['story']['id']; ?>').html("<?php echo($tsx['lang']['was_live']) ?>");
            $('[id=post-<?php echo $tsx['story']['id']; ?>]').find('.comment-textarea').attr('disabled');
            return false;
          }
          $('#live_post_comments_<?php echo $tsx['story']['id']; ?>').append(data.html);
          $('#live_count_<?php echo $tsx['story']['id']; ?>').html(data.count);
          $('#live_tsxrd_<?php echo $tsx['story']['id']; ?>').html(data.tsxrd);
          var comments = $('#live_post_comments_<?php echo $tsx['story']['id']; ?> .live_comments');
          if (comments.length > 4) {
            var i;
            for (i = 0; i < comments.length; i++) {
              if ($('#live_post_comments_<?php echo $tsx['story']['id']; ?> .live_comments').length > 4) {
                comments[i].remove();
              }
            }
          }
        }
        else if(data.removed == 'yes'){
            clearInterval(post_live_<?php echo $tsx['story']['id']; ?>);
            $('#live_count_<?php echo $tsx['story']['id']; ?>').html(0);
            $('#live_post_comments_<?php echo $tsx['story']['id']; ?>').html("<h3 class='end_video_text'><?php echo(str_replace('{{user}}', $tsx['story']['publisher']['username'], $tsx['lang']['stream_has_ended'])) ?></h3>");
            /*$('#live_post_comments_<?php echo $tsx['story']['id']; ?>').remove();*/
            $('.was_live_text_<?php echo $tsx['story']['id']; ?>').html("<?php echo($tsx['lang']['was_live']) ?>");
            $('#post-<?php echo $tsx['story']['id']; ?>').find('.comment-textarea').attr('disabled','true');
            $('#post-comments-<?php echo $tsx['story']['id']; ?>').remove();
            return false;
        }
        else{
            clearInterval(post_live_<?php echo $tsx['story']['id']; ?>);
            $('#live_count_<?php echo $tsx['story']['id']; ?>').html(0);
            $('#live_post_comments_<?php echo $tsx['story']['id']; ?>').html("<h3 class='end_video_text'><?php echo(str_replace('{{user}}', $tsx['story']['publisher']['username'], $tsx['lang']['stream_has_ended'])) ?></h3>");
            /*$('#live_post_comments_<?php echo $tsx['story']['id']; ?>').remove();*/
            $('.was_live_text_<?php echo $tsx['story']['id']; ?>').html("<?php echo($tsx['lang']['was_live']) ?>");
            $('#post-<?php echo $tsx['story']['id']; ?>').find('.comment-textarea').attr('disabled','true');
            $('#post-comments-<?php echo $tsx['story']['id']; ?>').remove();
            return false;
        }
      });
   }, 3000);

<?php } ?>
<?php if ($tsx['config']['agora_live_video'] == 1 && !empty($tsx['config']['agora_app_id']) && !empty($tsx['story']['stream_name']) && $tsx['story']['is_still_live']) { ?>
  RunLiveAgora("<?php echo $tsx['story']['stream_name']; ?>","post_live_video_<?php echo($tsx['story']['id']) ?>","<?php echo($tsx['story']['agora_token']) ?>");

<?php } ?>

</script>
