<style>
	.tsx_post_prod_full_related_prnt {
    padding: 20px 10px 20px;
}
.col-md-3, .col-sm-4, .col-xs-6{
    padding-right: 10px;
    padding-left: 10px;
}
.joinda_content {
    position: sticky;
    top: 7rem;
}
.tsx_post_prod_full_info {
    margin-bottom: 24px;
}
</style>

<?php
	$symbol =  (!empty($tsx['currencies'][$tsx['story']['product']['currency']]['symbol'])) ? $tsx['currencies'][$tsx['story']['product']['currency']]['symbol'] : $tsx['config']['classified_currency_s'];
	$text =  (!empty($tsx['currencies'][$tsx['story']['product']['currency']]['text'])) ? $tsx['currencies'][$tsx['story']['product']['currency']]['text'] : $tsx['config']['classified_currency'];
	$status = '<span class="product-description">' . $tsx['lang']['currently_unavailable'] . '</span>';
    if ($tsx['story']['product']['units'] > 0) {
      $status = ($tsx['story']['product']['status'] == 0) ? '' . $tsx['lang']['in_stock'] . '' : '<span class="product-status-sold">' . $tsx['lang']['sold'] . '</span><br><br>';
    }
	$type = ($tsx['story']['product']['type'] == 0) ? '' . $tsx['lang']['new'] . '' : '' . $tsx['lang']['used'] . '';
?>
<div class="page-margin">
	<div class="row setting-panel" style="position:relative;">
		<div class="col-md-8 sett_page mobile-noPad" id="tsx_main_sett_side">
			<div class="tsx_post_prod_full_img">
				<?php
					foreach ($tsx['story']['product']['images'] as $photo) {
						echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='image-file pointer' onclick='tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");'>";
					}
				?>
			</div>
			<div class="tsx_post_prod_full_img_slider">
				<?php
					foreach ($tsx['story']['product']['images'] as $photo) {
						echo  "<div><img src='" . ($photo['image_org']) ."' alt='image' class='active pointer'></div>";
					}
				?>
			</div>
			<div class="page-margin joinda_content tsx_post_prod_full_related_prnt">
				<?php
					$data['limit'] = 10;
					$products = tsx_GetProducts($data);
					if (count($products) > 0) {
				?>
				<div class="row">
					<?php
						foreach ($products as $key => $tsx['product']) {
							echo tsx_LoadPage('products/full-product-related-list'); 
						}
						} else {
							echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,13A5,5 0 0,1 7,8H9A3,3 0 0,0 12,11A3,3 0 0,0 15,8H17A5,5 0 0,1 12,13M12,3A3,3 0 0,1 15,6H9A3,3 0 0,1 12,3M19,6H17A5,5 0 0,0 12,1A5,5 0 0,0 7,6H5C3.89,6 3,6.89 3,8V20A2,2 0 0,0 5,22H19A2,2 0 0,0 21,20V8C21,6.89 20.1,6 19,6Z"></path></svg>' . $tsx['lang']['no_available_products'] . '</div>';
						}
					?>
				</div>
			</div>
		</div>
		<div class="col-md-4 sidebar sett_page joinda_content" id="tsx_main_sett_mid">
		<h4 class="tsx_post_prod_full_name"><?php echo $tsx['story']['product']['name'] ?></h4>
			
			<div class="product-priceLocation">
				<div class="priceLocation-price">
					<?php echo '<div class="tsx_post_prod_full_price">' . $symbol . $tsx['story']['product']['price_format'] . ' (' . $text . ')</div>';?>
				</div>
				<div class="priceLocation-location">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" /></svg>
					<?php echo $tsx['story']['product']['location'] ?>
				</div>
				
			</div>
			
			<?php
				$stars = '0';
				if (!empty($tsx['story']['product']['rating']) && is_numeric($tsx['story']['product']['rating'])) {
					$stars = $tsx['story']['product']['rating'];
				}
			?>
			<?php if ($tsx['config']['store_system'] == 'on') { ?>
				<div class="pr_stars tsx_post_prod_full_stars" data-stars="<?php echo $stars; ?>">
					<svg class="star rating" viewBox="0 0 24 24" data-rating="1"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<svg class="star rating" viewBox="0 0 24 24" data-rating="2"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<svg class="star rating" viewBox="0 0 24 24" data-rating="3"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<svg class="star rating" viewBox="0 0 24 24" data-rating="4"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<svg class="star rating" viewBox="0 0 24 24" data-rating="5"><path d="M6.516,14.323l-1.49,6.452c-0.092,0.399,0.068,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22 c0.193,0,0.387-0.056,0.555-0.168L12,18.202l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082 l-1.829-6.4l4.536-4.082c0.297-0.268,0.406-0.686,0.278-1.064c-0.129-0.378-0.47-0.644-0.868-0.676L15.378,8.05l-2.467-5.461 C12.75,2.23,12.393,2,12,2s-0.75,0.23-0.911,0.589L8.622,8.05L2.921,8.503C2.529,8.534,2.192,8.791,2.06,9.16 c-0.134,0.369-0.038,0.782,0.242,1.056L6.516,14.323z"></path></svg>
					<span onclick="ShowProductReviews('<?php echo $tsx['story']['product']['id'] ?>')" class="pointer"><?php echo $tsx['story']['product']['reviews_count'] ?> <?php echo $tsx['lang']['reviews']; ?></span>
				</div>
			<?php } ?>
			
			<div class="tsx_post_prod_full_user">
				<a href="<?php echo $tsx['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $tsx['story']['publisher']['username']?>" class="avatar joinda_post_usr_ava">
					<img src="<?php echo $tsx['story']['publisher']['avatar']; ?>" alt="<?php echo $tsx['story']['publisher']['name']; ?> profile picture">
				</a>&nbsp;&nbsp;
				<h5 class="user-popover" data-type="<?php echo $tsx['story']['publisher']['type']; ?>" data-id="<?php echo $tsx['story']['publisher']['id']; ?>">
					<b><?php echo $tsx['lang']['published']; ?> <?php echo $tsx['lang']['by']; ?></b>
					<a href="<?php echo $tsx['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $tsx['story']['publisher']['username']; ?>"><?php echo $tsx['story']['publisher']['name']; ?></a>
				</h5>
		   </div>
			
			<?php if ($tsx['loggedin']) { if ($tsx['page']  == 'story' && $tsx['story']['product']['user_id'] != $tsx['user']['user_id']) { ?>
				<div class="tsx_store_post_btns tsx_post_prod_full_btns">
					<button class="contact btn btn-default btn-mat" onclick="tsx_OpenChatTab(<?php echo $tsx['story']['product']['user_id']?>,0,<?php echo $tsx['story']['product']['id']?>)">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20,2H4A2,2 0 0,0 2,4V22L6,18H20A2,2 0 0,0 22,16V4A2,2 0 0,0 20,2M6,9H18V11H6M14,14H6V12H14M18,8H6V6H18" /></svg> <?php echo $tsx['lang']['contact_seller'] ?>
					</button> 
					<?php if ($tsx['config']['store_system'] == 'on') { ?>
						<?php if (!empty($tsx['story']['product']['units']) && $tsx['story']['product']['units'] > 0) { ?>
							&nbsp;&nbsp;<button class="contact btn btn-main btn-mat" onclick="AddProductToCart(this,'<?php echo($tsx['story']['product']['id']); ?>','add')">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,18C15.89,18 15,18.89 15,20A2,2 0 0,0 17,22A2,2 0 0,0 19,20C19,18.89 18.1,18 17,18M1,2V4H3L6.6,11.59L5.24,14.04C5.09,14.32 5,14.65 5,15A2,2 0 0,0 7,17H19V15H7.42A0.25,0.25 0 0,1 7.17,14.75C7.17,14.7 7.18,14.66 7.2,14.63L8.1,13H15.55C16.3,13 16.96,12.58 17.3,11.97L20.88,5.5C20.95,5.34 21,5.17 21,5A1,1 0 0,0 20,4H5.21L4.27,2M7,18C5.89,18 5,18.89 5,20A2,2 0 0,0 7,22A2,2 0 0,0 9,20C9,18.89 8.1,18 7,18Z" /></svg> <?php echo($tsx['lang']['buy_now']) ?>
							</button>
						<?php }else{ ?>
							&nbsp;&nbsp;<p><?php echo($tsx['lang']['currently_unavailable']) ?></p>
						<?php } ?> 
					<?php } ?>
				</div>
			<?php } else { ?> 
				<div class="tsx_store_post_btns">
					<a class="btn btn-default btn-mat" style="width: 100%;" href="<?php echo tsx_SeoLink('index.php?link1=edit-product&id=' . $tsx['story']['product_id']);?>">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z" /></svg> <?php echo $tsx['lang']['edit_product']?>
					</a>
				</div>
			<?php } } ?>

			<div class="tsx_page_hdng_innr big_size"><?php echo $tsx['lang']['details']?></div>
			<ul class="joinda_post_prod_shead tsx_post_prod_full_info">
				<?php 
					echo '<li><span style="margin-right: 8px;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M21,16.5C21,16.88 20.79,17.21 20.47,17.38L12.57,21.82C12.41,21.94 12.21,22 12,22C11.79,22 11.59,21.94 11.43,21.82L3.53,17.38C3.21,17.21 3,16.88 3,16.5V7.5C3,7.12 3.21,6.79 3.53,6.62L11.43,2.18C11.59,2.06 11.79,2 12,2C12.21,2 12.41,2.06 12.57,2.18L20.47,6.62C20.79,6.79 21,7.12 21,7.5V16.5M12,4.15L10.11,5.22L16,8.61L17.96,7.5L12,4.15M6.04,7.5L12,10.85L13.96,9.75L8.08,6.35L6.04,7.5M5,15.91L11,19.29V12.58L5,9.21V15.91M19,15.91V9.21L13,12.58V19.29L19,15.91Z" /></svg></span><span>' . $status . '</span></li>';
				?>
				<?php 
					echo '<li><span style="margin-right: 14px;"><svg style="margin-right: 4px;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M5.5,7A1.5,1.5 0 0,1 4,5.5A1.5,1.5 0 0,1 5.5,4A1.5,1.5 0 0,1 7,5.5A1.5,1.5 0 0,1 5.5,7M21.41,11.58L12.41,2.58C12.05,2.22 11.55,2 11,2H4C2.89,2 2,2.89 2,4V11C2,11.55 2.22,12.05 2.59,12.41L11.58,21.41C11.95,21.77 12.45,22 13,22C13.55,22 14.05,21.77 14.41,21.41L21.41,14.41C21.78,14.05 22,13.55 22,13C22,12.44 21.77,11.94 21.41,11.58Z" /></svg>&nbsp;' . $tsx['lang']['type'] . '</span><span>' . $type . '</span></li>';
				?>
			</ul>
			<p><?php echo $tsx['story']['product']['description'] ?></p>
			
			<?php
				$fields = tsx_GetCustomFields('product');
				if (!empty($fields)) {
					foreach ($fields as $key => $tsx['field']) { 
						if (!empty($tsx['story']['product']['fid_'.$tsx['field']['id']])) {
							if ($tsx['field']['type'] == 'selectbox') {
								$options = @explode(',', $tsx['field']['options']);
								foreach ($options as $key => $value) {
									if (($key + 1) == $tsx['story']['product']['fid_'.$tsx['field']['id']]) {
										$tsx['story']['product']['fid_'.$tsx['field']['id']] = $value;
									}
								}
							}
							echo '<div class="joinda_post_prod_infos"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" /></svg><p class="product-description">' . $tsx['story']['product']['fid_'.$tsx['field']['id']] . '</p></div>';
						} 
					} 
				} 
			?>
		</div>
	</div>
</div>

<script>
// 1st carousel, main
$('.tsx_post_prod_full_img').flickity({
	pageDots: false,
	draggable: false
});
// 2nd carousel, navigation
$('.tsx_post_prod_full_img_slider').flickity({
	asNavFor: '.tsx_post_prod_full_img',
	contain: true,
	pageDots: false,
	prevNextButtons: false,
});
</script>