<?php if (!empty($tsx['story']['parent_id'])) {
   $post_shared_from = tsx_PostData($tsx['story']['parent_id']);
   $tsx['story'] = $post_shared_from;
   if (!empty($tsx['story']['fund_raise_id'])) {
    $tsx['story']['fund'] = GetFundByRaiseId($tsx['story']['fund_raise_id'],$tsx['story']['user_id']);
   }
   if (!empty($tsx['story']['fund_id'])) {
      $tsx['story']['fund_data'] = GetFundingById($tsx['story']['fund_id']);
    }
    if ($tsx['config']['shout_box_system'] == 1 && $tsx['story']['postPrivacy'] == 4) {
      $anonymous = true;
       $tsx['story']['publisher']['username'] = 'anonymous';
       $tsx['story']['publisher']['name'] = $tsx['lang']['anonymous'];
       $tsx['story']['publisher']['avatar'] = tsx_GetMedia('upload/photos/incognito.png');
       $tsx['story']['publisher']['verified'] = 0;
       $tsx['story']['publisher']['type'] = '';
       $tsx['story']['publisher']['url'] = 'javascript:void(0)';
    }
   
   ?>
<div>
   <div class="clear"></div>
   <div class="bs-callout bs-callout-default joinda_shared_posts">
      <div class="post-heading">
         <div class="<?php echo tsx_RightToLeft('pull-left');?> image">
          <?php if (!isset($anonymous)) { ?>
            <a href="<?php echo $tsx['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $tsx['story']['publisher']['username']?>">
            <img src="<?php echo $tsx['story']['publisher']['avatar']; ?>" id="updateImage-<?php echo $tsx['story']['publisher']['user_id']?>" class="avatar" alt="<?php echo $tsx['story']['publisher']['name']; ?> profile picture" style="width: 40px;height: 40px;">
            </a>
          <?php }else{ ?>
            <img src="<?php echo $tsx['story']['publisher']['avatar']; ?>" id="updateImage-<?php echo $tsx['story']['publisher']['user_id']?>" class="avatar" alt="<?php echo $tsx['story']['publisher']['name']; ?> profile picture" style="width: 40px;height: 40px;">
          <?php } ?>
         </div>
         <div class="title h5" style="margin-bottom: 0;margin-top: 4px;">
          <?php if (!isset($anonymous)) { ?>
            <span class="user-popover" data-type="<?php echo $tsx['story']['publisher']['type']; ?>" data-id="<?php echo $tsx['story']['publisher']['id']; ?>">
               <a class="main-color" href="<?php echo $tsx['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $tsx['story']['publisher']['username']; ?>">
               <b style="margin-right:0px;"><?php echo $tsx['story']['publisher']['name']; ?></b>
               </a>
               <?php if($tsx['story']['publisher']['verified'] == 1) { ?>
               <span class="verified-color">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $tsx['lang']['verified_user'];?>" data-toggle="tooltip">
                     <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" />
                  </svg>
               </span>
               <?php } ?>
            </span>
          <?php }else{ ?>
            <b style="margin-right:0px;"><?php echo $tsx['story']['publisher']['name']; ?></b>
            <?php } ?>
            <?php if ($tsx['story']['recipient_exists'] == true) {  ?>
            <?php echo $tsx['lang']['to']; ?>
            <span class="user-popover" data-type="<?php echo $tsx['story']['recipient']['type']; ?>" data-id='<?php echo $tsx['story']['recipient']['id']; ?>'>
               <a href="<?php echo $tsx['story']['recipient']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $tsx['story']['recipient']['username']; ?>">
               <b>
               <?php echo $tsx['story']['recipient']['name']; ?>
               </b>
               </a>
               <?php if($tsx['story']['recipient']['verified'] == 1) { ?> 
               <span class="verified-color">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $tsx['lang']['verified_user'];?>" data-toggle="tooltip">
                     <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" />
                  </svg>
               </span>
               <?php } ?>
            </span>
            <?php } ?>
            <?php if (!empty($tsx['story']['page_event_id'])) {?>
            <small class="small-text"> <?php echo $tsx['lang']['created_new_event'] ?></small>
            <?php } ?>
            <?php if (!empty($tsx['story']['fund_id']) && empty($tsx['story']['parent_id'])) {?>
         <small class="small-text"> <?php echo $tsx['lang']['created_donation_request'] ?></small>
         <?php } ?>
         <?php if (!empty($tsx['story']['fund_raise_id']) && empty($tsx['story']['parent_id'])) {?>
         <small class="small-text"> <?php echo $tsx['lang']['donated_to_request'] ?></small>
         <?php } ?>
         <?php if (!empty($tsx['story']['offer_id']) && empty($tsx['story']['parent_id'])) {?>
         <small class="small-text"> <?php echo $tsx['lang']['created_offer'] ?></small>
         <?php } ?>
            <?php if (!empty($tsx['story']['event_id']) && $tsx['page'] != 'events') {  ?>
            <i class="fa fa-arrow-right"></i> <a href="<?php echo $tsx['story']['event']['url']; ?>" data-ajax="?link1=show-event&eid=<?php echo $tsx['story']['event']['id']; ?>"><b><?php echo $tsx['story']['event']['name']; ?></b></a>
            <?php } ?>
            <?php if ($tsx['story']['group_recipient_exists'] == true && $tsx['page'] != 'group') {  ?>
            <?php echo $tsx['lang']['to']; ?>
            <span class="user-popover" data-type="<?php echo $tsx['story']['group_recipient']['type']; ?>" data-id='<?php echo $tsx['story']['group_recipient']['id']; ?>'>
            <a href="<?php echo $tsx['story']['group_recipient']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $tsx['story']['group_recipient']['username']; ?>">
            <b><?php echo $tsx['story']['group_recipient']['name']; ?></b>
            </a>
            </span>
            <?php } ?>
            <?php if (!empty($tsx['story']['album_name']) && empty($tsx['story']['shared_from'])) {  ?>
            <small class="small-text"><?php echo $tsx['lang']['added_new_photos_to'];?> <b><a href="<?php echo $tsx['story']['url']; ?>" data-ajax="?link1=post&id=<?php echo $tsx['story']['id'];?>"><?php echo $tsx['story']['album_name']; ?></a></b></small>
            <?php } ?>
            <?php if (!empty($tsx['story']['product_id']) && empty($tsx['story']['shared_from'])) {  ?>
            <small class="small-text"><?php echo $tsx['lang']['added_new_product_for_sell']; ?></small>
            <?php } ?>
            <?php if (!empty($tsx['story']['blog_id'])  && empty($tsx['story']['shared_from'])) {  ?>
            <small class="small-text"><?php echo $tsx['lang']['created_new_blog'] ?></small>
            <?php } ?>
            <?php if (!empty($tsx['story']['forum_id'])  && empty($tsx['story']['shared_from']) && !empty($tsx['story']['forum'])) {  ?>
           <small class="small-text"><?php echo $tsx['lang']['shared_forum'] ?></small>
           <?php } ?>
           <?php if (!empty($tsx['story']['thread_id'])  && empty($tsx['story']['shared_from']) && !empty($tsx['story']['thread'])) {  ?>
         <small class="small-text"><?php echo $tsx['lang']['shared_thread'] ?></small>
         <?php } ?>
         <?php if ($tsx['config']['live_video'] == 1 && !empty($tsx['story']['stream_name'])) { ?>
         <span><span style="color: #666;" class="was_live_text_<?php echo($tsx['story']['id']) ?>"><?php echo ($tsx['story']['is_still_live'] ? $tsx['lang']['is_live'] : $tsx['lang']['was_live']); ?></span></span>
      <?php } ?>
            <?php if (empty($tsx['story']['shared_from'])): ?>
            <small class="small-text">
            <?php 
               if($tsx['story']['postType'] == 'profile_picture') { 
                  $changed_profile_pic_lang = $tsx['lang']['changed_profile_picture_male'];
                  if ($tsx['story']['publisher']['gender'] == 'female') {
                     $changed_profile_pic_lang = $tsx['lang']['changed_profile_picture_female'];
                  } else {
                     $changed_profile_pic_lang = $tsx['lang']['changed_profile_picture_male'];
                  }
                  echo $changed_profile_pic_lang;
               } 
               if($tsx['story']['postType'] == 'profile_cover_picture') { 
                  $changed_profile_cover_pic_lang = $tsx['lang']['changed_profile_cover_picture_male'];
                  if ($tsx['story']['publisher']['gender'] == 'female') {
                     $changed_profile_cover_pic_lang = $tsx['lang']['changed_profile_cover_picture_female'];
                  } else {
                     $changed_profile_cover_pic_lang = $tsx['lang']['changed_profile_cover_picture_male'];
                  }
                  echo $changed_profile_cover_pic_lang;
               } 
               ?>
            </small>
            <?php endif; ?>
            <?php if($tsx['story']['via_type'] == 'share') {  ?>
            <small style="color:#a33e40;"><?php echo $tsx['story']['via']['name'];?> <?php echo $tsx['lang']['shared_this_post'];?></small>
            <?php }  ?>
            <?php 
               $extra_exists = 0;
               if (!empty($tsx['story']['postFeeling'])) {
                 if (empty($changed_profile_pic_lang) 
                   && $tsx['story']['via_type'] != 'share'
                   && $tsx['story']['group_recipient_exists'] != true
                   && empty($tsx['story']['album_name'])) {
               ?>
            <span class="feeling-text"> <?php echo $tsx['lang']['is_feeling'];?> <i class="twa-lg twa twa-<?php echo $tsx['story']['postFeelingIcon'];?>"></i> <?php echo $tsx['lang'][$tsx['story']['postFeeling']];?></span>
            <?php
               } else {
                 $extra_exists = 1;
               }
               }
               if (!empty($tsx['story']['postTraveling'])) {
                 if (empty($changed_profile_pic_lang) 
                   && $tsx['story']['via_type'] != 'share'
                   && $tsx['story']['group_recipient_exists'] != true
                   && empty($tsx['story']['album_name'])) {
               ?>
            <span class="feeling-text"><i class="fa fa-plane"></i> <?php echo $tsx['lang']['is_traveling'];?> <?php echo $tsx['story']['postTraveling'];?></span>
            <?php
               } else {
                 $extra_exists = 1;
               }
               }
               if (!empty($tsx['story']['postListening'])) {
                 if (empty($changed_profile_pic_lang) 
                   && $tsx['story']['via_type'] != 'share'
                   && $tsx['story']['group_recipient_exists'] != true
                   && empty($tsx['story']['album_name'])) {
               ?>
            <span class="feeling-text"><i class="fa fa-headphones"></i> <?php echo $tsx['lang']['is_listening'];?> <?php echo $tsx['story']['postListening'];?></span>
            <?php
               } else {
                 $extra_exists = 1;
               }
               }
               if (!empty($tsx['story']['postPlaying'])) {
                 if (empty($changed_profile_pic_lang) 
                   && $tsx['story']['via_type'] != 'share'
                   && $tsx['story']['group_recipient_exists'] != true
                   && empty($tsx['story']['album_name'])) {
               ?>
            <span class="feeling-text"><i class="fa fa-gamepad"></i> <?php echo $tsx['lang']['is_playing'];?> <?php echo $tsx['story']['postPlaying'];?></span>
            <?php
               } else {
                 $extra_exists = 1;
               }
               }
               if (!empty($tsx['story']['postWatching'])) {
                 if (empty($changed_profile_pic_lang) 
                   && $tsx['story']['via_type'] != 'share'
                   && $tsx['story']['group_recipient_exists'] != true
                   && empty($tsx['story']['album_name'])) {
               ?>
            <span class="feeling-text"><i class="fa fa-eye"></i> <?php echo $tsx['lang']['is_watching'];?> <?php echo $tsx['story']['postWatching'];?></span>
            <?php
               } else {
                 $extra_exists = 1;
               }
               }
               ?>
         </div>
         <h6>
            <span class="time">
            <a  style="color:#9197a3" class="ajax-time" href="<?php echo $tsx['story']['url'];?>" title="<?php echo date('c',$tsx['story']['time']); ?>" target="_blank"><?php echo tsx_Time_Elapsed_String($tsx['story']['time']); ?></a>
            </span>
         </h6>
      </div>
      <div>
        <?php if (empty($tsx['story']['color_id']) || (!empty($tsx['story']['color_id']) && empty($tsx['post_colors'][$tsx['story']['color_id']]))) { ?>
         <p class="joinda_shared_posts_p"><?php echo $tsx['story']['postText']; ?></p>
         <?php } ?>
         <?php if (!empty($tsx['story']['color_id']) && !empty($tsx['post_colors'][$tsx['story']['color_id']])) { ?>
    <div dir="auto" 
    <?php if($tsx['config']['colored_posts_system'] == 1){ ?>
      class="tsx_actual_colrd_post" style="
      <?php if (!empty($tsx['post_colors'][$tsx['story']['color_id']]) && !empty($tsx['post_colors'][$tsx['story']['color_id']]->color_1) && !empty($tsx['post_colors'][$tsx['story']['color_id']]->color_2) && !empty($tsx['post_colors'][$tsx['story']['color_id']]->text_color)) { ?>
        background-image: linear-gradient(45deg, <?php echo $tsx['post_colors'][$tsx['story']['color_id']]->color_1; ?> 0%, <?php echo $tsx['post_colors'][$tsx['story']['color_id']]->color_2; ?> 100%);margin: 10px 0 0;
      <?php }else{ ?>
        background-image:url('<?php echo tsx_GetMedia($tsx['post_colors'][$tsx['story']['color_id']]->image); ?>');margin: 10px 0 0; <?php } ?>
      <?php if(strlen($tsx['story']['postText']) > 330){ ?>font-size: 16px;font-weight: normal;<?php } ?>"
    <?php } ?>
  >
  <span <?php if($tsx['config']['colored_posts_system'] == 1){ ?> style="<?php if (!empty($tsx['post_colors'][$tsx['story']['color_id']]) && !empty($tsx['post_colors'][$tsx['story']['color_id']]->text_color)) { ?>color:<?php echo $tsx['post_colors'][$tsx['story']['color_id']]->text_color; ?><?php } ?>"<?php } ?>> <?php echo $tsx['story']['postText']; ?></span>
  </div>
        <?php } ?>
      </div>
      <div class="clear"></div>
      <?php if (!empty($tsx['story']['fund_raise_id'])) {  ?>
          <?php if (!empty($tsx['story']['fund']['fund']['image'])): ?>
        <div class="post-file" id="fullsizeimg" style="width: 100%;margin-left: unset;">
          <img src="<?php echo $tsx['story']['fund']['fund']['image']; ?>" alt="Picture">
          <div class="joinda_dontd_posts">
            <div class="joinda_dontd_posts_innr">
              <div class="joinda_dontd_posts_left">
                <h4>
                  <a href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund']['fund']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund']['fund']['hashed_id']) ?>"><?php echo $tsx['story']['fund']['fund']['title']; ?></a>
                </h4>
                <!--<h5><?php echo $tsx['lang']['amount'] ?> : <?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund']['amount']; ?></h5>-->
                <p><?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund']['fund']['raised']; ?>  <?php echo $tsx['lang']['raised_of']; ?> <?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund']['fund']['amount']; ?></p>
              </div>
              <?php if ($tsx['story']['fund']['fund']['amount'] > $tsx['story']['fund']['fund']['raised']) { ?>
              <div class="joinda_dontd_posts_right">
                <a class="btn" href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund']['fund']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund']['fund']['hashed_id']) ?>"><?php echo $tsx['lang']['donate'] ?></a>
              </div>
              <?php } ?>
            </div>
            <div class="fund_raise_bar">
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <?php echo $tsx['story']['fund']['fund']['bar']; ?>%" aria-valuenow="<?php echo $tsx['story']['fund']['fund']['bar']; ?>" aria-valuemin="0" aria-valuemax="<?php echo($tsx['story']['fund']['fund']['amount']) ?>"></div>
              </div>
            </div>
          </div>
        </div>
      <?php endif; ?>


        <?php } ?>
        <?php if (!empty($tsx['story']['fund_id'])) { ?>

          <?php if (!empty($tsx['story']['fund_data']['image'])): ?>
        <div class="post-file" id="fullsizeimg" style="width: 100%;margin-left: unset;">
          <img src="<?php echo $tsx['story']['fund_data']['image']; ?>" alt="Picture">
          <div class="joinda_dontd_posts">
            <div class="joinda_dontd_posts_innr">
              <div class="joinda_dontd_posts_left">
                <h4>
                  <a href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund_data']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund_data']['hashed_id']) ?>"><?php echo $tsx['story']['fund_data']['title']; ?></a>
                </h4>
                <!--<h5><?php echo $tsx['lang']['amount'] ?> : <?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund_data']['amount']; ?></h5>-->
                <p><?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund_data']['raised']; ?>  <?php echo $tsx['lang']['raised_of']; ?> <?php echo $tsx['config']['currency_symbol_array'][$tsx['config']['currency']].$tsx['story']['fund_data']['amount']; ?></p>
              </div>
              <?php if ($tsx['story']['fund_data']['amount'] > $tsx['story']['fund_data']['raised']) { ?>
              <div class="joinda_dontd_posts_right">
                <a class="btn" href="<?php echo $tsx['config']['site_url'].'/show_fund/'. $tsx['story']['fund_data']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($tsx['story']['fund_data']['hashed_id']) ?>"><?php echo $tsx['lang']['donate'] ?></a>
              </div>
            <?php } ?>
            </div>
            <div class="fund_raise_bar">
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <?php echo $tsx['story']['fund_data']['bar']; ?>%" aria-valuenow="<?php echo $tsx['story']['fund_data']['bar']; ?>" aria-valuemin="0" aria-valuemax="<?php echo($tsx['story']['fund_data']['amount']) ?>"></div>
              </div>
            </div>
          </div>
        </div>
      <?php endif; ?>


        <?php } ?>

        <?php if (!empty($tsx['story']['offer_id'])) { ?>
          <div class="post-fetched-url tsx_post_fetch_event" id="fullsizeimg">
             <a href="<?php echo $tsx['story']['offer']['url'];?>">
                <?php if (!empty($tsx['story']['offer']['image'])) {?>
                   <img src="<?php echo $tsx['story']['offer']['image'];?>"/>
                <?php } ?>
                <div class="fetched-url-text">
                   <div class="short_start_dt">
                      <b><?php echo $tsx['lang']['end_date']." ".$tsx['story']['offer']['expire_date'];?></b>
                   </div>
                   <h4><?php if (strlen($tsx['story']['offer']['description']) > 175):?>
                      <?php echo mb_substr($tsx['story']['offer']['description'],0,175,"UTF-8") . "..."; ?>
                      <?php else:?>
                      <?php echo $tsx['story']['offer']['description']; ?>
                      <?php endif;?></h4>
                   <div class="url"><?php echo $tsx['story']['offer']['offer_text'].' '.$tsx['story']['offer']['discounted_items']; ?></div>
                </div>
                <div class="clear"></div>
             </a>
          </div>
        <?php } ?>
      <!-- start decs -->
      <?php  $tsx['story'] = $current_post; ?>
      <!-- Hide Post Owner -->
      <?php
         if (!empty($tsx['story']['product_id'])) {
           $class = '';
           $small = '';
           $singleimg = '';
           if (count($tsx['story']['product']['images']) == 1) {
             $singleimg = 'tsx_single_proimg';
           }
           if (count($tsx['story']['product']['images']) == 2) {
             $class = 'width-2';
           }
           if (count($tsx['story']['product']['images']) > 1) {
             $small = '_small';
           }
           if (count($tsx['story']['product']['images']) > 2) {
             $class = 'width-3';
           }
           if (count($tsx['story']['product']['images']) > 3) {
             foreach (array_slice($tsx['story']['product']['images'],0,3) as $key => $photo) {
               if ($key == 2) {
                 echo "<div onclick='tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");' class='album-collapse pointer'> 
                 <img src='".($photo['image_org'])."' class='image-file'>
                 <span>+".count(array_slice($tsx['story']['product']['images'],2))."</span>
                 </div>
                 "; 
               }
               else{
                 echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer' 
                 onclick='tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");'>";
               }
             }
             foreach (array_slice($tsx['story']['product']['images'],3) as $photo) {
               echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer hidden' 
               onclick='tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");'>";
             }
           }
           else{
             foreach ($tsx['story']['product']['images'] as $photo) {
               echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " " . $singleimg . " image-file pointer' 
               onclick='tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");'>";
             }
           }
           echo '<br><br>';
    $symbol =  (!empty($tsx['currencies'][$tsx['story']['product']['currency']]['symbol'])) ? $tsx['currencies'][$tsx['story']['product']['currency']]['symbol'] : $tsx['config']['classified_currency_s'];
    $text =  (!empty($tsx['currencies'][$tsx['story']['product']['currency']]['text'])) ? $tsx['currencies'][$tsx['story']['product']['currency']]['text'] : $tsx['config']['classified_currency'];
    $status = '<span class="product-description">' . $tsx['lang']['currently_unavailable'] . '</span>';
    if ($tsx['story']['product']['units'] > 0) {
      $status = ($tsx['story']['product']['status'] == 0) ? '' . $tsx['lang']['in_stock'] . '' : '<span class="product-status-sold">' . $tsx['lang']['sold'] . '</span><br><br>';
    }
    $type = ($tsx['story']['product']['type'] == 0) ? '<span class="product-description">' . $tsx['lang']['new'] . '</span>' : '<span class="product-description">' . $tsx['lang']['used'] . '</span><br>';
    echo '<div class="joinda_post_prod">';
    echo '<h4 class="joinda_post_prod_name">' . $tsx['story']['product']['name'] . '</h4>';
    echo '<div class="joinda_post_prod_shead">';
    if (!empty($tsx['story']['product']['location'])) {
      echo '<span> ' . $tsx['story']['product']['location'] . '</span><span class="middot">·</span>';
    }
    echo '<span> ' . $status . '</span>';
    echo '</div>';
    echo '<div class="joinda_post_prod_infos"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20,8H4V6H20M20,18H4V12H20M20,4H4C2.89,4 2,4.89 2,6V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V6C22,4.89 21.1,4 20,4Z" /></svg>' . $tsx['lang']['price'] . ' <span class="product-description" style="max-height: none;">' . $symbol . $tsx['story']['product']['price'] . ' (' . $text . ')</span></div>';
    echo '<div class="joinda_post_prod_infos"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M16,17H5V7H16L19.55,12M17.63,5.84C17.27,5.33 16.67,5 16,5H5A2,2 0 0,0 3,7V17A2,2 0 0,0 5,19H16C16.67,19 17.27,18.66 17.63,18.15L22,12L17.63,5.84Z" /></svg>' . $tsx['lang']['type'] . ' ' . $type . '</div>';
    echo '<div class="joinda_post_prod_infos"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" /></svg><p class="product-description product-description-'.$tsx['story']['product']['id'].'">' . $tsx['story']['product']['description'] . '</p></div>';
    echo '</div>';
         } 
         ?>
      <p class="joinda_shared_posts_p" dir="auto"><?php if (!empty($tsx['story']['postFeeling']) && $extra_exists == 1) { ?>
         <span class="feeling-text"> — <i class="twa-lg twa twa-<?php echo $tsx['story']['postFeelingIcon'];?>"></i> <?php echo $tsx['lang']['feeling'];?> <?php echo $tsx['lang'][$tsx['story']['postFeeling']];?></span><?php } ?><?php if (!empty($tsx['story']['postTraveling']) && $extra_exists == 1) { ?>
         <span class="feeling-text"> — <i class="fa fa-plane"></i> <?php echo $tsx['lang']['traveling'];?><?php echo $tsx['story']['postTraveling'];?></span>
         <?php } ?><?php if (!empty($tsx['story']['postWatching']) && $extra_exists == 1) { ?>
         <span class="feeling-text"> — <i class="fa fa-eye"></i> <?php echo $tsx['lang']['watching'];?> <?php echo $tsx['story']['postWatching'];?></span>
         <?php } ?><?php if (!empty($tsx['story']['postPlaying']) && $extra_exists == 1) { ?>
         <span class="feeling-text"> — <i class="fa fa-gamepad"></i> <?php echo $tsx['lang']['playing'];?> <?php echo $tsx['story']['postPlaying'];?></span>
         <?php } ?><?php if (!empty($tsx['story']['postListening']) && $extra_exists == 1) { ?>
         <span class="feeling-text"> — <i class="fa fa-headphones"></i> <?php echo $tsx['lang']['listening'];?> <?php echo $tsx['story']['postListening'];?></span>
         <?php } ?></p>
     
      <?php if(!empty($tsx['story']['postYoutube'])) {  ?>
      <div class="post-youtube tsx_video_post">
         <iframe id="ytplayer" type="text/html" width="100%" height="340" src="https://www.youtube.com/embed/<?php echo $tsx['story']['postYoutube']; ?>?autoplay=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen/></iframe>
      </div>
      <?php } ?>
      <?php if(!empty($tsx['story']['postPlaytube'])) {  ?>
      <div class="post-youtube tsx_video_post">
         <iframe id="ptplayer" type="text/html" width="100%" height="340" src="<?php echo $tsx['config']['playtube_url']; ?>/embed/<?php echo $tsx['story']['postPlaytube']; ?>?autoplay=0&fullscreen=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen/></iframe>
      </div>
      <?php } ?>
      <?php if(!empty($tsx['story']['postDeepsound'])) {  ?>
      <div class="post-youtube tsx_video_post">
         <iframe id="ptplayer" type="text/html" width="100%" height="200" src="<?php echo $tsx['config']['deepsound_url']; ?>/embed/<?php echo $tsx['story']['postDeepsound']; ?>?autoplay=0&fullscreen=1" frameborder="0" style="height: 140px !important;"/></iframe>
      </div>
      <?php } ?>
      <?php if(!empty($tsx['story']['postVimeo'])) {  ?>
      <div class="post-youtube tsx_video_post">
         <iframe src="https://player.vimeo.com/video/<?php echo $tsx['story']['postVimeo'];?>?byline=0&portrait=0" width="100%" height="340" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>
      <?php } ?>
      <?php if(!empty($tsx['story']['postFacebook'])) {  ?>
        <script>
        // window.fbAsyncInit = function() {
              
        //    };
        FB.init({
              appId      : '374255706379985',
              xfbml      : true,
              version    : 'v3.2'
              });
        </script>
        <div id="fb-root"></div>
        <div class="fb-video" data-href="https://www.facebook.com/<?php echo $tsx['story']['postFacebook'];?>" data-show-text="false" data-width=""></div>
        <div class="clear"></div>
      <!-- <div class="post-youtube tsx_video_post">
         <iframe src="https://www.facebook.com/plugins/video.php?href=https://www.facebook.com/<?php echo $tsx['story']['postFacebook'];?>&show_text=0" width="100%" height="100%" frameborder="0" allowfullscreen></iframe>
         <div class="clear"></div>
      </div> -->
      <?php } ?>
      <?php if(!empty($tsx['story']['postDailymotion'])) {  ?>
      <div class="post-youtube tsx_video_post">
         <iframe frameborder="0" width="100%" height="340" src="https://www.dailymotion.com/embed/video/<?php echo $tsx['story']['postDailymotion']?>" allowfullscreen></iframe>
      </div>
      <?php } ?>
      <?php if(!empty($tsx['story']['postVine'])) {  ?>
      <iframe src="https://vine.co/v/<?php echo $tsx['story']['postVine']; ?>/embed/simple" width="100%" height="400" frameborder="0"></iframe>
      <?php } ?>
      <?php if(!empty($tsx['story']['postSoundCloud'])) { ?>
      <iframe width="100%" src="https://w.soundcloud.com/player/?url=https://api.soundcloud.com/tracks/<?php echo $tsx['story']['postSoundCloud'];?>&auto_play=false"></iframe>
      <?php } ?>
      <?php if(!empty($tsx['story']['postMap']) && empty($tsx['story']['postVine']) && empty($tsx['story']['postSoundCloud']) && empty($tsx['story']['postVimeo']) && empty($tsx['story']['postDailymotion']) && empty($tsx['story']['postYoutube']) && empty($tsx['story']['postPlaytube']) && empty($tsx['story']['postDeepsound']) && empty($tsx['story']['postFile']) && ($tsx['config']['google_map'] == 1 || $tsx['config']['yandex_map'] == 1)) { ?>
      <div class="post-map">
        <?php if ($tsx['config']['google_map'] == 1) { ?>
         <img src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $tsx['story']['postMap'];?>&zoom=13&size=600x250&maptype=roadmap&markers=color:red%7C<?php echo $tsx['story']['postMap'];?>&key=<?php echo $tsx['config']['google_map_api'];?>" width="100%">
         <?php } ?>
            <?php if ($tsx['config']['yandex_map'] == 1) { ?>
            <div id="shared_place_<?php echo($tsx['story']['id']) ?>" <?php echo($tsx['config']['yandex_map'] == 1 ? 'style="width: 100%; height: 300px; padding: 0; margin: 0;"' : '') ?>></div>
            <script type="text/javascript">
                  <?php if (!empty($tsx['story']['postMap'])) { ?>
                    setTimeout(function () {
                      var myMap;
                      ymaps.geocode("<?php echo($tsx['story']['postMap']); ?>").then(function (res) {
                          myMap = new ymaps.Map('shared_place_<?php echo($tsx['story']['id']) ?>', {
                              center: res.geoObjects.get(0).geometry.getCoordinates(),
                              zoom : 10
                          });
                          myMap.geoObjects.add(new ymaps.Placemark(res.geoObjects.get(0).geometry.getCoordinates(), {
                              balloonContent: ''
                          }));
                      });
                    },1000);
                  <?php } ?>
                </script>
          <?php } ?>
      </div>
      <?php } ?>
      <?php if(!empty($tsx['story']['postLink']) && empty($tsx['story']['postVine']) && empty($tsx['story']['postPlaytube']) && empty($tsx['story']['postDeepsound']) && empty($tsx['story']['postSoundCloud']) && empty($tsx['story']['postYoutube']) && empty($tsx['story']['postFile'])) { ?>
        <?php if (!preg_match("/(http|https):\/\/twitter\.com\/[a-zA-Z0-9_]+\/status\/[0-9]+/", $tsx['story']['postLink']) && !preg_match("/(http|https):\/\/www.tiktok\.com\/(.*)\/video\/(.*)+/", $tsx['story']['postLink']) && !preg_match("/^(http:\/\/|https:\/\/|www\.).*(\.mp4)$/", $tsx['story']['postLink'])) { ?>
      <div class="post-fetched-url tsx_post_fetch_link">
         <a href="<?php echo $tsx['story']['postLink'];?>" target="_blank">
            <?php if (!empty($tsx['story']['postLinkImage'])) {?>
            <div class="post-fetched-url-con">
               <img src="<?php echo $tsx['story']['postLinkImage'];?>" class="<?php echo tsx_RightToLeft('pull-left');?>" alt="<?php echo $tsx['story']['postLinkTitle'];?>"/>
               <div class="url">
                  <?php 
                     $parse = parse_url($tsx['story']['postLink']);
                     echo $parse['host'];
                     ?>
               </div>
            </div>
            <?php } ?>
            <div class="fetched-url-text">
               <h4><?php echo $tsx['story']['postLinkTitle'];?></h4>
               <div class="description"><?php echo $tsx['story']['postLinkContent'];?></div>
            </div>
            <div class="clear"></div>
         </a>
      </div>
      <?php }
      elseif (preg_match("/(http|https):\/\/www.tiktok\.com\/(.*)\/video\/(.*)+/", $tsx['story']['postLink'])) {
          echo html_entity_decode($tsx['story']['postLinkContent']);
        }elseif (preg_match("/^(http:\/\/|https:\/\/|www\.).*(\.mp4)$/", $tsx['story']['postLink'])) {
         ?>
         <div class="post-file" id="fullsizeimg" style="width: 100%;margin-left:0;">
            <?php
               $tsx['media'] = array('storyId' => $tsx['story']['id'],
                                    'filename' => $tsx['story']['postLink'],
                                    'video_thumb' => '');
               $tsx['tsx_ad_id'] = '';
               $tsx['rvad_con'] = '';
               echo tsx_LoadPage('players/video');
               ?>
         </div>
         <?php
        }
      else{ ?>
   <?php echo html_entity_decode($tsx['story']['postLinkContent']);?>
 <?php } ?>
      <?php } ?>
      <?php if(!empty($tsx['story']['page_event_id'])) { ?>
      <div class="post-fetched-url tsx_post_fetch_event" id="fullsizeimg">
    <a href="<?php echo $tsx['story']['event']['url'];?>">
      <?php if (!empty($tsx['story']['event']['cover'])) {?>
        <img src="<?php echo $tsx['story']['event']['cover'];?>"/>
      <?php } ?>
      <div class="fetched-url-text">
        <div class="short_start_dt">
          <b><?php echo date('d',strtotime($tsx['story']['event']['start_edit_date'])); ?></b>
          <span><?php echo date('M',strtotime($tsx['story']['event']['start_edit_date'])); ?></span>
        </div>
        <h4><?php echo $tsx['story']['event']['name'];?></h4>
        <div class="url"><?php echo $tsx['story']['event']['start_date'];?> <?php echo $tsx['lang']['to'];?> <?php echo $tsx['story']['event']['end_date'];?></div>
      </div>
      <div class="clear"></div>
    </a>
  </div>
      <?php } ?>
      <?php if(!empty($tsx['story']['blog_id'])) { ?>
      <div class="post-fetched-url tsx_post_fetch_blog" id="fullsizeimg">
    <a href="<?php echo $tsx['story']['blog']['url'];?>">
      <?php if (!empty($tsx['story']['blog']['thumbnail'])) {?>
        <div class="post-fetched-url-con">
          <img src="<?php echo $tsx['story']['blog']['thumbnail'];?>" alt="<?php echo $tsx['story']['blog']['title'];?>"/>
        </div>
      <?php } ?>
      <div class="fetched-url-text">
        <div class="joinda_post_blog_ico"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#f35d4d" d="M20,11H4V8H20M20,15H13V13H20M20,19H13V17H20M11,19H4V13H11M20.33,4.67L18.67,3L17,4.67L15.33,3L13.67,4.67L12,3L10.33,4.67L8.67,3L7,4.67L5.33,3L3.67,4.67L2,3V19A2,2 0 0,0 4,21H20A2,2 0 0,0 22,19V3L20.33,4.67Z"></path></svg></div>
        <h4><?php echo $tsx['story']['blog']['title'];?></h4>
        <div class="description"><?php echo $tsx['story']['blog']['description'];?></div>
      </div>
      <div class="clear"></div>
    </a>
  </div>
      <?php } ?>
      <?php if(!empty($tsx['story']['forum_id']) && !empty($tsx['story']['forum'])) { ?>
<div class="post-fetched-url tsx_post_fetch_blog">
   <a href="<?php echo $tsx['config']['site_url'].'/forums/'.$tsx['story']['forum']['id'];?>">
      <div class="fetched-url-text">
         <h4>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-book">
               <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>
               <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>
            </svg>
            <?php echo $tsx['story']['forum']['name'];?>
         </h4>
         <div class="description"><?php echo $tsx['story']['forum']['description'];?></div>
      </div>
      <div class="clear"></div>
   </a>
</div>
<?php } ?>
<?php if(!empty($tsx['story']['thread_id']) && !empty($tsx['story']['thread'])) { ?>
<div class="post-fetched-url tsx_post_fetch_blog">
   <a href="<?php echo $tsx['config']['site_url'].'/forums/thread/'.$tsx['story']['thread_id'];?>">
      <div class="fetched-url-text">
         <h4>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-book">
               <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>
               <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>
            </svg>
            <?php echo $tsx['story']['thread']['headline'];?>
         </h4>
      </div>
      <div class="clear"></div>
   </a>
</div>
<?php } ?>
      <?php if(!empty($tsx['story']['postFile'])) { ?>
      <div class="post-file" id="fullsizeimg" style="width: 100%;margin-left:0;">
         <?php
            $media = array(
              'type' => 'post',
              'storyId' => $tsx['story']['id'],
              'filename' => $tsx['story']['postFile'],
              'name' => $tsx['story']['postFileName'],
              'postFileThumb' => $tsx['story']['postFileThumb'],
            );
            echo tsx_DisplaySharedFile($media, '', $tsx['story']['cache']);
            ?>
      </div>
      <?php } ?>
      <?php 
        if ($tsx['config']['live_video'] == 1 && !empty($tsx['story']['stream_name'])) { ?>
      <div class="post-file" <?php echo $tsx['story']['is_still_live'] ? 'style="/*height: 440px;*/"' : ''; ?> id="fullsizeimg">
        <?php if ($tsx['story']['is_still_live']) { ?>
          <div class="embed-responsive embed-responsive-4by3">
            <iframe src="https://viewer.millicast.com/v2?streamId=<?php echo($tsx['config']['live_account_id']) ?>/<?php echo($tsx['story']['stream_name']) ?>" class="embed-responsive-item"></iframe>
            <div class="joinda_liv_counter"><span id="live_tsxrd_<?php echo($tsx['story']['id']) ?>"><?php echo $tsx['lang']['live']; ?></span> <span id="live_count_<?php echo($tsx['story']['id']) ?>"> <?php echo $tsx['story']['live_sub_users']; ?></span></div>
          </div>
          <?php if (!empty($tsx['page']) && $tsx['page']  == 'story' && $tsx['story']['comments_status'] == 1) { ?>
            <div id="live_post_comments_<?php echo($tsx['story']['id']) ?>" class="joinda_liv_comments_feed">
              <?php if (!empty($tsx['story']['get_post_comments'])) { 
                $count = 0;
                for ($i=count($tsx['story']['get_post_comments'])-1; $i >= 0 ; $i--){ 
                  $tsx['comment'] = $tsx['story']['get_post_comments'][$i];
                  if (!empty($tsx['comment']['text'])) { 
                    echo tsx_LoadPage('story/includes/live_comment');
                    $count = $count + 1;
                    if ($count == 4) {
                      break;
                    }
                  }
                }
              }
              ?>
            </div>
          <?php } ?>
        <?php } else{
          $tsx['media'] = array('filename' => 'https://viewer.millicast.com/v2?streamId='.$tsx['config']['live_account_id'].'/'.$tsx['story']['stream_name']);
          echo tsx_LoadPage('players/chat-video');
          }
        ?>
      </div>
        <?php } ?>
      <?php if (tsx_IsUrl($tsx['story']['postSticker'])): ?>
      <div class="post-file tsx_video_post">
         <?php if (strpos('.mp4', $tsx['story']['postSticker'])) { ?>
         <video autoplay loop>
            <source src="<?php echo $tsx['story']['postSticker']; ?>" type="video/mp4">
         </video>
         <?php } else { ?>
         <img src="<?php echo $tsx['story']['postSticker']; ?>" alt="GIF">
         <?php } ?>
      </div>
      <?php endif; ?>
      <?php if (tsx_IsUrl($tsx['story']['postPhoto'])): ?>
      <div class="post-file" id="fullsizeimg" style="width: 100%;margin-left:0;">
         <img src="<?php echo $tsx['story']['postPhoto']; ?>" alt="Picture">
      </div>
      <?php endif; ?>
      <?php if(!empty($tsx['story']['postRecord'])) { ?>
      <div class="post-file">
         <?php  
            $media = array(
              'type' => 'post',
              'storyId' => $tsx['story']['id'],
              'filename' => $tsx['story']['postRecord'],
              'name' => ''
            );
            echo  tsx_DisplaySharedFile($media,'record');
            ?>
      </div>
      <?php } ?>
      <div id="fullsizeimg" style="position: relative; width: 100%;margin-left:0;">
         <?php if (!empty($tsx['story']['photo_album']) && $tsx['story']['blur'] == 1) { ?>
         <div class="post-file show_album_<?php echo $tsx['story']['id']; ?> blur_multi_images" id="fullsizeimg" style="width: 100%;margin-left:0;">
            <button class='btn btn-main image_blur_btn remover_blur_btn_<?php echo $tsx['story']['id']; ?>' onclick='tsx_RemoveBlurAlbum(this,<?php echo $tsx['story']['id']; ?>)'><?php echo $tsx['lang']['view_image']; ?></button>
            <img src="<?php echo(tsx_GetMedia($tsx['story']['photo_album'][0]['image_org'])) ?>" alt='image' class='image-file pointer image_blur remover_blur_<?php echo $tsx['story']['id']; ?>'>
         </div>
         <?php } ?>
         <?php if (!empty($tsx['story']['photo_album'])) {
            $class = '';
            $small = '';
            if (count($tsx['story']['photo_album']) == 2) {
              $class = 'width-2';
            }
            if (count($tsx['story']['photo_album']) > 1) {
              $small = '_small';
            }
            if (count($tsx['story']['photo_album']) > 2) {
              $class = 'width-3';
            }
            $delete  = '';
            $onhover = '';
            if (count($tsx['story']['photo_album']) == 3) {
              echo "<div class='tsx_adaptive_media'>";
              foreach ($tsx['story']['photo_album'] as $photo) {
                if ($tsx['story']['admin'] === true && empty($tsx['story']['parent_id'])) {
                  $delete = "<span onclick='tsx_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='tsx_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='tsx_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
               if (!empty($photo['parent_id'])) {
                 $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
               }
                echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . tsx_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='".$multi_image_function."'></div>";
              }
              echo "</div>";
            }
            else if (count($tsx['story']['photo_album']) == 4) {
              echo "<div class='tsx_adaptive_media_4'>";
              foreach ($tsx['story']['photo_album'] as $photo) {
                if ($tsx['story']['admin'] === true && empty($tsx['story']['parent_id'])) {
                  $delete = "<span onclick='tsx_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='tsx_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='tsx_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
               if (!empty($photo['parent_id'])) {
                 $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
               }
                echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . tsx_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='".$multi_image_function."'></div>";
              }
              echo "</div>";
            }
            else if (count($tsx['story']['photo_album']) == 5) {
              echo "<div class='tsx_adaptive_media_5'>";
              foreach ($tsx['story']['photo_album'] as $photo) {
                if ($tsx['story']['admin'] === true && empty($tsx['story']['parent_id'])) {
                  $delete = "<span onclick='tsx_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='tsx_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='tsx_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
               if (!empty($photo['parent_id'])) {
                 $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
               }
                echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . tsx_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='".$multi_image_function."'></div>";
              }
              echo "</div>";
            }
            else if (count($tsx['story']['photo_album']) > 3) {
              foreach (array_slice($tsx['story']['photo_album'],0,3) as $key => $photo) {
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
               if (!empty($photo['parent_id'])) {
                 $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
               }
                if ($key == 2) {
                  echo "<div onclick='".$multi_image_function."' class='album-collapse pull-left pointer'> 
                  <img src='".tsx_GetMedia($photo['image_org'])."' class='image-file'>
                  <span>+".count(array_slice($tsx['story']['photo_album'],2))."</span>
                  </div>
                    "; 
                }
                else{
                  if ($tsx['story']['admin'] === true && empty($tsx['story']['parent_id'])) {
                    $delete = "<span onclick='tsx_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                    $onhover = "onmouseover='tsx_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='tsx_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                  }
                  echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . tsx_GetMedia($photo['image_org']) . "' alt='image' class='image-file  pointer' onclick='".$multi_image_function."'></div>";
                }
              }
              foreach (array_slice($tsx['story']['photo_album'],3) as $photo) {
                if ($tsx['story']['admin'] === true && empty($tsx['story']['parent_id'])) {
                  $delete = "<span onclick='tsx_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='tsx_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='tsx_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
               if (!empty($photo['parent_id'])) {
                 $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
               }
                echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . tsx_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer hidden' onclick='".$multi_image_function."'></div>";
              }
            }
            else{
              foreach ($tsx['story']['photo_album'] as $photo) {
                if ($tsx['story']['admin'] === true && empty($tsx['story']['parent_id'])) {
                  $delete = "<span onclick='tsx_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='tsx_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='tsx_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
               if (!empty($photo['parent_id'])) {
                 $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
               }
                echo  "<div style='text-align:center;width: 100%;' class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . tsx_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='".$multi_image_function."'></div>";
              }
            }
            } 
            ?>
         <?php if ($tsx['story']['multi_image'] == 1) {
            if ($tsx['story']['blur'] == 1) { ?>
         <div class="post-file show_album_<?php echo $tsx['story']['id']; ?> blur_multi_images" id="fullsizeimg" style="width: 100%;margin-left:0;">
            <button class='btn btn-main image_blur_btn remover_blur_btn_<?php echo $tsx['story']['id']; ?>' onclick='tsx_RemoveBlurAlbum(this,<?php echo $tsx['story']['id']; ?>)'><?php echo $tsx['lang']['view_image']; ?></button>
            <img src="<?php echo(tsx_GetMedia($tsx['story']['photo_multi'][0]['image_org'])) ?>" alt='image' class='image-file pointer image_blur remover_blur_<?php echo $tsx['story']['id']; ?>'>
         </div>
         <?php }
            $class = '';
            $small = '';
            if (count($tsx['story']['photo_multi']) == 2) {
              $class = 'width-2';
            }
            if (count($tsx['story']['photo_multi']) > 1) {
              $small = '_small';
            }
            if (count($tsx['story']['photo_multi']) > 2) {
              $class = 'width-3';
            }
            if (count($tsx['story']['photo_multi']) == 3) {
              echo "<div class='tsx_adaptive_media'>";
              foreach ($tsx['story']['photo_multi'] as $photo) {
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
                if (!empty($photo['parent_id'])) {
                  $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
                }
                echo  "<div class='album-image'><img src='" . tsx_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='".$multi_image_function."'></div>";
              }
              echo "</div>";
            }
            else if (count($tsx['story']['photo_multi']) == 4) {
              echo "<div class='tsx_adaptive_media_4'>";
              foreach ($tsx['story']['photo_multi'] as $photo) {
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
                if (!empty($photo['parent_id'])) {
                  $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
                }
                echo  "<div class='album-image'><img src='" . tsx_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='".$multi_image_function."'></div>";
              }
              echo "</div>";
            }
            else if (count($tsx['story']['photo_multi']) == 5) {
              echo "<div class='tsx_adaptive_media_5'>";
              foreach ($tsx['story']['photo_multi'] as $photo) {
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
                if (!empty($photo['parent_id'])) {
                  $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
                }
                echo  "<div class='album-image'><img src='" . tsx_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='".$multi_image_function."'></div>";
              }
              echo "</div>";
            }
            else if (count($tsx['story']['photo_multi']) > 3) {
              foreach (array_slice($tsx['story']['photo_multi'],0,3) as $key => $photo) {
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
                if (!empty($photo['parent_id'])) {
                  $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
                }
                if ($key == 2) {
                  echo "<div onclick='".$multi_image_function."' class='album-collapse pointer'> 
                  <img src='".tsx_GetMedia($photo['image_org'])."' class='image-file'>
                  <span>+".count(array_slice($tsx['story']['photo_multi'],2))."</span>
                  </div>
                  "; 
                }
                else{
                  echo  "<img src='" . tsx_GetMedia($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer' 
                  onclick='".$multi_image_function."'>";
                }
              }
              foreach (array_slice($tsx['story']['photo_multi'],3) as $photo) {
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
                if (!empty($photo['parent_id'])) {
                  $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
                }
                echo  "<img src='" . tsx_GetMedia($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer hidden' 
                onclick='".$multi_image_function."'>";
              }
            }
            else{
              foreach ($tsx['story']['photo_multi'] as $photo) {
                $multi_image_function = "tsx_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");";
                if (!empty($photo['parent_id'])) {
                  $multi_image_function = "tsx_OpenLightBox(" . $photo['parent_id'] . ", \"album\");";
                }
                echo  "<img src='" . tsx_GetMedia($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer' 
                onclick='".$multi_image_function."'>";
              }
            }
            }
            ?>
         <div class="clear"></div>
      </div>
      <?php
         if ($tsx['story']['poll_id'] == 1) {
           echo tsx_LoadPage('story/entries/options');
         }
         ?>
      <div class="clear"></div>
      <!-- end decs -->
   </div>
   <div class="clear"></div>
</div>
<div class="clear"></div>
<?php  $tsx['story'] = $current_post;}
   ?>