<?php
$page_name = '';
$page_icon = '';
switch ($wo['active']) {
		case 1:
			$page_name = $wo['lang']['events'];
			break;
		case 2:
			$page_name = $wo['lang']['going'];
			break;
		case 3:
			$page_name = $wo['lang']['invited'];
			break;
		case 4:
			$page_name = $wo['lang']['interested'];
			break;
		case 5:
			$page_name = $wo['lang']['past'];
			break;
		case 6:
			$page_name = $wo['lang']['create'];
			break;
		case 7:
			$page_name = $wo['lang']['my_events'];
			break;
		default:
	}
?>
<style>
	span.button-text {color: #1E1F20; }.btn-default {background: #ebeef0;border: 0;color: #1E1F20; }
	.pag_neg_padd.pag_alone {
    display: flex;
    align-items: center;
    justify-content: space-between;
}
a.btn.btn-main.btn-mat.btn-mat-raised {
    padding: 0 40px;
    background: transparent linear-gradient(180deg, #E01F1F 0%, #BD1616 100%) 0% 0% no-repeat padding-box;
}
</style>


<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 profile-lists singlecol">
			<div class="events-content-wrapper">
				<div class="page-margin mt-0">
					<div class="pag_neg_padd pag_alone">
						<div class="wo_page_hdng_innr big_size">
						<svg width="583" height="639" viewBox="0 0 583 639" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M431.95 213.63L387.99 182.8L450.5 59.6802L526.43 112.94L431.95 213.63Z" fill="url(#paint0_linear_1118_285)"/>
							<path d="M576.36 126.43C559 152.12 508.71 148.48 464.04 118.29C419.36 88.1001 397.21 42.8101 414.57 17.1201C431.93 -8.56991 482.22 -4.9299 526.89 25.2601C571.57 55.4401 593.72 100.74 576.36 126.43Z" fill="url(#paint1_linear_1118_285)"/>
							<path d="M455.59 294.71C433.7 327.1 280 223.26 301.88 190.86C323.76 158.47 375.91 155.46 418.36 184.13C460.8 212.81 477.47 262.32 455.59 294.71Z" fill="url(#paint2_linear_1118_285)"/>
							<path d="M301.04 366.27L293.05 360.67L371.53 248.77L379.53 254.37L301.04 366.27Z" fill="url(#paint3_linear_1118_285)"/>
							<path d="M470.13 305.89L469.83 569.03C469.83 581.83 459.09 592.21 445.84 592.21H67.42C54.17 592.21 43.43 581.83 43.43 569.03V214.77C43.43 201.97 54.17 191.59 67.42 191.59H268.48V141.99H28.68C12.84 141.99 0 154.4 0 169.71V610.29C0 625.6 12.84 638.01 28.68 638.01H484.58C500.42 638.01 513.26 625.6 513.26 610.29V305.89H470.13Z" fill="url(#paint4_linear_1118_285)"/>
							<path d="M267.41 305.89H10.2299L8.62988 327.45H267.41V305.89Z" fill="url(#paint5_linear_1118_285)"/>
							<defs>
							<linearGradient id="paint0_linear_1118_285" x1="401.441" y1="113.526" x2="521.119" y2="183.107" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint1_linear_1118_285" x1="408.654" y1="71.7724" x2="582.274" y2="71.7724" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint2_linear_1118_285" x1="299.755" y1="232.674" x2="465.219" y2="232.674" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint3_linear_1118_285" x1="293.047" y1="307.519" x2="379.528" y2="307.519" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint4_linear_1118_285" x1="10.9908" y1="351.403" x2="504.626" y2="491.989" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="0.0146" stop-color="#81D6C1"/>
							<stop offset="0.0593" stop-color="#6AAD9C"/>
							<stop offset="0.1095" stop-color="#55877B"/>
							<stop offset="0.1641" stop-color="#43675E"/>
							<stop offset="0.2244" stop-color="#334B46"/>
							<stop offset="0.2925" stop-color="#273532"/>
							<stop offset="0.3721" stop-color="#1E2423"/>
							<stop offset="0.4705" stop-color="#171919"/>
							<stop offset="0.6085" stop-color="#131213"/>
							<stop offset="0.9916" stop-color="#121011"/>
							</linearGradient>
							<linearGradient id="paint5_linear_1118_285" x1="22.4089" y1="316.671" x2="281.197" y2="316.671" gradientUnits="userSpaceOnUse">
							<stop stop-color="#8AE5CE"/>
							<stop offset="1" stop-color="#121011"/>
							</linearGradient>
							</defs>
						</svg>

				<?php echo $wo['lang']['events']; ?>
						</div>
						<?php if ($wo['config']['can_use_events']) { ?>
							<a class="btn btn-main btn-mat btn-mat-raised create-btn-bottom" href="<?php echo Wo_SeoLink('index.php?link1=create-event');?>">
								<svg height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg">
									<g id="_03_Login" data-name="03 Login"><path d="m256 512a25 25 0 0 1 -25-25v-462a25 25 0 0 1 50 0v462a25 25 0 0 1 -25 25z"/><path d="m487 281h-462a25 25 0 0 1 0-50h462a25 25 0 0 1 0 50z"/></g>
								</svg>
							</a>
							<?php } ?>
					</div>
				</div>
				<div class="row">