<?php
$page_name = '';
$page_icon = '';
switch ($wo['active']) {
		case 1:
			$page_name = $wo['lang']['events'];
			break;
		case 2:
			$page_name = $wo['lang']['going'];
			break;
		case 3:
			$page_name = $wo['lang']['invited'];
			break;
		case 4:
			$page_name = $wo['lang']['interested'];
			break;
		case 5:
			$page_name = $wo['lang']['past'];
			break;
		case 6:
			$page_name = $wo['lang']['create'];
			break;
		case 7:
			$page_name = $wo['lang']['my_events'];
			break;
		default:
	}
?>
<style>
	span.button-text {color: #1E1F20; }.btn-default {background: #ebeef0;border: 0;color: #1E1F20; }
	.pag_neg_padd.pag_alone {
    display: flex;
    align-items: center;
    justify-content: space-between;
}
a.btn.btn-main.btn-mat.btn-mat-raised {
    padding: 0 40px;
    background: transparent linear-gradient(180deg, #E01F1F 0%, #BD1616 100%) 0% 0% no-repeat padding-box;
}
</style>


<div class="leftcol-sidebar"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
<div class="page-margin">
	<div class="row">
		<div class="col-md-7 profile-lists singlecol">
			<div class="events-content-wrapper">
				<div class="page-margin mt-0">
					<div class="pag_neg_padd pag_alone">
						<div class="wo_page_hdng_innr big_size">
						<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="27.999" height="28" viewBox="0 0 27.999 28">
				<defs>
					<linearGradient id="linear-gradient4231" x1="0.251" y1="0.741" x2="0.251" gradientUnits="objectBoundingBox">
					<stop offset="0" stop-color="#8c5afd"></stop>
					<stop offset="1" stop-color="#13e2da"></stop>
					</linearGradient>
				</defs>
				<path id="Union_37" data-name="Union 37" d="M-152.6,4992a1.445,1.445,0,0,1-.993-.406,1.448,1.448,0,0,1-.406-.995v-22.4a1.444,1.444,0,0,1,.406-.994,1.442,1.442,0,0,1,.993-.407h5.6V4964h2.8v2.8h8.4V4964h2.8v2.8h5.6a1.446,1.446,0,0,1,.995.407,1.443,1.443,0,0,1,.4.994v22.4a1.446,1.446,0,0,1-.4.995,1.449,1.449,0,0,1-.995.406Zm1.4-2.8h22.4v-14h-22.4Zm10.707-4.078-3.767,1.987.718-4.2-3.051-2.974,4.217-.6,1.883-3.819,1.884,3.819,4.2.6-3.037,2.974.718,4.2Z" transform="translate(154 -4964)" fill="url(#linear-gradient4231)"></path>
				</svg><?php echo $wo['lang']['events']; ?>
						</div>
						<?php if ($wo['config']['can_use_events']) { ?>
							<a class="btn btn-main btn-mat btn-mat-raised create-btn-bottom" href="<?php echo Wo_SeoLink('index.php?link1=create-event');?>">
								<svg height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg"><g id="_03_Login" data-name="03 Login"><path d="m256 512a25 25 0 0 1 -25-25v-462a25 25 0 0 1 50 0v462a25 25 0 0 1 -25 25z"/><path d="m487 281h-462a25 25 0 0 1 0-50h462a25 25 0 0 1 0 50z"/></g></svg>
							</a>
							<?php } ?>
					</div>
				</div>
				<div class="row">