<div class="modal fade" id="calling-modal" role="dialog" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog joinda_mat_mdl modal-sm">
		<div class="modal-content text-center tsx_calling_modals video">
			<img src="<?php echo $tsx['calling_user']['avatar'];?>">
			<div class="modal-header">
				<div class="avatar">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,10.5V7A1,1 0 0,0 16,6H4A1,1 0 0,0 3,7V17A1,1 0 0,0 4,18H16A1,1 0 0,0 17,17V13.5L21,17.5V6.5L17,10.5Z" /></svg>
					<img width="100" height="100" src="<?php echo $tsx['calling_user']['avatar'];?>">
				</div>
				<h4 class="modal-title"><?php echo $tsx['lang']['calling'];?> <?php echo $tsx['calling_user']['username'];?> ..</h4>
			</div>
			<div class="modal-body">
				<p><?php echo $tsx['lang']['calling_desc'];?></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-mat cancel-call" onclick="tsx_CancelCall();"><i class="fa fa-times progress-icon" data-icon="times"></i> <?php echo $tsx['lang']['cancel'];?></button>
			</div>
		</div>
	</div>
</div>