<!-- Text input-->
<div class="col-lg-6">
	<div class="sun_input">
		<select id="discount_type_<?php echo($tsx['offer']['id']) ?>" name="discount_type" class="form-control input-md" onchange="change_discount(this,<?php echo($tsx['offer']['id']) ?>)"">
			<option value="discount_percent" <?php echo $tsx['offer']['discount_type'] == 'discount_percent' ? 'selected' : ''; ?>><?php echo $tsx['lang']['discount_percent'] ?></option>
			<option value="discount_amount" <?php echo $tsx['offer']['discount_type'] == 'discount_amount' ? 'selected' : ''; ?>><?php echo $tsx['lang']['discount_amount'] ?></option>
			<option value="buy_get_discount" <?php echo $tsx['offer']['discount_type'] == 'buy_get_discount' ? 'selected' : ''; ?>><?php echo $tsx['lang']['buy_get_discount'] ?></option>
			<option value="spend_get_off" <?php echo $tsx['offer']['discount_type'] == 'spend_get_off' ? 'selected' : ''; ?>><?php echo $tsx['lang']['spend_get_off'] ?></option>
			<option value="free_shipping" <?php echo $tsx['offer']['discount_type'] == 'free_shipping' ? 'selected' : ''; ?>><?php echo $tsx['lang']['free_shipping'] ?></option>
		</select>
	</div>
</div>

<div class="col-lg-6 discount_percent_input_<?php echo($tsx['offer']['id']) ?>"  <?php echo $tsx['offer']['discount_type'] == 'discount_percent' || $tsx['offer']['discount_type'] == 'buy_get_discount' ? '' : 'style="display: none;"'; ?>>
	<div class="sun_input">
		<select name="discount_percent" class="form-control input-md">
			<?php for ($i=1; $i < 100 ; $i++) {  ?>
				<option value="<?php echo $i ?>" <?php echo $tsx['offer']['discount_percent'] == $i ? 'selected' : ''; ?>><?php echo $i ?>%</option>
			<?php } ?>
		</select>
	</div>
</div>
<div class="clear"></div>
							<div class="col-lg-12">
								<br>
							</div>
<div class="col-lg-6 discount_amount_input_<?php echo($tsx['offer']['id']) ?>"  <?php echo $tsx['offer']['discount_type'] == 'discount_amount' ? '' : 'style="display: none;"'; ?>>
	<div class="sun_input">
		<input name="discount_amount" type="text" class="form-control input-md" placeholder="<?php echo $tsx['lang']['discount_amount'] ?>" value="<?php echo($tsx['offer']['discount_amount']) ?>">
	</div>
</div>
<div class="clear"></div>
							<div class="col-lg-12">
								<br>
							</div>
<div class="col-lg-12 buy_get_discount_input_<?php echo($tsx['offer']['id']) ?>" <?php echo $tsx['offer']['discount_type'] == 'buy_get_discount' ? '' : 'style="display: none;"'; ?>>
	<div class="col-lg-6">
		<div class="sun_input">
			<input name="buy" type="text" class="form-control input-md" placeholder="<?php echo $tsx['lang']['buy'] ?>"  value="<?php echo($tsx['offer']['buy']) ?>">
		</div>
	</div>
	<div class="col-lg-6">
		<div class="sun_input">
			<input name="get" type="text" class="form-control input-md" placeholder="<?php echo $tsx['lang']['get'] ?>" value="<?php echo($tsx['offer']['get_price']) ?>">
		</div>
	</div>
</div>
<div class="clear"></div>
							<div class="col-lg-12">
								<br>
							</div>
<div class="col-lg-12 spend_get_off_input_<?php echo($tsx['offer']['id']) ?>" <?php echo $tsx['offer']['discount_type'] == 'spend_get_off' ? '' : 'style="display: none;"'; ?>>
	<div class="col-lg-6">
		<div class="sun_input">
			<input name="spend" type="text" class="form-control input-md" placeholder="<?php echo $tsx['lang']['spend'] ?>" value="<?php echo($tsx['offer']['spend']) ?>">
		</div>
	</div>
	<div class="col-lg-6">
		<div class="sun_input">
			<input name="amount_off" type="text" class="form-control input-md" placeholder="<?php echo $tsx['lang']['amount_off'] ?>" value="<?php echo($tsx['offer']['amount_off']) ?>">
		</div>
	</div>
</div>


<div class="clear"></div>
							<div class="col-lg-12">
								<br>
							</div>

<div class="col-lg-12 no-padding-right">
	<div class="sun_input">
		<input name="discounted_items" type="text" class="form-control input-md" placeholder="<?php echo $tsx['lang']['discounted_items'] ?>" value="<?php echo($tsx['offer']['discounted_items']) ?>" maxlength="100">
		<small><?php echo $tsx['lang']['items_services'] ?> </small>
	</div>
</div>
<div class="clear"></div>
							<div class="col-lg-12">
								<br>
							</div>
<div class="col-lg-12">
	<div class="sun_input">
		<textarea class="form-control" name="description" rows="3" placeholder="<?php echo $tsx['lang']['description'] ?>"><?php echo($tsx['offer']['description']) ?></textarea>
	</div>
</div>
<input type="hidden" name="page_id" class="form-control input-md" value="<?php echo $tsx['offer']['page_id'];?>">
<input type="hidden" name="offer_id" class="form-control input-md" value="<?php echo $tsx['offer']['id'];?>">
<input type="hidden" name="hash_id" value="<?php echo tsx_CreateSession();?>">